---
title: "10.04 LTS &quot;gave up waiting for root device&quot;"
date: 2010-08-14
forum: General Help
---

### Post by Vadtec on 2010-08-14
I am running 10.04 LTS on an old AMD Althon 64-bit MB. When I first installed Ubuntu, everything was working great. Then, a few weeks ago, I did a standard update and rebooted. At this point, I started getting "gave up waiting on root device" and related errors. After trying various fixes ranging from adding rootdelay=XX and root=/dev/sda1 and related, I have not been able to get my box to boot without having to sit and wait for a very long time.

Also, for whatever reason, Ubuntu now refuses to detect my DVD burner and 120GB HD. When I do ls /dev/sd*, I see sda (80GB HD below) and sdb (250GB HD below), but I do not see sdc and sdd.

Here is the assignment of drives as reported by the BIOS.

Primary IDE Master: WDC WD800JB-00ETA0 (80GB WD HD, set as boot drive and where ubuntu is installed to)
Primary IDE Slave:  WDC WD2500JB-00GVA0 (250GB WD HD)
Secondary IDE Master: LITE-ON DVDRW SOHW-1683S (DVD-RW/dual layer/DVD-RAM burner)
Secondary IDE Slave:  WDC WD1200JB-00GVA0 (120GB WD HD, NTFS file system, uses ntfs-3g)

I noticed that if I go into the BIOS and sit for a while then exit the BIOS, Ubuntu loads just fine. I don't know how long I have to sit there before Ubuntu will fully load just fine, so this confuses me.

Here is the output from dmesg when I have trouble booting. The interesting section starts around index 0.839746 where it tries to find all the hardware.
```

[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 2.6.32-24-generic (buildd@yellow) (gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) ) #39-Ubuntu SMP Wed Jul 28 05:14:15 UTC 2010 (Ubuntu 2.6.32-24.39-generic 2.6.32.15+drm33.5)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-2.6.32-24-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] BIOS-provided physical RAM map:
[    0.000000]  BIOS-e820: 0000000000000000 - 000000000009fc00 (usable)
[    0.000000]  BIOS-e820: 000000000009fc00 - 00000000000a0000 (reserved)
[    0.000000]  BIOS-e820: 00000000000e4000 - 0000000000100000 (reserved)
[    0.000000]  BIOS-e820: 0000000000100000 - 000000007ffd0000 (usable)
[    0.000000]  BIOS-e820: 000000007ffd0000 - 000000007ffde000 (ACPI data)
[    0.000000]  BIOS-e820: 000000007ffde000 - 0000000080000000 (ACPI NVS)
[    0.000000]  BIOS-e820: 00000000fec00000 - 00000000fec01000 (reserved)
[    0.000000]  BIOS-e820: 00000000ff780000 - 0000000100000000 (reserved)
[    0.000000] DMI 2.3 present.
[    0.000000] AMI BIOS detected: BIOS may corrupt low RAM, working around it.
[    0.000000] e820 update range: 0000000000000000 - 0000000000010000 (usable) ==> (reserved)
[    0.000000] last_pfn = 0x7ffd0 max_arch_pfn = 0x400000000
[    0.000000] MTRR default type: uncachable
[    0.000000] MTRR fixed ranges enabled:
[    0.000000]   00000-9FFFF write-back
[    0.000000]   A0000-EFFFF uncachable
[    0.000000]   F0000-FFFFF write-protect
[    0.000000] MTRR variable ranges enabled:
[    0.000000]   0 base 0000000000 mask FF80000000 write-back
[    0.000000]   1 disabled
[    0.000000]   2 disabled
[    0.000000]   3 disabled
[    0.000000]   4 disabled
[    0.000000]   5 disabled
[    0.000000]   6 disabled
[    0.000000]   7 disabled
[    0.000000] x86 PAT enabled: cpu 0, old 0x7040600070406, new 0x7010600070106
[    0.000000] Scanning 0 areas for low memory corruption
[    0.000000] modified physical RAM map:
[    0.000000]  modified: 0000000000000000 - 0000000000010000 (reserved)
[    0.000000]  modified: 0000000000010000 - 000000000009fc00 (usable)
[    0.000000]  modified: 000000000009fc00 - 00000000000a0000 (reserved)
[    0.000000]  modified: 00000000000e4000 - 0000000000100000 (reserved)
[    0.000000]  modified: 0000000000100000 - 000000007ffd0000 (usable)
[    0.000000]  modified: 000000007ffd0000 - 000000007ffde000 (ACPI data)
[    0.000000]  modified: 000000007ffde000 - 0000000080000000 (ACPI NVS)
[    0.000000]  modified: 00000000fec00000 - 00000000fec01000 (reserved)
[    0.000000]  modified: 00000000ff780000 - 0000000100000000 (reserved)
[    0.000000] initial memory mapped : 0 - 20000000
[    0.000000] init_memory_mapping: 0000000000000000-000000007ffd0000
[    0.000000] NX (Execute Disable) protection: active
[    0.000000]  0000000000 - 007fe00000 page 2M
[    0.000000]  007fe00000 - 007ffd0000 page 4k
[    0.000000] kernel direct mapping tables up to 7ffd0000 @ 10000-14000
[    0.000000] RAMDISK: 377fc000 - 37fef849
[    0.000000] ACPI: RSDP 00000000000f9350 00014 (v00 ACPIAM)
[    0.000000] ACPI: RSDT 000000007ffd0000 00030 (v01 A M I  OEMRSDT  07000526 MSFT 00000097)
[    0.000000] ACPI: FACP 000000007ffd0200 00084 (v02 A M I  OEMFACP  07000526 MSFT 00000097)
[    0.000000] ACPI: DSDT 000000007ffd03f0 03BD4 (v01  1XXXX 1XXXX005 00000005 INTL 02002026)
[    0.000000] ACPI: FACS 000000007ffde000 00040
[    0.000000] ACPI: APIC 000000007ffd0390 00054 (v01 A M I  OEMAPIC  07000526 MSFT 00000097)
[    0.000000] ACPI: OEMB 000000007ffde040 00046 (v01 A M I  AMI_OEM  07000526 MSFT 00000097)
[    0.000000] ACPI: Local APIC address 0xfee00000
[    0.000000] Scanning NUMA topology in Northbridge 24
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at 0000000000000000-000000007ffd0000
[    0.000000] Bootmem setup node 0 0000000000000000-000000007ffd0000
[    0.000000]   NODE_DATA [0000000000012000 - 0000000000016fff]
[    0.000000]   bootmap [0000000000017000 -  0000000000026fff] pages 10
[    0.000000] (7 early reservations) ==> bootmem [0000000000 - 007ffd0000]
[    0.000000]   #0 [0000000000 - 0000001000]   BIOS data page ==> [0000000000 - 0000001000]
[    0.000000]   #1 [0000006000 - 0000008000]       TRAMPOLINE ==> [0000006000 - 0000008000]
[    0.000000]   #2 [0001000000 - 0001a2fe64]    TEXT DATA BSS ==> [0001000000 - 0001a2fe64]
[    0.000000]   #3 [00377fc000 - 0037fef849]          RAMDISK ==> [00377fc000 - 0037fef849]
[    0.000000]   #4 [000009fc00 - 0000100000]    BIOS reserved ==> [000009fc00 - 0000100000]
[    0.000000]   #5 [0001a30000 - 0001a30190]              BRK ==> [0001a30000 - 0001a30190]
[    0.000000]   #6 [0000010000 - 0000012000]          PGTABLE ==> [0000010000 - 0000012000]
[    0.000000] found SMP MP-table at [ffff8800000ff780] ff780
[    0.000000]  [ffffea0000000000-ffffea0001bfffff] PMD -> [ffff880002000000-ffff880003bfffff] on node 0
[    0.000000] Zone PFN ranges:
[    0.000000]   DMA      0x00000010 -> 0x00001000
[    0.000000]   DMA32    0x00001000 -> 0x00100000
[    0.000000]   Normal   0x00100000 -> 0x00100000
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[2] active PFN ranges
[    0.000000]     0: 0x00000010 -> 0x0000009f
[    0.000000]     0: 0x00000100 -> 0x0007ffd0
[    0.000000] On node 0 totalpages: 524127
[    0.000000]   DMA zone: 56 pages used for memmap
[    0.000000]   DMA zone: 101 pages reserved
[    0.000000]   DMA zone: 3826 pages, LIFO batch:0
[    0.000000]   DMA32 zone: 7112 pages used for memmap
[    0.000000]   DMA32 zone: 513032 pages, LIFO batch:31
[    0.000000] ACPI: PM-Timer IO Port: 0x808
[    0.000000] ACPI: Local APIC address 0xfee00000
[    0.000000] ACPI: LAPIC (acpi_id[0x01] lapic_id[0x00] enabled)
[    0.000000] ACPI: IOAPIC (id[0x01] address[0xfec00000] gsi_base[0])
[    0.000000] IOAPIC[0]: apic_id 1, version 3, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 low level)
[    0.000000] ACPI: IRQ0 used by override.
[    0.000000] ACPI: IRQ2 used by override.
[    0.000000] ACPI: IRQ9 used by override.
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] SMP: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] nr_irqs_gsi: 24
[    0.000000] PM: Registered nosave memory: 000000000009f000 - 00000000000a0000
[    0.000000] PM: Registered nosave memory: 00000000000a0000 - 00000000000e4000
[    0.000000] PM: Registered nosave memory: 00000000000e4000 - 0000000000100000
[    0.000000] Allocating PCI resources starting at 80000000 (gap: 80000000:7ec00000)
[    0.000000] Booting paravirtualized kernel on bare hardware
[    0.000000] NR_CPUS:64 nr_cpumask_bits:64 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] PERCPU: Embedded 30 pages/cpu @ffff880001c00000 s91544 r8192 d23144 u2097152
[    0.000000] pcpu-alloc: s91544 r8192 d23144 u2097152 alloc=1*2097152
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 516858
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-2.6.32-24-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Initializing CPU#0
[    0.000000] Checking aperture...
[    0.000000] AGP bridge at 00:00:00
[    0.000000] Aperture from AGP @ e0000000 old size 32 MB
[    0.000000] Aperture from AGP @ e0000000 size 256 MB (APSIZE f00)
[    0.000000] Node 0: aperture @ d0000000 size 256 MB
[    0.000000] Memory: 2048972k/2096960k available (5422k kernel code, 452k absent, 47536k reserved, 2979k data, 880k init)
[    0.000000] SLUB: Genslabs=14, HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS:4352 nr_irqs:256
[    0.000000] spurious 8259A interrupt: IRQ7.
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty0] enabled
[    0.000000] allocated 20971520 bytes of page_cgroup
[    0.000000] please try 'cgroup_disable=memory' option if you don't want memory cgroups
[    0.000000] Fast TSC calibration using PIT
[    0.000000] Detected 1599.886 MHz processor.
[    0.010006] Calibrating delay loop (skipped), value calculated using timer frequency.. 3199.77 BogoMIPS (lpj=15998860)
[    0.010040] Security Framework initialized
[    0.010069] AppArmor: AppArmor initialized
[    0.010326] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes)
[    0.012239] Inode-cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.020595] Mount-cache hash table entries: 256
[    0.020790] Initializing cgroup subsys ns
[    0.020795] Initializing cgroup subsys cpuacct
[    0.020801] Initializing cgroup subsys memory
[    0.020814] Initializing cgroup subsys devices
[    0.020817] Initializing cgroup subsys freezer
[    0.020820] Initializing cgroup subsys net_cls
[    0.020845] CPU: L1 I Cache: 64K (64 bytes/line), D cache 64K (64 bytes/line)
[    0.020848] CPU: L2 Cache: 256K (64 bytes/line)
[    0.020852] CPU 0/0x0 -> Node 0
[    0.020854] tseg: 0000000000
[    0.020876] mce: CPU supports 5 MCE banks
[    0.020890] Performance Events: AMD PMU driver.
[    0.020897] ... version:                0
[    0.020899] ... bit width:              48
[    0.020901] ... generic registers:      4
[    0.020903] ... value mask:             0000ffffffffffff
[    0.020906] ... max period:             00007fffffffffff
[    0.020908] ... fixed-purpose events:   0
[    0.020910] ... event mask:             000000000000000f
[    0.020925] SMP alternatives: switching to UP code
[    0.033196] Freeing SMP alternatives: 40k freed
[    0.033234] ACPI: Core revision 20090903
[    0.040013] ftrace: converting mcount calls to 0f 1f 44 00 00
[    0.040021] ftrace: allocating 22527 entries in 89 pages
[    0.047163] Setting APIC routing to flat
[    0.048013] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=0 pin2=0
[    0.149112] CPU0: AMD Sempron(tm) Processor 2800+ stepping 02
[    0.150000] Brought up 1 CPUs
[    0.150000] Total of 1 processors activated (3199.77 BogoMIPS).
[    0.150000] CPU0 attaching NULL sched-domain.
[    0.150000] devtmpfs: initialized
[    0.150000] regulator: core version 0.5
[    0.150000] Time: 12:48:27  Date: 08/13/10
[    0.150000] NET: Registered protocol family 16
[    0.150000] node 0 link 0: io port [1000, ffffff]
[    0.150000] TOM: 0000000080000000 aka 2048M
[    0.150000] node 0 link 0: mmio [a0000, bffff]
[    0.150000] node 0 link 0: mmio [80000000, ffffffff]
[    0.150000] bus: [00,ff] on node 0 link 0
[    0.150000] bus: 00 index 0 io port: [0, ffff]
[    0.150000] bus: 00 index 1 mmio: [a0000, bffff]
[    0.150000] bus: 00 index 2 mmio: [80000000, fcffffffff]
[    0.150000] ACPI: bus type pci registered
[    0.150000] PCI: Using configuration type 1 for base access
[    0.150000] bio: create slab <bio-0> at 0
[    0.150000] ACPI: EC: Look up EC in DSDT
[    0.150000] ACPI: Executed 1 blocks of module-level executable AML code
[    0.152134] ACPI: Interpreter enabled
[    0.152140] ACPI: (supports S0 S1 S4 S5)
[    0.152164] ACPI: Using IOAPIC for interrupt routing
[    0.161501] ACPI Warning: Incorrect checksum in table [OEMB] - 8C, should be 86 (20090903/tbutils-314)
[    0.161642] ACPI: No dock devices found.
[    0.161795] ACPI: PCI Root Bridge [PCI0] (0000:00)
[    0.161860] pci 0000:00:00.0: reg 10 32bit mmio pref: [0xe0000000-0xefffffff]
[    0.162161] pci 0000:00:01.0: supports D1
[    0.162201] pci 0000:00:08.0: reg 10 io port: [0xe800-0xe8ff]
[    0.162209] pci 0000:00:08.0: reg 14 32bit mmio: [0xff6ffc00-0xff6fffff]
[    0.162231] pci 0000:00:08.0: reg 30 32bit mmio pref: [0xff6c0000-0xff6dffff]
[    0.162250] pci 0000:00:08.0: supports D1 D2
[    0.162253] pci 0000:00:08.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.162258] pci 0000:00:08.0: PME# disabled
[    0.162292] pci 0000:00:0a.0: reg 10 32bit mmio: [0xff6f0000-0xff6f7fff]
[    0.162388] pci 0000:00:0f.0: reg 20 io port: [0xfc00-0xfc0f]
[    0.162464] pci 0000:00:10.0: reg 20 io port: [0xec00-0xec1f]
[    0.162489] pci 0000:00:10.0: supports D1 D2
[    0.162492] pci 0000:00:10.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.162496] pci 0000:00:10.0: PME# disabled
[    0.162544] pci 0000:00:10.1: reg 20 io port: [0xe400-0xe41f]
[    0.162569] pci 0000:00:10.1: supports D1 D2
[    0.162572] pci 0000:00:10.1: PME# supported from D0 D1 D2 D3hot D3cold
[    0.162576] pci 0000:00:10.1: PME# disabled
[    0.162624] pci 0000:00:10.2: reg 20 io port: [0xe000-0xe01f]
[    0.162649] pci 0000:00:10.2: supports D1 D2
[    0.162651] pci 0000:00:10.2: PME# supported from D0 D1 D2 D3hot D3cold
[    0.162656] pci 0000:00:10.2: PME# disabled
[    0.162703] pci 0000:00:10.3: reg 20 io port: [0xdc00-0xdc1f]
[    0.162728] pci 0000:00:10.3: supports D1 D2
[    0.162731] pci 0000:00:10.3: PME# supported from D0 D1 D2 D3hot D3cold
[    0.162736] pci 0000:00:10.3: PME# disabled
[    0.162768] pci 0000:00:10.4: reg 10 32bit mmio: [0xff6ff400-0xff6ff4ff]
[    0.162809] pci 0000:00:10.4: supports D1 D2
[    0.162811] pci 0000:00:10.4: PME# supported from D0 D1 D2 D3hot D3cold
[    0.162816] pci 0000:00:10.4: PME# disabled
[    0.162878] HPET not enabled in BIOS. You might try hpet=force boot option
[    0.162935] pci 0000:00:11.5: reg 10 io port: [0xd800-0xd8ff]
[    0.162978] pci 0000:00:11.5: supports D1 D2
[    0.163013] pci 0000:00:12.0: reg 10 io port: [0xd400-0xd4ff]
[    0.163021] pci 0000:00:12.0: reg 14 32bit mmio: [0xff6ff000-0xff6ff0ff]
[    0.163058] pci 0000:00:12.0: supports D1 D2
[    0.163061] pci 0000:00:12.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.163065] pci 0000:00:12.0: PME# disabled
[    0.163198] pci 0000:01:00.0: reg 10 32bit mmio pref: [0xc0000000-0xcfffffff]
[    0.163205] pci 0000:01:00.0: reg 14 io port: [0xc800-0xc8ff]
[    0.163210] pci 0000:01:00.0: reg 18 32bit mmio: [0xff5f0000-0xff5fffff]
[    0.163224] pci 0000:01:00.0: reg 30 32bit mmio pref: [0xff5c0000-0xff5dffff]
[    0.163242] pci 0000:01:00.0: supports D1 D2
[    0.163267] pci 0000:01:00.1: reg 10 32bit mmio pref: [0xb0000000-0xbfffffff]
[    0.163273] pci 0000:01:00.1: reg 14 32bit mmio: [0xff5e0000-0xff5effff]
[    0.163300] pci 0000:01:00.1: supports D1 D2
[    0.163334] pci 0000:00:01.0: bridge io port: [0xc000-0xcfff]
[    0.163339] pci 0000:00:01.0: bridge 32bit mmio: [0xff500000-0xff5fffff]
[    0.163344] pci 0000:00:01.0: bridge 32bit mmio pref: [0x9eb00000-0xdeafffff]
[    0.163356] ACPI: PCI Interrupt Routing Table [\_SB_.PCI0._PRT]
[    0.180501] ACPI: PCI Interrupt Link [LNKA] (IRQs 3 4 5 6 7 *10 11 12 14 15)
[    0.180628] ACPI: PCI Interrupt Link [LNKB] (IRQs 3 4 *5 6 7 10 11 12 14 15)
[    0.180748] ACPI: PCI Interrupt Link [LNKC] (IRQs 3 4 5 6 7 10 *11 12 14 15)
[    0.180868] ACPI: PCI Interrupt Link [LNKD] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.180989] ACPI: PCI Interrupt Link [LNKE] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.181110] ACPI: PCI Interrupt Link [LNKF] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.181231] ACPI: PCI Interrupt Link [LNKG] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.181351] ACPI: PCI Interrupt Link [LNKH] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.181496] vgaarb: device added: PCI:0000:01:00.0,decodes=io+mem,owns=io+mem,locks=none
[    0.181499] vgaarb: loaded
[    0.181645] SCSI subsystem initialized
[    0.181738] libata version 3.00 loaded.
[    0.181827] usbcore: registered new interface driver usbfs
[    0.181841] usbcore: registered new interface driver hub
[    0.181871] usbcore: registered new device driver usb
[    0.182032] ACPI: WMI: Mapper loaded
[    0.182034] PCI: Using ACPI for IRQ routing
[    0.182044] pci 0000:00:01.0: BAR 15: address space collision on of bridge [0x9eb00000-0xdeafffff]
[    0.182048] pci 0000:00:01.0: BAR 15: can't allocate resource
[    0.182093] pci 0000:01:00.0: BAR 0: no parent found for of device [0xc0000000-0xcfffffff]
[    0.182097] pci 0000:01:00.0: BAR 0: can't allocate resource
[    0.182102] pci 0000:01:00.1: BAR 0: no parent found for of device [0xb0000000-0xbfffffff]
[    0.182105] pci 0000:01:00.1: BAR 0: can't allocate resource
[    0.182253] NetLabel: Initializing
[    0.182255] NetLabel:  domain hash size = 128
[    0.182257] NetLabel:  protocols = UNLABELED CIPSOv4
[    0.182274] NetLabel:  unlabeled traffic allowed by default
[    0.182347] Switching to clocksource tsc
[    0.184554] AppArmor: AppArmor Filesystem Enabled
[    0.184580] pnp: PnP ACPI init
[    0.184604] ACPI: bus type pnp registered
[    0.189087] pnp 00:0d: mem resource (0x0-0x9ffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.189093] pnp 00:0d: mem resource (0xc0000-0xcffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.189097] pnp 00:0d: mem resource (0xe0000-0xfffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.189102] pnp 00:0d: mem resource (0x100000-0x7fffffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.189108] pnp 00:0d: mem resource (0x0-0x9ffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.189112] pnp 00:0d: mem resource (0xc0000-0xcffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.189117] pnp 00:0d: mem resource (0xe0000-0xfffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.189121] pnp 00:0d: mem resource (0x100000-0x7fffffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.189495] pnp: PnP ACPI: found 14 devices
[    0.189498] ACPI: ACPI bus type pnp unregistered
[    0.189515] system 00:0a: ioport range 0x680-0x6ff has been reserved
[    0.189519] system 00:0a: ioport range 0x295-0x296 has been reserved
[    0.189527] system 00:0b: ioport range 0x3e0-0x3e7 has been reserved
[    0.189530] system 00:0b: ioport range 0x4d0-0x4d1 has been reserved
[    0.189534] system 00:0b: ioport range 0x800-0x87f has been reserved
[    0.189537] system 00:0b: ioport range 0x400-0x41f has been reserved
[    0.189552] system 00:0c: iomem range 0xfec00000-0xfec00fff could not be reserved
[    0.189556] system 00:0c: iomem range 0xfee00000-0xfee00fff has been reserved
[    0.189564] system 00:0d: iomem range 0xfff80000-0xffffffff has been reserved
[    0.191923] pci 0000:00:01.0: PCI bridge, secondary bus 0000:01
[    0.191927] pci 0000:00:01.0:   IO window: 0xc000-0xcfff
[    0.191932] pci 0000:00:01.0:   MEM window: 0xff500000-0xff5fffff
[    0.191937] pci 0000:00:01.0:   PREFETCH window: 0x80000000-0x9fffffff
[    0.191954] pci 0000:00:01.0: setting latency timer to 64
[    0.191960] pci_bus 0000:00: resource 0 io:  [0x00-0xffff]
[    0.191963] pci_bus 0000:00: resource 1 mem: [0x000000-0xffffffffffffffff]
[    0.191967] pci_bus 0000:01: resource 0 io:  [0xc000-0xcfff]
[    0.191971] pci_bus 0000:01: resource 1 mem: [0xff500000-0xff5fffff]
[    0.191974] pci_bus 0000:01: resource 2 pref mem [0x80000000-0x9fffffff]
[    0.192022] NET: Registered protocol family 2
[    0.192181] IP route cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.193389] TCP established hash table entries: 262144 (order: 10, 4194304 bytes)
[    0.197429] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[    0.198392] TCP: Hash tables configured (established 262144 bind 65536)
[    0.198396] TCP reno registered
[    0.198539] NET: Registered protocol family 1
[    0.198571] pci 0000:00:01.0: disabling DAC on VIA PCI bridge
[    0.198670] pci 0000:01:00.0: Boot video device
[    0.198795] agpgart-amd64 0000:00:00.0: AGP bridge [1106/0282]
[    0.208094] Trying to unpack rootfs image as initramfs...
[    0.218186] agpgart-amd64 0000:00:00.0: AGP aperture is 256M @ 0xd0000000
[    0.218400] Scanning for low memory corruption every 60 seconds
[    0.218563] audit: initializing netlink socket (disabled)
[    0.218579] type=2000 audit(1281703707.217:1): initialized
[    0.248235] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    0.250061] VFS: Disk quotas dquot_6.5.2
[    0.250145] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.250980] fuse init (API version 7.13)
[    0.251087] msgmni has been set to 4001
[    0.251371] alg: No test for stdrng (krng)
[    0.251452] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    0.251456] io scheduler noop registered
[    0.251458] io scheduler anticipatory registered
[    0.251460] io scheduler deadline registered
[    0.251508] io scheduler cfq registered (default)
[    0.251700] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    0.251727] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    0.251848] input: Sleep Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input0
[    0.251857] ACPI: Sleep Button [SLPB]
[    0.251915] input: Power Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1
[    0.251919] ACPI: Power Button [PWRB]
[    0.251972] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input2
[    0.251975] ACPI: Power Button [PWRF]
[    0.252379] processor LNXCPU:00: registered as cooling_device0
[    0.268459] Linux agpgart interface v0.103
[    0.268505] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.268610] serial8250: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    0.268948] 00:07: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    0.270186] brd: module loaded
[    0.270765] loop: module loaded
[    0.270902] input: Macintosh mouse button emulation as /devices/virtual/input/input3
[    0.271184]   alloc irq_desc for 20 on node 0
[    0.271188]   alloc kstat_irqs on node 0
[    0.271197] pata_acpi 0000:00:0f.0: PCI INT A -> GSI 20 (level, low) -> IRQ 20
[    0.271253] pata_acpi 0000:00:0f.0: PCI INT A disabled
[    0.271707] Fixed MDIO Bus: probed
[    0.271759] PPP generic driver version 2.4.2
[    0.271830] tun: Universal TUN/TAP device driver, 1.6
[    0.271832] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    0.271938] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.272016]   alloc irq_desc for 21 on node 0
[    0.272019]   alloc kstat_irqs on node 0
[    0.272026] ehci_hcd 0000:00:10.4: PCI INT C -> GSI 21 (level, low) -> IRQ 21
[    0.272047] ehci_hcd 0000:00:10.4: EHCI Host Controller
[    0.272095] ehci_hcd 0000:00:10.4: new USB bus registered, assigned bus number 1
[    0.272170] ehci_hcd 0000:00:10.4: irq 21, io mem 0xff6ff400
[    0.287721] ehci_hcd 0000:00:10.4: USB 2.0 started, EHCI 1.00
[    0.287893] usb usb1: configuration #1 chosen from 1 choice
[    0.287931] hub 1-0:1.0: USB hub found
[    0.287943] hub 1-0:1.0: 8 ports detected
[    0.288052] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.288073] uhci_hcd: USB Universal Host Controller Interface driver
[    0.297753] uhci_hcd 0000:00:10.0: PCI INT A -> GSI 21 (level, low) -> IRQ 21
[    0.297768] uhci_hcd 0000:00:10.0: UHCI Host Controller
[    0.297859] uhci_hcd 0000:00:10.0: new USB bus registered, assigned bus number 2
[    0.297894] uhci_hcd 0000:00:10.0: irq 21, io base 0x0000ec00
[    0.298034] usb usb2: configuration #1 chosen from 1 choice
[    0.298068] hub 2-0:1.0: USB hub found
[    0.298079] hub 2-0:1.0: 2 ports detected
[    0.298218] uhci_hcd 0000:00:10.1: PCI INT A -> GSI 21 (level, low) -> IRQ 21
[    0.298230] uhci_hcd 0000:00:10.1: UHCI Host Controller
[    0.298287] uhci_hcd 0000:00:10.1: new USB bus registered, assigned bus number 3
[    0.298313] uhci_hcd 0000:00:10.1: irq 21, io base 0x0000e400
[    0.298434] usb usb3: configuration #1 chosen from 1 choice
[    0.298464] hub 3-0:1.0: USB hub found
[    0.298473] hub 3-0:1.0: 2 ports detected
[    0.298586] uhci_hcd 0000:00:10.2: PCI INT B -> GSI 21 (level, low) -> IRQ 21
[    0.298595] uhci_hcd 0000:00:10.2: UHCI Host Controller
[    0.298645] uhci_hcd 0000:00:10.2: new USB bus registered, assigned bus number 4
[    0.298669] uhci_hcd 0000:00:10.2: irq 21, io base 0x0000e000
[    0.298786] usb usb4: configuration #1 chosen from 1 choice
[    0.298819] hub 4-0:1.0: USB hub found
[    0.298827] hub 4-0:1.0: 2 ports detected
[    0.298934] uhci_hcd 0000:00:10.3: PCI INT B -> GSI 21 (level, low) -> IRQ 21
[    0.298943] uhci_hcd 0000:00:10.3: UHCI Host Controller
[    0.298988] uhci_hcd 0000:00:10.3: new USB bus registered, assigned bus number 5
[    0.299013] uhci_hcd 0000:00:10.3: irq 21, io base 0x0000dc00
[    0.299137] usb usb5: configuration #1 chosen from 1 choice
[    0.299167] hub 5-0:1.0: USB hub found
[    0.299176] hub 5-0:1.0: 2 ports detected
[    0.299302] PNP: PS/2 Controller [PNP0303:PS2K,PNP0f03:PS2M] at 0x60,0x64 irq 1,12
[    0.299791] serio: i8042 KBD port at 0x60,0x64 irq 1
[    0.299798] serio: i8042 AUX port at 0x60,0x64 irq 12
[    0.299896] mice: PS/2 mouse device common for all mice
[    0.300033] rtc_cmos 00:02: RTC can wake from S4
[    0.300085] rtc_cmos 00:02: rtc core: registered rtc_cmos as rtc0
[    0.300139] rtc0: alarms up to one year, y3k, 114 bytes nvram
[    0.300314] device-mapper: uevent: version 1.0.3
[    0.300528] device-mapper: ioctl: 4.15.0-ioctl (2009-04-01) initialised: dm-devel@redhat.com
[    0.305179] device-mapper: multipath: version 1.1.0 loaded
[    0.305185] device-mapper: multipath round-robin: version 1.0.0 loaded
[    0.305427] cpuidle: using governor ladder
[    0.305430] cpuidle: using governor menu
[    0.305897] TCP cubic registered
[    0.306083] NET: Registered protocol family 10
[    0.306721] lo: Disabled Privacy Extensions
[    0.307134] NET: Registered protocol family 17
[    0.307183] powernow-k8: Power state transitions not supported
[    0.307318] PM: Resume from disk failed.
[    0.307333] registered taskstats version 1
[    0.307726]   Magic number: 6:49:835
[    0.307824] rtc_cmos 00:02: setting system clock to 2010-08-13 12:48:27 UTC (1281703707)
[    0.307828] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    0.307830] EDD information not available.
[    0.328862] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input4
[    0.498542] Freeing initrd memory: 8142k freed
[    0.505839] Freeing unused kernel memory: 880k freed
[    0.506616] Write protecting the kernel read-only data: 7696k
[    0.535387] udev: starting version 151
[    0.824355] via-rhine.c:v1.10-LK1.4.3 2007-03-06 Written by Donald Becker
[    0.824447] Linux Tulip driver version 1.1.15 (Feb 27, 2007)
[    0.830075]   alloc irq_desc for 23 on node 0
[    0.830079]   alloc kstat_irqs on node 0
[    0.830089] via-rhine 0000:00:12.0: PCI INT A -> GSI 23 (level, low) -> IRQ 23
[    0.830914] eth0: VIA Rhine II at 0xff6ff000, 00:13:d3:a7:0a:a4, IRQ 23.
[    0.831625] eth0: MII PHY found at address 1, status 0x786d advertising 01e1 Link 45e1.
[    0.832255]   alloc irq_desc for 16 on node 0
[    0.832260]   alloc kstat_irqs on node 0
[    0.832270] tulip 0000:00:08.0: PCI INT A -> GSI 16 (level, low) -> IRQ 16
[    0.832846] tulip0:  MII transceiver #1 config 1000 status 7849 advertising 05e1.
[    0.839131] eth1: ADMtek Comet rev 17 at Port 0xe800, 00:0c:41:1d:bf:19, IRQ 16.
[    0.839746] pata_via 0000:00:0f.0: version 0.3.4
[    0.839765] pata_via 0000:00:0f.0: PCI INT A -> GSI 20 (level, low) -> IRQ 20
[    0.839986] scsi0 : pata_via
[    0.840260] scsi1 : pata_via
[    0.843597] ata1: PATA max UDMA/133 cmd 0x1f0 ctl 0x3f6 bmdma 0xfc00 irq 14
[    0.843601] ata2: PATA max UDMA/133 cmd 0x170 ctl 0x376 bmdma 0xfc08 irq 15
[    1.039089] ata1.00: ATA-6: WDC WD800JB-00ETA0, 77.07W77, max UDMA/100
[    1.039094] ata1.00: 156301488 sectors, multi 16: LBA48 
[    1.040487] ata1.01: ATA-6: WDC WD2500JB-00GVA0, 08.02D08, max UDMA/100
[    1.040491] ata1.01: 488397168 sectors, multi 16: LBA48 
[    1.040517] ata1.00: limited to UDMA/33 due to 40-wire cable
[    1.040520] ata1.01: limited to UDMA/33 due to 40-wire cable
[    1.078914] ata1.00: configured for UDMA/33
[    1.119230] ata1.01: configured for UDMA/33
[    1.119360] scsi 0:0:0:0: Direct-Access     ATA      WDC WD800JB-00ET 77.0 PQ: 0 ANSI: 5
[    1.119569] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    1.119921] scsi 0:0:1:0: Direct-Access     ATA      WDC WD2500JB-00G 08.0 PQ: 0 ANSI: 5
[    1.120187] sd 0:0:1:0: Attached scsi generic sg1 type 0
[    1.120371] sd 0:0:0:0: [sda] 156301488 512-byte logical blocks: (80.0 GB/74.5 GiB)
[    1.120426] sd 0:0:0:0: [sda] Write Protect is off
[    1.120429] sd 0:0:0:0: [sda] Mode Sense: 00 3a 00 00
[    1.120457] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.120627]  sda: sda1 sda2 < sda5 >
[    1.161934] sd 0:0:0:0: [sda] Attached SCSI disk
[    1.161951] sd 0:0:1:0: [sdb] 488397168 512-byte logical blocks: (250 GB/232 GiB)
[    1.162000] sd 0:0:1:0: [sdb] Write Protect is off
[    1.162004] sd 0:0:1:0: [sdb] Mode Sense: 00 3a 00 00
[    1.162030] sd 0:0:1:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.162204]  sdb:
[    1.178381] sd 0:0:1:0: [sdb] Attached SCSI disk
[    6.320016] ata2: link is slow to respond, please be patient (ready=0)
[   11.180012] ata2: SRST failed (errno=-16)
[   16.380014] ata2: link is slow to respond, please be patient (ready=0)
[   21.240014] ata2: SRST failed (errno=-16)
[   26.440014] ata2: link is slow to respond, please be patient (ready=0)
[   32.380073] ata2.01: link status unknown, clearing UNKNOWN to NONE
[   37.380027] ata2.00: qc timeout (cmd 0xa1)
[   37.380035] ata2.00: failed to IDENTIFY (I/O error, err_mask=0x4)
[   42.420014] ata2: link is slow to respond, please be patient (ready=0)
[   47.400014] ata2: device not ready (errno=-16), forcing hardreset
[   52.600014] ata2: link is slow to respond, please be patient (ready=0)
[   57.460014] ata2: SRST failed (errno=-16)
[   62.660009] ata2: link is slow to respond, please be patient (ready=0)
[   63.500061] ata2.01: link status unknown, clearing UNKNOWN to NONE
[   73.500023] ata2.00: qc timeout (cmd 0xa1)
[   73.500029] ata2.00: failed to IDENTIFY (I/O error, err_mask=0x4)
[   78.540014] ata2: link is slow to respond, please be patient (ready=0)
[   83.520014] ata2: device not ready (errno=-16), forcing hardreset
[   88.720014] ata2: link is slow to respond, please be patient (ready=0)
[   93.580014] ata2: SRST failed (errno=-16)
[   94.640062] ata2.01: link status unknown, clearing UNKNOWN to NONE
[  124.640026] ata2.00: qc timeout (cmd 0xa1)
[  124.640033] ata2.00: failed to IDENTIFY (I/O error, err_mask=0x4)
[  130.800014] ata2: link is slow to respond, please be patient (ready=0)
[  135.660009] ata2: SRST failed (errno=-16)
[  140.860014] ata2: link is slow to respond, please be patient (ready=0)
[  145.720014] ata2: SRST failed (errno=-16)
[  150.920014] ata2: link is slow to respond, please be patient (ready=0)
[  156.860061] ata2.01: link status unknown, clearing UNKNOWN to NONE
[  410.797152] EXT4-fs (sda1): mounted filesystem with ordered data mode
[  422.895639] udev: starting version 151
[  422.943550] Adding 3229024k swap on /dev/sda5.  Priority:-1 extents:1 across:3229024k 
[  423.056126] lp: driver loaded but no devices found
[  423.157109] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
[  423.235018] udev: renamed network interface eth0 to eth1
[  423.255674] udev: renamed network interface eth1_rename to eth0
[  423.394285] cfg80211: Calling CRDA to update world regulatory domain
[  423.442367] ACPI: resource vt596_smbus [0x400-0x407] conflicts with ACPI region SMOV [0x400-0x406]
[  423.442372] ACPI: If an ACPI driver is available for this device, you should use it instead of the native driver
[  423.553593] EDAC MC: Ver: 2.1.0 Jul 28 2010
[  423.554748] parport_pc 00:08: reported by Plug and Play ACPI
[  423.554797] parport0: PC-style at 0x378, irq 7 [PCSPP,TRISTATE]
[  423.630670] lp0: using parport0 (interrupt-driven).
[  423.650334] type=1505 audit(1281704130.842:2):  operation="profile_load" pid=595 name="/sbin/dhclient3"
[  423.650731] type=1505 audit(1281704130.842:3):  operation="profile_load" pid=595 name="/usr/lib/NetworkManager/nm-dhcp-client.action"
[  423.650927] type=1505 audit(1281704130.842:4):  operation="profile_load" pid=595 name="/usr/lib/connman/scripts/dhclient-script"
[  423.711826] cfg80211: World regulatory domain updated:
[  423.711831]  (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[  423.711835]  (2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[  423.711839]  (2457000 KHz - 2482000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[  423.711843]  (2474000 KHz - 2494000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[  423.711846]  (5170000 KHz - 5250000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[  423.711849]  (5735000 KHz - 5835000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[  423.912282] EDAC amd64_edac:  Ver: 3.2.0 Jul 28 2010
[  423.930295] [drm] Initialized drm 1.1.0 20060810
[  423.941377] EDAC amd64: ECC is enabled by BIOS.
[  423.942017] EDAC MC: Rev E or earlier detected
[  423.942956] EDAC MC0: Giving out device to 'amd64_edac' 'RevF': DEV 0000:00:18.2
[  423.943529] EDAC PCI0: Giving out device to module 'amd64_edac' controller 'EDAC PCI controller': DEV '0000:00:18.2' (POLLED)
[  423.977893] ppdev: user-space parallel port driver
[  424.045452] input: PS2++ Logitech Wheel Mouse as /devices/platform/i8042/serio1/input/input5
[  424.046962] gameport: NS558 PnP Gameport is pnp00:09/gameport0, io 0x201, speed 780kHz
[  424.120748]   alloc irq_desc for 18 on node 0
[  424.120753]   alloc kstat_irqs on node 0
[  424.120765] rt61pci 0000:00:0a.0: PCI INT A -> GSI 18 (level, low) -> IRQ 18
[  424.173444] [drm] radeon defaulting to kernel modesetting.
[  424.173450] [drm] radeon kernel modesetting enabled.
[  424.174680] radeon 0000:01:00.0: PCI INT A -> GSI 16 (level, low) -> IRQ 16
[  424.193179] [drm] radeon: Initializing kernel modesetting.
[  424.196260] [drm] register mmio base: 0xFF5F0000
[  424.196264] [drm] register mmio size: 65536
[  424.197071] [drm] GPU reset succeed (RBBM_STATUS=0x00000140)
[  424.197098] [drm] Generation 2 PCI interface, using max accessible memory
[  424.197108] agpgart-amd64 0000:00:00.0: AGP 3.0 bridge
[  424.197129] agpgart-amd64 0000:00:00.0: putting AGP V3 device into 8x mode
[  424.197206] radeon 0000:01:00.0: putting AGP V3 device into 8x mode
[  424.197214] [drm] radeon: VRAM 256M
[  424.197217] [drm] radeon: VRAM from 0x00000000 to 0x0FFFFFFF
[  424.197219] [drm] radeon: GTT 256M
[  424.197221] [drm] radeon: GTT from 0xD0000000 to 0xDFFFFFFF
[  424.197275] [drm] radeon: irq initialized.
[  424.197380] [drm] Detected VRAM RAM=256M, BAR=256M
[  424.197386] [drm] RAM width 128bits DDR
[  424.201103] [TTM] Zone  kernel: Available graphics memory: 1029020 kiB.
[  424.201131] [drm] radeon: 256M of VRAM memory ready
[  424.201134] [drm] radeon: 256M of GTT memory ready.
[  424.201377] [drm] radeon: 1 quad pipes, 1 Z pipes initialized.
[  424.201391] [drm] radeon: cp idle (0x10000C03)
[  424.201514] [drm] Loading R300 Microcode
[  424.201938] platform radeon_cp.0: firmware: requesting radeon/R300_cp.bin
[  424.212085] phy0: Selected rate control algorithm 'minstrel'
[  424.213010] Registered led device: rt61pci-phy0::radio
[  424.213029] Registered led device: rt61pci-phy0::assoc
[  424.223036] [drm] radeon: ring at 0x00000000D0000000
[  424.223059] [drm] ring test succeeded in 1 usecs
[  424.225946] [drm] radeon: ib pool ready.
[  424.226045] [drm] ib test succeeded in 0 usecs
[  424.250850] [drm] Default TV standard: NTSC
[  424.250854] [drm] 27.000000000 MHz TV ref clk
[  424.250860] [drm] DFP table revision: 4
[  424.251597] [drm] Default TV standard: NTSC
[  424.251601] [drm] 27.000000000 MHz TV ref clk
[  424.251740] [drm] Radeon Display Connectors
[  424.251743] [drm] Connector 0:
[  424.251744] [drm]   VGA
[  424.251748] [drm]   DDC: 0x60 0x60 0x60 0x60 0x60 0x60 0x60 0x60
[  424.251750] [drm]   Encoders:
[  424.251752] [drm]     CRT1: INTERNAL_DAC1
[  424.251753] [drm] Connector 1:
[  424.251755] [drm]   DVI-I
[  424.251757] [drm]   HPD1
[  424.251759] [drm]   DDC: 0x64 0x64 0x64 0x64 0x64 0x64 0x64 0x64
[  424.251761] [drm]   Encoders:
[  424.251763] [drm]     CRT2: INTERNAL_DAC2
[  424.251765] [drm]     DFP1: INTERNAL_TMDS1
[  424.251767] [drm] Connector 2:
[  424.251769] [drm]   S-video
[  424.251770] [drm]   Encoders:
[  424.251772] [drm]     TV1: INTERNAL_DAC2
[  424.436393]   alloc irq_desc for 22 on node 0
[  424.436398]   alloc kstat_irqs on node 0
[  424.436408] VIA 82xx Audio 0000:00:11.5: PCI INT C -> GSI 22 (level, low) -> IRQ 22
[  424.436572] VIA 82xx Audio 0000:00:11.5: setting latency timer to 64
[  424.599669] [drm] fb mappable at 0x80040000
[  424.599673] [drm] vram apper at 0x80000000
[  424.599676] [drm] size 5242880
[  424.599678] [drm] fb depth is 24
[  424.599680] [drm]    pitch is 5120
[  424.600141] fb0: radeondrmfb frame buffer device
[  424.600144] registered panic notifier
[  424.600153] [drm] Initialized radeon 2.0.0 20080528 for 0000:01:00.0 on minor 0
[  424.602744] vga16fb: initializing
[  424.602750] vga16fb: mapped to 0xffff8800000a0000
[  424.602756] vga16fb: not registering due to another framebuffer present
[  424.775981] Console: switching to colour frame buffer device 160x64
[  446.504123] type=1505 audit(1281704153.692:5):  operation="profile_load" pid=856 name="/usr/share/gdm/guest-session/Xsession"
[  446.506313] type=1505 audit(1281704153.692:6):  operation="profile_replace" pid=857 name="/sbin/dhclient3"
[  446.506684] type=1505 audit(1281704153.692:7):  operation="profile_replace" pid=857 name="/usr/lib/NetworkManager/nm-dhcp-client.action"
[  446.506892] type=1505 audit(1281704153.692:8):  operation="profile_replace" pid=857 name="/usr/lib/connman/scripts/dhclient-script"
[  446.819076] type=1505 audit(1281704154.005:9):  operation="profile_load" pid=858 name="/usr/bin/evince"
[  446.825004] type=1505 audit(1281704154.012:10):  operation="profile_load" pid=858 name="/usr/bin/evince-previewer"
[  446.827983] type=1505 audit(1281704154.012:11):  operation="profile_load" pid=858 name="/usr/bin/evince-thumbnailer"
[  446.876791] type=1505 audit(1281704154.062:12):  operation="profile_load" pid=863 name="/usr/lib/cups/backend/cups-pdf"
[  446.877246] type=1505 audit(1281704154.062:13):  operation="profile_load" pid=863 name="/usr/sbin/cupsd"
[  446.921216] type=1505 audit(1281704154.112:14):  operation="profile_load" pid=865 name="/usr/sbin/mysqld"
[  448.351967] rt61pci 0000:00:0a.0: firmware: requesting rt2561s.bin
[  448.570499] ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  448.576348] eth1: link up, 100Mbps, full-duplex, lpa 0x45E1
[  458.730025] eth1: no IPv6 routers present
[  458.800023] eth0: no IPv6 routers present

```Here is the output from dmseg when I "wait long enough" and get a clean boot:
```

[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 2.6.32-24-generic (buildd@yellow) (gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) ) #39-Ubuntu SMP Wed Jul 28 05:14:15 UTC 2010 (Ubuntu 2.6.32-24.39-generic 2.6.32.15+drm33.5)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-2.6.32-24-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] BIOS-provided physical RAM map:
[    0.000000]  BIOS-e820: 0000000000000000 - 000000000009fc00 (usable)
[    0.000000]  BIOS-e820: 000000000009fc00 - 00000000000a0000 (reserved)
[    0.000000]  BIOS-e820: 00000000000e4000 - 0000000000100000 (reserved)
[    0.000000]  BIOS-e820: 0000000000100000 - 000000007ffd0000 (usable)
[    0.000000]  BIOS-e820: 000000007ffd0000 - 000000007ffde000 (ACPI data)
[    0.000000]  BIOS-e820: 000000007ffde000 - 0000000080000000 (ACPI NVS)
[    0.000000]  BIOS-e820: 00000000fec00000 - 00000000fec01000 (reserved)
[    0.000000]  BIOS-e820: 00000000ff780000 - 0000000100000000 (reserved)
[    0.000000] DMI 2.3 present.
[    0.000000] AMI BIOS detected: BIOS may corrupt low RAM, working around it.
[    0.000000] e820 update range: 0000000000000000 - 0000000000010000 (usable) ==> (reserved)
[    0.000000] last_pfn = 0x7ffd0 max_arch_pfn = 0x400000000
[    0.000000] MTRR default type: uncachable
[    0.000000] MTRR fixed ranges enabled:
[    0.000000]   00000-9FFFF write-back
[    0.000000]   A0000-EFFFF uncachable
[    0.000000]   F0000-FFFFF write-protect
[    0.000000] MTRR variable ranges enabled:
[    0.000000]   0 base 0000000000 mask FF80000000 write-back
[    0.000000]   1 disabled
[    0.000000]   2 disabled
[    0.000000]   3 disabled
[    0.000000]   4 disabled
[    0.000000]   5 disabled
[    0.000000]   6 disabled
[    0.000000]   7 disabled
[    0.000000] x86 PAT enabled: cpu 0, old 0x7040600070406, new 0x7010600070106
[    0.000000] Scanning 0 areas for low memory corruption
[    0.000000] modified physical RAM map:
[    0.000000]  modified: 0000000000000000 - 0000000000010000 (reserved)
[    0.000000]  modified: 0000000000010000 - 000000000009fc00 (usable)
[    0.000000]  modified: 000000000009fc00 - 00000000000a0000 (reserved)
[    0.000000]  modified: 00000000000e4000 - 0000000000100000 (reserved)
[    0.000000]  modified: 0000000000100000 - 000000007ffd0000 (usable)
[    0.000000]  modified: 000000007ffd0000 - 000000007ffde000 (ACPI data)
[    0.000000]  modified: 000000007ffde000 - 0000000080000000 (ACPI NVS)
[    0.000000]  modified: 00000000fec00000 - 00000000fec01000 (reserved)
[    0.000000]  modified: 00000000ff780000 - 0000000100000000 (reserved)
[    0.000000] initial memory mapped : 0 - 20000000
[    0.000000] init_memory_mapping: 0000000000000000-000000007ffd0000
[    0.000000] NX (Execute Disable) protection: active
[    0.000000]  0000000000 - 007fe00000 page 2M
[    0.000000]  007fe00000 - 007ffd0000 page 4k
[    0.000000] kernel direct mapping tables up to 7ffd0000 @ 10000-14000
[    0.000000] RAMDISK: 377fc000 - 37fefb16
[    0.000000] ACPI: RSDP 00000000000f9350 00014 (v00 ACPIAM)
[    0.000000] ACPI: RSDT 000000007ffd0000 00030 (v01 A M I  OEMRSDT  07000526 MSFT 00000097)
[    0.000000] ACPI: FACP 000000007ffd0200 00084 (v02 A M I  OEMFACP  07000526 MSFT 00000097)
[    0.000000] ACPI: DSDT 000000007ffd03f0 03BD4 (v01  1XXXX 1XXXX005 00000005 INTL 02002026)
[    0.000000] ACPI: FACS 000000007ffde000 00040
[    0.000000] ACPI: APIC 000000007ffd0390 00054 (v01 A M I  OEMAPIC  07000526 MSFT 00000097)
[    0.000000] ACPI: OEMB 000000007ffde040 00046 (v01 A M I  AMI_OEM  07000526 MSFT 00000097)
[    0.000000] ACPI: Local APIC address 0xfee00000
[    0.000000] Scanning NUMA topology in Northbridge 24
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at 0000000000000000-000000007ffd0000
[    0.000000] Bootmem setup node 0 0000000000000000-000000007ffd0000
[    0.000000]   NODE_DATA [0000000000012000 - 0000000000016fff]
[    0.000000]   bootmap [0000000000017000 -  0000000000026fff] pages 10
[    0.000000] (7 early reservations) ==> bootmem [0000000000 - 007ffd0000]
[    0.000000]   #0 [0000000000 - 0000001000]   BIOS data page ==> [0000000000 - 0000001000]
[    0.000000]   #1 [0000006000 - 0000008000]       TRAMPOLINE ==> [0000006000 - 0000008000]
[    0.000000]   #2 [0001000000 - 0001a2fe64]    TEXT DATA BSS ==> [0001000000 - 0001a2fe64]
[    0.000000]   #3 [00377fc000 - 0037fefb16]          RAMDISK ==> [00377fc000 - 0037fefb16]
[    0.000000]   #4 [000009fc00 - 0000100000]    BIOS reserved ==> [000009fc00 - 0000100000]
[    0.000000]   #5 [0001a30000 - 0001a30190]              BRK ==> [0001a30000 - 0001a30190]
[    0.000000]   #6 [0000010000 - 0000012000]          PGTABLE ==> [0000010000 - 0000012000]
[    0.000000] found SMP MP-table at [ffff8800000ff780] ff780
[    0.000000]  [ffffea0000000000-ffffea0001bfffff] PMD -> [ffff880002000000-ffff880003bfffff] on node 0
[    0.000000] Zone PFN ranges:
[    0.000000]   DMA      0x00000010 -> 0x00001000
[    0.000000]   DMA32    0x00001000 -> 0x00100000
[    0.000000]   Normal   0x00100000 -> 0x00100000
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[2] active PFN ranges
[    0.000000]     0: 0x00000010 -> 0x0000009f
[    0.000000]     0: 0x00000100 -> 0x0007ffd0
[    0.000000] On node 0 totalpages: 524127
[    0.000000]   DMA zone: 56 pages used for memmap
[    0.000000]   DMA zone: 101 pages reserved
[    0.000000]   DMA zone: 3826 pages, LIFO batch:0
[    0.000000]   DMA32 zone: 7112 pages used for memmap
[    0.000000]   DMA32 zone: 513032 pages, LIFO batch:31
[    0.000000] ACPI: PM-Timer IO Port: 0x808
[    0.000000] ACPI: Local APIC address 0xfee00000
[    0.000000] ACPI: LAPIC (acpi_id[0x01] lapic_id[0x00] enabled)
[    0.000000] ACPI: IOAPIC (id[0x01] address[0xfec00000] gsi_base[0])
[    0.000000] IOAPIC[0]: apic_id 1, version 3, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 low level)
[    0.000000] ACPI: IRQ0 used by override.
[    0.000000] ACPI: IRQ2 used by override.
[    0.000000] ACPI: IRQ9 used by override.
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] SMP: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] nr_irqs_gsi: 24
[    0.000000] PM: Registered nosave memory: 000000000009f000 - 00000000000a0000
[    0.000000] PM: Registered nosave memory: 00000000000a0000 - 00000000000e4000
[    0.000000] PM: Registered nosave memory: 00000000000e4000 - 0000000000100000
[    0.000000] Allocating PCI resources starting at 80000000 (gap: 80000000:7ec00000)
[    0.000000] Booting paravirtualized kernel on bare hardware
[    0.000000] NR_CPUS:64 nr_cpumask_bits:64 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] PERCPU: Embedded 30 pages/cpu @ffff880001c00000 s91544 r8192 d23144 u2097152
[    0.000000] pcpu-alloc: s91544 r8192 d23144 u2097152 alloc=1*2097152
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 516858
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-2.6.32-24-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Initializing CPU#0
[    0.000000] Checking aperture...
[    0.000000] AGP bridge at 00:00:00
[    0.000000] Aperture from AGP @ e0000000 old size 32 MB
[    0.000000] Aperture from AGP @ e0000000 size 256 MB (APSIZE f00)
[    0.000000] Node 0: aperture @ d0000000 size 256 MB
[    0.000000] Memory: 2048972k/2096960k available (5422k kernel code, 452k absent, 47536k reserved, 2979k data, 880k init)
[    0.000000] SLUB: Genslabs=14, HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS:4352 nr_irqs:256
[    0.000000] spurious 8259A interrupt: IRQ7.
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty0] enabled
[    0.000000] allocated 20971520 bytes of page_cgroup
[    0.000000] please try 'cgroup_disable=memory' option if you don't want memory cgroups
[    0.000000] Fast TSC calibration using PIT
[    0.000000] Detected 1600.129 MHz processor.
[    0.010006] Calibrating delay loop (skipped), value calculated using timer frequency.. 3200.25 BogoMIPS (lpj=16001290)
[    0.010040] Security Framework initialized
[    0.010069] AppArmor: AppArmor initialized
[    0.010325] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes)
[    0.012240] Inode-cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.013159] Mount-cache hash table entries: 256
[    0.013352] Initializing cgroup subsys ns
[    0.013358] Initializing cgroup subsys cpuacct
[    0.013363] Initializing cgroup subsys memory
[    0.013376] Initializing cgroup subsys devices
[    0.013379] Initializing cgroup subsys freezer
[    0.013382] Initializing cgroup subsys net_cls
[    0.013407] CPU: L1 I Cache: 64K (64 bytes/line), D cache 64K (64 bytes/line)
[    0.013410] CPU: L2 Cache: 256K (64 bytes/line)
[    0.013413] CPU 0/0x0 -> Node 0
[    0.013416] tseg: 0000000000
[    0.013438] mce: CPU supports 5 MCE banks
[    0.013452] Performance Events: AMD PMU driver.
[    0.013459] ... version:                0
[    0.013461] ... bit width:              48
[    0.013463] ... generic registers:      4
[    0.013465] ... value mask:             0000ffffffffffff
[    0.013468] ... max period:             00007fffffffffff
[    0.013470] ... fixed-purpose events:   0
[    0.013472] ... event mask:             000000000000000f
[    0.013487] SMP alternatives: switching to UP code
[    0.026357] Freeing SMP alternatives: 40k freed
[    0.026394] ACPI: Core revision 20090903
[    0.040009] ftrace: converting mcount calls to 0f 1f 44 00 00
[    0.040017] ftrace: allocating 22527 entries in 89 pages
[    0.050114] Setting APIC routing to flat
[    0.050945] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=0 pin2=0
[    0.152204] CPU0: AMD Sempron(tm) Processor 2800+ stepping 02
[    0.160000] Brought up 1 CPUs
[    0.160000] Total of 1 processors activated (3200.25 BogoMIPS).
[    0.160000] CPU0 attaching NULL sched-domain.
[    0.160000] devtmpfs: initialized
[    0.160000] regulator: core version 0.5
[    0.160000] Time:  4:01:48  Date: 08/14/10
[    0.160000] NET: Registered protocol family 16
[    0.160000] node 0 link 0: io port [1000, ffffff]
[    0.160000] TOM: 0000000080000000 aka 2048M
[    0.160000] node 0 link 0: mmio [a0000, bffff]
[    0.160000] node 0 link 0: mmio [80000000, ffffffff]
[    0.160000] bus: [00,ff] on node 0 link 0
[    0.160000] bus: 00 index 0 io port: [0, ffff]
[    0.160000] bus: 00 index 1 mmio: [a0000, bffff]
[    0.160000] bus: 00 index 2 mmio: [80000000, fcffffffff]
[    0.160000] ACPI: bus type pci registered
[    0.160000] PCI: Using configuration type 1 for base access
[    0.160000] bio: create slab <bio-0> at 0
[    0.160000] ACPI: EC: Look up EC in DSDT
[    0.160000] ACPI: Executed 1 blocks of module-level executable AML code
[    0.162055] ACPI: Interpreter enabled
[    0.162060] ACPI: (supports S0 S1 S4 S5)
[    0.162084] ACPI: Using IOAPIC for interrupt routing
[    0.171452] ACPI Warning: Incorrect checksum in table [OEMB] - 8C, should be 86 (20090903/tbutils-314)
[    0.171594] ACPI: No dock devices found.
[    0.171748] ACPI: PCI Root Bridge [PCI0] (0000:00)
[    0.171819] pci 0000:00:00.0: reg 10 32bit mmio pref: [0xe0000000-0xefffffff]
[    0.172195] pci 0000:00:01.0: supports D1
[    0.172242] pci 0000:00:08.0: reg 10 io port: [0xe800-0xe8ff]
[    0.172250] pci 0000:00:08.0: reg 14 32bit mmio: [0xff6ffc00-0xff6fffff]
[    0.172279] pci 0000:00:08.0: reg 30 32bit mmio pref: [0xff6c0000-0xff6dffff]
[    0.172301] pci 0000:00:08.0: supports D1 D2
[    0.172304] pci 0000:00:08.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.172310] pci 0000:00:08.0: PME# disabled
[    0.172350] pci 0000:00:0a.0: reg 10 32bit mmio: [0xff6f0000-0xff6f7fff]
[    0.172468] pci 0000:00:0f.0: reg 20 io port: [0xfc00-0xfc0f]
[    0.172560] pci 0000:00:10.0: reg 20 io port: [0xec00-0xec1f]
[    0.172594] pci 0000:00:10.0: supports D1 D2
[    0.172596] pci 0000:00:10.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.172601] pci 0000:00:10.0: PME# disabled
[    0.172659] pci 0000:00:10.1: reg 20 io port: [0xe400-0xe41f]
[    0.172690] pci 0000:00:10.1: supports D1 D2
[    0.172693] pci 0000:00:10.1: PME# supported from D0 D1 D2 D3hot D3cold
[    0.172699] pci 0000:00:10.1: PME# disabled
[    0.172759] pci 0000:00:10.2: reg 20 io port: [0xe000-0xe01f]
[    0.172791] pci 0000:00:10.2: supports D1 D2
[    0.172793] pci 0000:00:10.2: PME# supported from D0 D1 D2 D3hot D3cold
[    0.172799] pci 0000:00:10.2: PME# disabled
[    0.172859] pci 0000:00:10.3: reg 20 io port: [0xdc00-0xdc1f]
[    0.172892] pci 0000:00:10.3: supports D1 D2
[    0.172894] pci 0000:00:10.3: PME# supported from D0 D1 D2 D3hot D3cold
[    0.172899] pci 0000:00:10.3: PME# disabled
[    0.172937] pci 0000:00:10.4: reg 10 32bit mmio: [0xff6ff400-0xff6ff4ff]
[    0.172989] pci 0000:00:10.4: supports D1 D2
[    0.172992] pci 0000:00:10.4: PME# supported from D0 D1 D2 D3hot D3cold
[    0.172996] pci 0000:00:10.4: PME# disabled
[    0.173073] HPET not enabled in BIOS. You might try hpet=force boot option
[    0.173136] pci 0000:00:11.5: reg 10 io port: [0xd800-0xd8ff]
[    0.173189] pci 0000:00:11.5: supports D1 D2
[    0.173232] pci 0000:00:12.0: reg 10 io port: [0xd400-0xd4ff]
[    0.173240] pci 0000:00:12.0: reg 14 32bit mmio: [0xff6ff000-0xff6ff0ff]
[    0.173286] pci 0000:00:12.0: supports D1 D2
[    0.173289] pci 0000:00:12.0: PME# supported from D0 D1 D2 D3hot D3cold
[    0.173294] pci 0000:00:12.0: PME# disabled
[    0.173450] pci 0000:01:00.0: reg 10 32bit mmio pref: [0xc0000000-0xcfffffff]
[    0.173457] pci 0000:01:00.0: reg 14 io port: [0xc800-0xc8ff]
[    0.173463] pci 0000:01:00.0: reg 18 32bit mmio: [0xff5f0000-0xff5fffff]
[    0.173485] pci 0000:01:00.0: reg 30 32bit mmio pref: [0xff5c0000-0xff5dffff]
[    0.173513] pci 0000:01:00.0: supports D1 D2
[    0.173545] pci 0000:01:00.1: reg 10 32bit mmio pref: [0xb0000000-0xbfffffff]
[    0.173552] pci 0000:01:00.1: reg 14 32bit mmio: [0xff5e0000-0xff5effff]
[    0.173594] pci 0000:01:00.1: supports D1 D2
[    0.173650] pci 0000:00:01.0: bridge io port: [0xc000-0xcfff]
[    0.173655] pci 0000:00:01.0: bridge 32bit mmio: [0xff500000-0xff5fffff]
[    0.173660] pci 0000:00:01.0: bridge 32bit mmio pref: [0x9eb00000-0xdeafffff]
[    0.173674] ACPI: PCI Interrupt Routing Table [\_SB_.PCI0._PRT]
[    0.190649] ACPI: PCI Interrupt Link [LNKA] (IRQs 3 4 5 6 7 *10 11 12 14 15)
[    0.190776] ACPI: PCI Interrupt Link [LNKB] (IRQs 3 4 *5 6 7 10 11 12 14 15)
[    0.190896] ACPI: PCI Interrupt Link [LNKC] (IRQs 3 4 5 6 7 10 *11 12 14 15)
[    0.191015] ACPI: PCI Interrupt Link [LNKD] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.191135] ACPI: PCI Interrupt Link [LNKE] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.191255] ACPI: PCI Interrupt Link [LNKF] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.191377] ACPI: PCI Interrupt Link [LNKG] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.191497] ACPI: PCI Interrupt Link [LNKH] (IRQs 3 4 5 6 7 10 11 12 14 15) *0, disabled.
[    0.191644] vgaarb: device added: PCI:0000:01:00.0,decodes=io+mem,owns=io+mem,locks=none
[    0.191648] vgaarb: loaded
[    0.191793] SCSI subsystem initialized
[    0.191885] libata version 3.00 loaded.
[    0.191973] usbcore: registered new interface driver usbfs
[    0.191987] usbcore: registered new interface driver hub
[    0.192017] usbcore: registered new device driver usb
[    0.192176] ACPI: WMI: Mapper loaded
[    0.192179] PCI: Using ACPI for IRQ routing
[    0.192189] pci 0000:00:01.0: BAR 15: address space collision on of bridge [0x9eb00000-0xdeafffff]
[    0.192192] pci 0000:00:01.0: BAR 15: can't allocate resource
[    0.192246] pci 0000:01:00.0: BAR 0: no parent found for of device [0xc0000000-0xcfffffff]
[    0.192249] pci 0000:01:00.0: BAR 0: can't allocate resource
[    0.192255] pci 0000:01:00.1: BAR 0: no parent found for of device [0xb0000000-0xbfffffff]
[    0.192258] pci 0000:01:00.1: BAR 0: can't allocate resource
[    0.192411] NetLabel: Initializing
[    0.192414] NetLabel:  domain hash size = 128
[    0.192415] NetLabel:  protocols = UNLABELED CIPSOv4
[    0.192432] NetLabel:  unlabeled traffic allowed by default
[    0.192504] Switching to clocksource tsc
[    0.194707] AppArmor: AppArmor Filesystem Enabled
[    0.194733] pnp: PnP ACPI init
[    0.194757] ACPI: bus type pnp registered
[    0.199247] pnp 00:0d: mem resource (0x0-0x9ffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.199253] pnp 00:0d: mem resource (0xc0000-0xcffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.199257] pnp 00:0d: mem resource (0xe0000-0xfffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.199262] pnp 00:0d: mem resource (0x100000-0x7fffffff) overlaps 0000:01:00.0 BAR 0 (0x0-0xfffffff), disabling
[    0.199268] pnp 00:0d: mem resource (0x0-0x9ffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.199272] pnp 00:0d: mem resource (0xc0000-0xcffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.199277] pnp 00:0d: mem resource (0xe0000-0xfffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.199281] pnp 00:0d: mem resource (0x100000-0x7fffffff) overlaps 0000:01:00.1 BAR 0 (0x0-0xfffffff), disabling
[    0.199658] pnp: PnP ACPI: found 14 devices
[    0.199661] ACPI: ACPI bus type pnp unregistered
[    0.199678] system 00:0a: ioport range 0x680-0x6ff has been reserved
[    0.199682] system 00:0a: ioport range 0x295-0x296 has been reserved
[    0.199690] system 00:0b: ioport range 0x3e0-0x3e7 has been reserved
[    0.199693] system 00:0b: ioport range 0x4d0-0x4d1 has been reserved
[    0.199697] system 00:0b: ioport range 0x800-0x87f has been reserved
[    0.199701] system 00:0b: ioport range 0x400-0x41f has been reserved
[    0.199715] system 00:0c: iomem range 0xfec00000-0xfec00fff could not be reserved
[    0.199719] system 00:0c: iomem range 0xfee00000-0xfee00fff has been reserved
[    0.199727] system 00:0d: iomem range 0xfff80000-0xffffffff has been reserved
[    0.201941] pci 0000:00:01.0: PCI bridge, secondary bus 0000:01
[    0.201945] pci 0000:00:01.0:   IO window: 0xc000-0xcfff
[    0.201951] pci 0000:00:01.0:   MEM window: 0xff500000-0xff5fffff
[    0.201956] pci 0000:00:01.0:   PREFETCH window: 0x80000000-0x9fffffff
[    0.201976] pci 0000:00:01.0: setting latency timer to 64
[    0.201982] pci_bus 0000:00: resource 0 io:  [0x00-0xffff]
[    0.201986] pci_bus 0000:00: resource 1 mem: [0x000000-0xffffffffffffffff]
[    0.201989] pci_bus 0000:01: resource 0 io:  [0xc000-0xcfff]
[    0.201993] pci_bus 0000:01: resource 1 mem: [0xff500000-0xff5fffff]
[    0.201996] pci_bus 0000:01: resource 2 pref mem [0x80000000-0x9fffffff]
[    0.202044] NET: Registered protocol family 2
[    0.202203] IP route cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.203399] TCP established hash table entries: 262144 (order: 10, 4194304 bytes)
[    0.207461] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[    0.208421] TCP: Hash tables configured (established 262144 bind 65536)
[    0.208425] TCP reno registered
[    0.208568] NET: Registered protocol family 1
[    0.208599] pci 0000:00:01.0: disabling DAC on VIA PCI bridge
[    0.208706] pci 0000:01:00.0: Boot video device
[    0.208834] agpgart-amd64 0000:00:00.0: AGP bridge [1106/0282]
[    0.218133] Trying to unpack rootfs image as initramfs...
[    0.227717] agpgart-amd64 0000:00:00.0: AGP aperture is 256M @ 0xd0000000
[    0.227931] Scanning for low memory corruption every 60 seconds
[    0.228090] audit: initializing netlink socket (disabled)
[    0.228105] type=2000 audit(1281758507.227:1): initialized
[    0.257830] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    0.259656] VFS: Disk quotas dquot_6.5.2
[    0.259737] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.260575] fuse init (API version 7.13)
[    0.260682] msgmni has been set to 4001
[    0.260962] alg: No test for stdrng (krng)
[    0.261045] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    0.261049] io scheduler noop registered
[    0.261051] io scheduler anticipatory registered
[    0.261053] io scheduler deadline registered
[    0.261101] io scheduler cfq registered (default)
[    0.267579] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    0.267609] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    0.267736] input: Sleep Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input0
[    0.267746] ACPI: Sleep Button [SLPB]
[    0.267803] input: Power Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1
[    0.267806] ACPI: Power Button [PWRB]
[    0.267854] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input2
[    0.267857] ACPI: Power Button [PWRF]
[    0.268247] processor LNXCPU:00: registered as cooling_device0
[    0.273749] Linux agpgart interface v0.103
[    0.273796] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.273913] serial8250: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    0.274266] 00:07: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    0.275489] brd: module loaded
[    0.276060] loop: module loaded
[    0.276198] input: Macintosh mouse button emulation as /devices/virtual/input/input3
[    0.287705]   alloc irq_desc for 20 on node 0
[    0.287709]   alloc kstat_irqs on node 0
[    0.287721] pata_acpi 0000:00:0f.0: PCI INT A -> GSI 20 (level, low) -> IRQ 20
[    0.287784] pata_acpi 0000:00:0f.0: PCI INT A disabled
[    0.288292] Fixed MDIO Bus: probed
[    0.288342] PPP generic driver version 2.4.2
[    0.288417] tun: Universal TUN/TAP device driver, 1.6
[    0.288419] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    0.288524] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.288605]   alloc irq_desc for 21 on node 0
[    0.288607]   alloc kstat_irqs on node 0
[    0.288615] ehci_hcd 0000:00:10.4: PCI INT C -> GSI 21 (level, low) -> IRQ 21
[    0.288637] ehci_hcd 0000:00:10.4: EHCI Host Controller
[    0.288679] ehci_hcd 0000:00:10.4: new USB bus registered, assigned bus number 1
[    0.288761] ehci_hcd 0000:00:10.4: irq 21, io mem 0xff6ff400
[    0.307649] ehci_hcd 0000:00:10.4: USB 2.0 started, EHCI 1.00
[    0.307803] usb usb1: configuration #1 chosen from 1 choice
[    0.307839] hub 1-0:1.0: USB hub found
[    0.307852] hub 1-0:1.0: 8 ports detected
[    0.307968] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.307988] uhci_hcd: USB Universal Host Controller Interface driver
[    0.317630] uhci_hcd 0000:00:10.0: PCI INT A -> GSI 21 (level, low) -> IRQ 21
[    0.317646] uhci_hcd 0000:00:10.0: UHCI Host Controller
[    0.317735] uhci_hcd 0000:00:10.0: new USB bus registered, assigned bus number 2
[    0.317774] uhci_hcd 0000:00:10.0: irq 21, io base 0x0000ec00
[    0.317921] usb usb2: configuration #1 chosen from 1 choice
[    0.317956] hub 2-0:1.0: USB hub found
[    0.317967] hub 2-0:1.0: 2 ports detected
[    0.318114] uhci_hcd 0000:00:10.1: PCI INT A -> GSI 21 (level, low) -> IRQ 21
[    0.318127] uhci_hcd 0000:00:10.1: UHCI Host Controller
[    0.318187] uhci_hcd 0000:00:10.1: new USB bus registered, assigned bus number 3
[    0.318215] uhci_hcd 0000:00:10.1: irq 21, io base 0x0000e400
[    0.318340] usb usb3: configuration #1 chosen from 1 choice
[    0.318372] hub 3-0:1.0: USB hub found
[    0.318381] hub 3-0:1.0: 2 ports detected
[    0.318495] uhci_hcd 0000:00:10.2: PCI INT B -> GSI 21 (level, low) -> IRQ 21
[    0.318506] uhci_hcd 0000:00:10.2: UHCI Host Controller
[    0.318551] uhci_hcd 0000:00:10.2: new USB bus registered, assigned bus number 4
[    0.318579] uhci_hcd 0000:00:10.2: irq 21, io base 0x0000e000
[    0.318700] usb usb4: configuration #1 chosen from 1 choice
[    0.318735] hub 4-0:1.0: USB hub found
[    0.318744] hub 4-0:1.0: 2 ports detected
[    0.318855] uhci_hcd 0000:00:10.3: PCI INT B -> GSI 21 (level, low) -> IRQ 21
[    0.318863] uhci_hcd 0000:00:10.3: UHCI Host Controller
[    0.318909] uhci_hcd 0000:00:10.3: new USB bus registered, assigned bus number 5
[    0.318937] uhci_hcd 0000:00:10.3: irq 21, io base 0x0000dc00
[    0.319063] usb usb5: configuration #1 chosen from 1 choice
[    0.319096] hub 5-0:1.0: USB hub found
[    0.319107] hub 5-0:1.0: 2 ports detected
[    0.319238] PNP: PS/2 Controller [PNP0303:PS2K,PNP0f03:PS2M] at 0x60,0x64 irq 1,12
[    0.319748] serio: i8042 KBD port at 0x60,0x64 irq 1
[    0.319755] serio: i8042 AUX port at 0x60,0x64 irq 12
[    0.319857] mice: PS/2 mouse device common for all mice
[    0.319996] rtc_cmos 00:02: RTC can wake from S4
[    0.320053] rtc_cmos 00:02: rtc core: registered rtc_cmos as rtc0
[    0.320108] rtc0: alarms up to one year, y3k, 114 bytes nvram
[    0.320301] device-mapper: uevent: version 1.0.3
[    0.320518] device-mapper: ioctl: 4.15.0-ioctl (2009-04-01) initialised: dm-devel@redhat.com
[    0.325038] device-mapper: multipath: version 1.1.0 loaded
[    0.325044] device-mapper: multipath round-robin: version 1.0.0 loaded
[    0.325290] cpuidle: using governor ladder
[    0.325293] cpuidle: using governor menu
[    0.325768] TCP cubic registered
[    0.325956] NET: Registered protocol family 10
[    0.326593] lo: Disabled Privacy Extensions
[    0.327002] NET: Registered protocol family 17
[    0.327048] powernow-k8: Power state transitions not supported
[    0.327184] PM: Resume from disk failed.
[    0.327205] registered taskstats version 1
[    0.327706]   Magic number: 6:446:9
[    0.327713] hub 4-0:1.0: hash matches
[    0.327807] rtc_cmos 00:02: setting system clock to 2010-08-14 04:01:48 UTC (1281758508)
[    0.327811] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    0.327813] EDD information not available.
[    0.348764] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input4
[    0.508164] Freeing initrd memory: 8142k freed
[    0.515455] Freeing unused kernel memory: 880k freed
[    0.516229] Write protecting the kernel read-only data: 7696k
[    0.545215] udev: starting version 151
[    0.761270] Linux Tulip driver version 1.1.15 (Feb 27, 2007)
[    0.836284] pata_via 0000:00:0f.0: version 0.3.4
[    0.836305] pata_via 0000:00:0f.0: PCI INT A -> GSI 20 (level, low) -> IRQ 20
[    0.836591] scsi0 : pata_via
[    0.837051] via-rhine.c:v1.10-LK1.4.3 2007-03-06 Written by Donald Becker
[    0.837083] scsi1 : pata_via
[    0.840201] ata1: PATA max UDMA/133 cmd 0x1f0 ctl 0x3f6 bmdma 0xfc00 irq 14
[    0.840206] ata2: PATA max UDMA/133 cmd 0x170 ctl 0x376 bmdma 0xfc08 irq 15
[    0.840819]   alloc irq_desc for 16 on node 0
[    0.840823]   alloc kstat_irqs on node 0
[    0.840833] tulip 0000:00:08.0: PCI INT A -> GSI 16 (level, low) -> IRQ 16
[    0.841691] tulip0:  MII transceiver #1 config 1000 status 7849 advertising 05e1.
[    0.851057] eth0: ADMtek Comet rev 17 at Port 0xe800, 00:0c:41:1d:bf:19, IRQ 16.
[    0.851364]   alloc irq_desc for 23 on node 0
[    0.851368]   alloc kstat_irqs on node 0
[    0.851378] via-rhine 0000:00:12.0: PCI INT A -> GSI 23 (level, low) -> IRQ 23
[    0.852242] eth1: VIA Rhine II at 0xff6ff000, 00:13:d3:a7:0a:a4, IRQ 23.
[    0.852953] eth1: MII PHY found at address 1, status 0x786d advertising 01e1 Link 45e1.
[    1.038830] ata1.00: ATA-6: WDC WD800JB-00ETA0, 77.07W77, max UDMA/100
[    1.038835] ata1.00: 156301488 sectors, multi 16: LBA48 
[    1.040220] ata1.01: ATA-6: WDC WD2500JB-00GVA0, 08.02D08, max UDMA/100
[    1.040223] ata1.01: 488397168 sectors, multi 16: LBA48 
[    1.040250] ata1.00: limited to UDMA/33 due to 40-wire cable
[    1.040253] ata1.01: limited to UDMA/33 due to 40-wire cable
[    1.078667] ata1.00: configured for UDMA/33
[    1.119006] ata1.01: configured for UDMA/33
[    1.119137] scsi 0:0:0:0: Direct-Access     ATA      WDC WD800JB-00ET 77.0 PQ: 0 ANSI: 5
[    1.119347] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    1.119702] scsi 0:0:1:0: Direct-Access     ATA      WDC WD2500JB-00G 08.0 PQ: 0 ANSI: 5
[    1.119878] sd 0:0:1:0: Attached scsi generic sg1 type 0
[    1.120259] sd 0:0:0:0: [sda] 156301488 512-byte logical blocks: (80.0 GB/74.5 GiB)
[    1.120314] sd 0:0:0:0: [sda] Write Protect is off
[    1.120318] sd 0:0:0:0: [sda] Mode Sense: 00 3a 00 00
[    1.120346] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.120521]  sda: sda1 sda2 < sda5 >
[    1.170269] sd 0:0:0:0: [sda] Attached SCSI disk
[    1.170294] sd 0:0:1:0: [sdb] 488397168 512-byte logical blocks: (250 GB/232 GiB)
[    1.170344] sd 0:0:1:0: [sdb] Write Protect is off
[    1.170347] sd 0:0:1:0: [sdb] Mode Sense: 00 3a 00 00
[    1.170373] sd 0:0:1:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.170548]  sdb:
[    1.189420] sd 0:0:1:0: [sdb] Attached SCSI disk
[    1.320400] ata2.00: ATAPI: LITE-ON DVDRW SOHW-1693S, KS02, max UDMA/66
[    1.321778] ata2.01: ATA-6: WDC WD1200JB-00GVA0, 08.02D08, max UDMA/100
[    1.321782] ata2.01: 234441648 sectors, multi 16: LBA48 
[    1.360285] ata2.00: configured for UDMA/66
[    1.401607] ata2.01: configured for UDMA/100
[    1.402846] scsi 1:0:0:0: CD-ROM            LITE-ON  DVDRW SOHW-1693S KS02 PQ: 0 ANSI: 5
[    1.407229] sr0: scsi3-mmc drive: 48x/48x writer cd/rw xa/form2 cdda tray
[    1.407235] Uniform CD-ROM driver Revision: 3.20
[    1.407584] sr 1:0:0:0: Attached scsi CD-ROM sr0
[    1.407753] sr 1:0:0:0: Attached scsi generic sg2 type 5
[    1.407938] scsi 1:0:1:0: Direct-Access     ATA      WDC WD1200JB-00G 08.0 PQ: 0 ANSI: 5
[    1.408178] sd 1:0:1:0: [sdc] 234441648 512-byte logical blocks: (120 GB/111 GiB)
[    1.408233] sd 1:0:1:0: [sdc] Write Protect is off
[    1.408236] sd 1:0:1:0: [sdc] Mode Sense: 00 3a 00 00
[    1.408264] sd 1:0:1:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.408433]  sdc:
[    1.408695] sd 1:0:1:0: Attached scsi generic sg3 type 0
[    1.424050]  sdc1
[    1.424554] sd 1:0:1:0: [sdc] Attached SCSI disk
[    1.537245] ata2.01: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x6
[    1.537250] ata2.01: BMDMA stat 0x64
[    1.537255] ata2.01: failed command: READ DMA
[    1.537263] ata2.01: cmd c8/00:08:08:01:00/00:00:00:00:00/f0 tag 0 dma 4096 in
[    1.537265]          res 51/84:00:0f:01:00/00:00:00:00:00/f0 Emask 0x10 (ATA bus error)
[    1.537269] ata2.01: status: { DRDY ERR }
[    1.537272] ata2.01: error: { ICRC ABRT }
[    1.537299] ata2: soft resetting link
[    1.767484] EXT4-fs (sda1): mounted filesystem with ordered data mode
[    1.770337] ata2.00: configured for UDMA/66
[    1.812701] ata2.01: configured for UDMA/100
[    1.813168] ata2: EH complete
[    1.823118] ata2.01: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x6
[    1.823123] ata2.01: BMDMA stat 0x64
[    1.823128] ata2.01: failed command: READ DMA
[    1.823136] ata2.01: cmd c8/00:08:08:03:00/00:00:00:00:00/f0 tag 0 dma 4096 in
[    1.823138]          res 51/84:00:0f:03:00/00:00:00:00:00/f0 Emask 0x10 (ATA bus error)
[    1.823141] ata2.01: status: { DRDY ERR }
[    1.823144] ata2.01: error: { ICRC ABRT }
[    1.823173] ata2: soft resetting link
[    2.040305] ata2.00: configured for UDMA/66
[    2.083418] ata2.01: configured for UDMA/100
[    2.083974] ata2: EH complete
[    2.096695] ata2.01: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x6
[    2.096699] ata2.01: BMDMA stat 0x64
[    2.096704] ata2.01: failed command: READ DMA
[    2.096712] ata2.01: cmd c8/00:08:00:02:00/00:00:00:00:00/f0 tag 0 dma 4096 in
[    2.096714]          res 51/84:00:07:02:00/00:00:00:00:00/f0 Emask 0x10 (ATA bus error)
[    2.096718] ata2.01: status: { DRDY ERR }
[    2.096720] ata2.01: error: { ICRC ABRT }
[    2.096784] ata2: soft resetting link
[    2.292303] ata2.00: configured for UDMA/66
[    2.331573] ata2.01: configured for UDMA/100
[    2.332021] ata2: EH complete
[   14.001374] udev: starting version 151
[   14.033190] Adding 3229024k swap on /dev/sda5.  Priority:-1 extents:1 across:3229024k 
[   14.187487] lp: driver loaded but no devices found
[   14.265479] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
[   14.567394] type=1505 audit(1281758522.732:2):  operation="profile_load" pid=501 name="/sbin/dhclient3"
[   14.567748] type=1505 audit(1281758522.732:3):  operation="profile_load" pid=501 name="/usr/lib/NetworkManager/nm-dhcp-client.action"
[   14.567946] type=1505 audit(1281758522.732:4):  operation="profile_load" pid=501 name="/usr/lib/connman/scripts/dhclient-script"
[   14.644792] parport_pc 00:08: reported by Plug and Play ACPI
[   14.644845] parport0: PC-style at 0x378, irq 7 [PCSPP,TRISTATE]
[   14.646218] cfg80211: Calling CRDA to update world regulatory domain
[   14.677369] ACPI: resource vt596_smbus [0x400-0x407] conflicts with ACPI region SMOV [0x400-0x406]
[   14.677374] ACPI: If an ACPI driver is available for this device, you should use it instead of the native driver
[   14.720301] lp0: using parport0 (interrupt-driven).
[   14.727976] cfg80211: World regulatory domain updated:
[   14.727981]  (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[   14.727986]  (2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.727989]  (2457000 KHz - 2482000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[   14.727993]  (2474000 KHz - 2494000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[   14.727996]  (5170000 KHz - 5250000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.728000]  (5735000 KHz - 5835000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   15.043807] gameport: NS558 PnP Gameport is pnp00:09/gameport0, io 0x201, speed 777kHz
[   15.070506] ppdev: user-space parallel port driver
[   15.070994] [drm] Initialized drm 1.1.0 20060810
[   15.099200] EDAC MC: Ver: 2.1.0 Jul 28 2010
[   15.164295] EDAC amd64_edac:  Ver: 3.2.0 Jul 28 2010
[   15.167511] input: PS2++ Logitech Wheel Mouse as /devices/platform/i8042/serio1/input/input5
[   15.170831] EDAC amd64: ECC is enabled by BIOS.
[   15.171350] EDAC MC: Rev E or earlier detected
[   15.172740] EDAC MC0: Giving out device to 'amd64_edac' 'RevF': DEV 0000:00:18.2
[   15.173009] EDAC PCI0: Giving out device to module 'amd64_edac' controller 'EDAC PCI controller': DEV '0000:00:18.2' (POLLED)
[   15.272393]   alloc irq_desc for 18 on node 0
[   15.272399]   alloc kstat_irqs on node 0
[   15.272411] rt61pci 0000:00:0a.0: PCI INT A -> GSI 18 (level, low) -> IRQ 18
[   15.325206] [drm] radeon defaulting to kernel modesetting.
[   15.325212] [drm] radeon kernel modesetting enabled.
[   15.331165] radeon 0000:01:00.0: PCI INT A -> GSI 16 (level, low) -> IRQ 16
[   15.349435] [drm] radeon: Initializing kernel modesetting.
[   15.354289] [drm] register mmio base: 0xFF5F0000
[   15.354293] [drm] register mmio size: 65536
[   15.355220] [drm] GPU reset succeed (RBBM_STATUS=0x00000140)
[   15.355520] [drm] Generation 2 PCI interface, using max accessible memory
[   15.355533] agpgart-amd64 0000:00:00.0: AGP 3.0 bridge
[   15.355554] agpgart-amd64 0000:00:00.0: putting AGP V3 device into 8x mode
[   15.355797] radeon 0000:01:00.0: putting AGP V3 device into 8x mode
[   15.355807] [drm] radeon: VRAM 256M
[   15.355809] [drm] radeon: VRAM from 0x00000000 to 0x0FFFFFFF
[   15.355812] [drm] radeon: GTT 256M
[   15.355814] [drm] radeon: GTT from 0xD0000000 to 0xDFFFFFFF
[   15.355867] [drm] radeon: irq initialized.
[   15.356226] [drm] Detected VRAM RAM=256M, BAR=256M
[   15.356231] [drm] RAM width 128bits DDR
[   15.360100] [TTM] Zone  kernel: Available graphics memory: 1029020 kiB.
[   15.360126] [drm] radeon: 256M of VRAM memory ready
[   15.360129] [drm] radeon: 256M of GTT memory ready.
[   15.360379] [drm] radeon: 1 quad pipes, 1 Z pipes initialized.
[   15.360392] [drm] radeon: cp idle (0x10000C03)
[   15.360515] [drm] Loading R300 Microcode
[   15.360944] platform radeon_cp.0: firmware: requesting radeon/R300_cp.bin
[   15.391907] phy0: Selected rate control algorithm 'minstrel'
[   15.392800] Registered led device: rt61pci-phy0::radio
[   15.392818] Registered led device: rt61pci-phy0::assoc
[   15.398579] [drm] radeon: ring at 0x00000000D0000000
[   15.398604] [drm] ring test succeeded in 1 usecs
[   15.417000] [drm] radeon: ib pool ready.
[   15.417108] [drm] ib test succeeded in 0 usecs
[   15.418360] [drm] Default TV standard: NTSC
[   15.418365] [drm] 27.000000000 MHz TV ref clk
[   15.418369] [drm] DFP table revision: 4
[   15.419622] [drm] Default TV standard: NTSC
[   15.419626] [drm] 27.000000000 MHz TV ref clk
[   15.419767] [drm] Radeon Display Connectors
[   15.419769] [drm] Connector 0:
[   15.419771] [drm]   VGA
[   15.419775] [drm]   DDC: 0x60 0x60 0x60 0x60 0x60 0x60 0x60 0x60
[   15.419777] [drm]   Encoders:
[   15.419779] [drm]     CRT1: INTERNAL_DAC1
[   15.419781] [drm] Connector 1:
[   15.419782] [drm]   DVI-I
[   15.419784] [drm]   HPD1
[   15.419786] [drm]   DDC: 0x64 0x64 0x64 0x64 0x64 0x64 0x64 0x64
[   15.419788] [drm]   Encoders:
[   15.419790] [drm]     CRT2: INTERNAL_DAC2
[   15.419792] [drm]     DFP1: INTERNAL_TMDS1
[   15.419794] [drm] Connector 2:
[   15.419796] [drm]   S-video
[   15.419797] [drm]   Encoders:
[   15.419799] [drm]     TV1: INTERNAL_DAC2
[   15.543811] ata2.01: limiting speed to UDMA/66:PIO4
[   15.543818] ata2.01: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x6
[   15.543883] ata2.01: BMDMA stat 0x64
[   15.543943] ata2.01: failed command: READ DMA
[   15.544008] ata2.01: cmd c8/00:80:a7:01:60/00:00:00:00:00/f0 tag 0 dma 65536 in
[   15.544010]          res 51/84:00:26:02:60/00:00:00:00:00/f0 Emask 0x10 (ATA bus error)
[   15.544131] ata2.01: status: { DRDY ERR }
[   15.544188] ata2.01: error: { ICRC ABRT }
[   15.544272] ata2: soft resetting link
[   15.621118]   alloc irq_desc for 22 on node 0
[   15.621122]   alloc kstat_irqs on node 0
[   15.621132] VIA 82xx Audio 0000:00:11.5: PCI INT C -> GSI 22 (level, low) -> IRQ 22
[   15.621301] VIA 82xx Audio 0000:00:11.5: setting latency timer to 64
[   15.787373] [drm] fb mappable at 0x80040000
[   15.787377] [drm] vram apper at 0x80000000
[   15.787379] [drm] size 5242880
[   15.787381] [drm] fb depth is 24
[   15.787383] [drm]    pitch is 5120
[   15.788387] fb0: radeondrmfb frame buffer device
[   15.788391] registered panic notifier
[   15.788399] [drm] Initialized radeon 2.0.0 20080528 for 0000:01:00.0 on minor 0
[   15.795226] vga16fb: initializing
[   15.795239] vga16fb: mapped to 0xffff8800000a0000
[   15.795246] vga16fb: not registering due to another framebuffer present
[   15.830347] ata2.00: configured for UDMA/66
[   15.969659] Console: switching to colour frame buffer device 160x64
[   16.048543] ata2.01: configured for UDMA/66
[   16.050815] ata2: EH complete
[   17.624132] type=1505 audit(1281758525.792:5):  operation="profile_load" pid=810 name="/usr/share/gdm/guest-session/Xsession"
[   17.626428] type=1505 audit(1281758525.792:6):  operation="profile_replace" pid=814 name="/sbin/dhclient3"
[   17.626795] type=1505 audit(1281758525.792:7):  operation="profile_replace" pid=814 name="/usr/lib/NetworkManager/nm-dhcp-client.action"
[   17.627002] type=1505 audit(1281758525.792:8):  operation="profile_replace" pid=814 name="/usr/lib/connman/scripts/dhclient-script"
[   17.847511] type=1505 audit(1281758526.012:9):  operation="profile_load" pid=815 name="/usr/bin/evince"
[   17.852468] type=1505 audit(1281758526.022:10):  operation="profile_load" pid=815 name="/usr/bin/evince-previewer"
[   17.855426] type=1505 audit(1281758526.022:11):  operation="profile_load" pid=815 name="/usr/bin/evince-thumbnailer"
[   19.162985] rt61pci 0000:00:0a.0: firmware: requesting rt2561s.bin
[   19.260631] ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   19.266705] eth1: link up, 100Mbps, full-duplex, lpa 0x45E1
[   19.601975] __ratelimit: 15 callbacks suppressed
[   19.601979] type=1505 audit(1281758527.772:17):  operation="profile_replace" pid=955 name="/usr/sbin/mysqld"
[   29.620026] eth1: no IPv6 routers present
[   29.700027] eth0: no IPv6 routers present

```Here is the kernel command line from a boot that gives me errors:
```

BOOT_IMAGE=/boot/vmlinuz-2.6.32-24-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash

```Here is the kernel modules from a boot that gives me errors:
```

binfmt_misc 7960 1 - Live 0xffffffffa002c000
fbcon 39270 71 - Live 0xffffffffa0342000
tileblit 2487 1 fbcon, Live 0xffffffffa033c000
font 8053 1 fbcon, Live 0xffffffffa0335000
bitblit 5811 1 fbcon, Live 0xffffffffa032e000
softcursor 1565 1 bitblit, Live 0xffffffffa0328000
vga16fb 12757 0 - Live 0xffffffffa031e000
vgastate 9857 1 vga16fb, Live 0xffffffffa0316000
snd_via82xx 24004 2 - Live 0xffffffffa0309000
snd_ac97_codec 125394 1 snd_via82xx, Live 0xffffffffa02df000
ac97_bus 1450 1 snd_ac97_codec, Live 0xffffffffa02d9000
snd_pcm_oss 41394 0 - Live 0xffffffffa02c7000
snd_mixer_oss 16299 1 snd_pcm_oss, Live 0xffffffffa02bd000
snd_pcm 87882 4 snd_via82xx,snd_ac97_codec,snd_pcm_oss, Live 0xffffffffa029b000
snd_page_alloc 8500 2 snd_via82xx,snd_pcm, Live 0xffffffffa0292000
snd_mpu401_uart 6857 1 snd_via82xx, Live 0xffffffffa01a1000
snd_seq_dummy 1782 0 - Live 0xffffffffa00a1000
snd_seq_oss 31219 0 - Live 0xffffffffa01b8000
snd_seq_midi 5829 0 - Live 0xffffffffa0099000
snd_rawmidi 23420 2 snd_mpu401_uart,snd_seq_midi, Live 0xffffffffa0183000
snd_seq_midi_event 7267 2 snd_seq_oss,snd_seq_midi, Live 0xffffffffa018a000
arc4 1473 2 - Live 0xffffffffa00a9000
snd_seq 57481 6 snd_seq_dummy,snd_seq_oss,snd_seq_midi,snd_seq_midi_event, Live 0xffffffffa015d000
radeon 740390 2 - Live 0xffffffffa01c1000
rt61pci 21414 0 - Live 0xffffffffa0120000
crc_itu_t 1715 1 rt61pci, Live 0xffffffffa005a000
snd_timer 23649 2 snd_pcm,snd_seq, Live 0xffffffffa00ba000
snd_seq_device 6888 5 snd_seq_dummy,snd_seq_oss,snd_seq_midi,snd_rawmidi,snd_seq, Live 0xffffffffa0089000
rt2x00pci 6905 1 rt61pci, Live 0xffffffffa0021000
ttm 60847 1 radeon, Live 0xffffffffa01a7000
rt2x00lib 32133 2 rt61pci,rt2x00pci, Live 0xffffffffa0197000
drm_kms_helper 30742 1 radeon, Live 0xffffffffa018d000
led_class 3764 1 rt2x00lib, Live 0xffffffffa0057000
ppdev 6375 0 - Live 0xffffffffa0018000
snd 71106 14 snd_via82xx,snd_ac97_codec,snd_pcm_oss,snd_mixer_oss,snd_pcm,snd_mpu401_uart,snd_seq_oss,snd_rawmidi,snd_seq,snd_timer,snd_seq_device, Live 0xffffffffa016f000
amd64_edac_mod 20456 0 - Live 0xffffffffa008c000
ns558 3704 0 - Live 0xffffffffa001b000
drm 199204 3 radeon,ttm,drm_kms_helper, Live 0xffffffffa012a000
i2c_algo_bit 6024 1 radeon, Live 0xffffffffa005f000
mac80211 238448 2 rt2x00pci,rt2x00lib, Live 0xffffffffa00de000
psmouse 64576 0 - Live 0xffffffffa00cc000
serio_raw 4918 0 - Live 0xffffffffa0048000
gameport 10966 3 snd_via82xx,ns558, Live 0xffffffffa003d000
parport_pc 29958 1 - Live 0xffffffffa00c2000
k8temp 3912 0 - Live 0xffffffffa0005000
edac_core 45423 3 amd64_edac_mod, Live 0xffffffffa00ac000
edac_mce_amd 9278 1 amd64_edac_mod, Live 0xffffffffa00a4000
i2c_viapro 6537 0 - Live 0xffffffffa009d000
soundcore 8052 1 snd, Live 0xffffffffa0095000
cfg80211 148546 2 rt2x00lib,mac80211, Live 0xffffffffa0062000
eeprom_93cx6 1765 1 rt61pci, Live 0xffffffffa005c000
shpchp 33711 0 - Live 0xffffffffa004c000
lp 9336 0 - Live 0xffffffffa0043000
parport 37160 3 ppdev,parport_pc,lp, Live 0xffffffffa0031000
via_rhine 22496 0 - Live 0xffffffffa0024000
mii 5237 1 via_rhine, Live 0xffffffffa001d000
tulip 50592 0 - Live 0xffffffffa0009000
pata_via 9072 3 - Live 0xffffffffa0000000

```Here is the modules list from a good boot:
```

binfmt_misc 7960 1 - Live 0xffffffffa0057000
fbcon 39270 71 - Live 0xffffffffa0345000
tileblit 2487 1 fbcon, Live 0xffffffffa033f000
font 8053 1 fbcon, Live 0xffffffffa0338000
bitblit 5811 1 fbcon, Live 0xffffffffa02d8000
softcursor 1565 1 bitblit, Live 0xffffffffa01d1000
vga16fb 12757 0 - Live 0xffffffffa032f000
vgastate 9857 1 vga16fb, Live 0xffffffffa01c2000
snd_via82xx 24004 1 - Live 0xffffffffa02c7000
snd_ac97_codec 125394 1 snd_via82xx, Live 0xffffffffa030e000
ac97_bus 1450 1 snd_ac97_codec, Live 0xffffffffa00bc000
snd_pcm_oss 41394 0 - Live 0xffffffffa0301000
snd_mixer_oss 16299 1 snd_pcm_oss, Live 0xffffffffa014f000
snd_pcm 87882 3 snd_via82xx,snd_ac97_codec,snd_pcm_oss, Live 0xffffffffa02e9000
snd_page_alloc 8500 2 snd_via82xx,snd_pcm, Live 0xffffffffa010d000
snd_mpu401_uart 6857 1 snd_via82xx, Live 0xffffffffa00b8000
snd_seq_dummy 1782 0 - Live 0xffffffffa008d000
snd_seq_oss 31219 0 - Live 0xffffffffa0103000
snd_seq_midi 5829 0 - Live 0xffffffffa0040000
snd_rawmidi 23420 2 snd_mpu401_uart,snd_seq_midi, Live 0xffffffffa02dc000
snd_seq_midi_event 7267 2 snd_seq_oss,snd_seq_midi, Live 0xffffffffa02d4000
arc4 1473 2 - Live 0xffffffffa02ce000
snd_seq 57481 6 snd_seq_dummy,snd_seq_oss,snd_seq_midi,snd_seq_midi_event, Live 0xffffffffa02b6000
radeon 740390 2 - Live 0xffffffffa01e5000
rt61pci 21414 0 - Live 0xffffffffa01d9000
crc_itu_t 1715 1 rt61pci, Live 0xffffffffa01d3000
snd_timer 23649 2 snd_pcm,snd_seq, Live 0xffffffffa01c6000
snd_seq_device 6888 5 snd_seq_dummy,snd_seq_oss,snd_seq_midi,snd_rawmidi,snd_seq, Live 0xffffffffa01be000
rt2x00pci 6905 1 rt61pci, Live 0xffffffffa00a3000
ttm 60847 1 radeon, Live 0xffffffffa01a4000
rt2x00lib 32133 2 rt61pci,rt2x00pci, Live 0xffffffffa0194000
amd64_edac_mod 20456 0 - Live 0xffffffffa018d000
drm_kms_helper 30742 1 radeon, Live 0xffffffffa0183000
led_class 3764 1 rt2x00lib, Live 0xffffffffa002c000
snd 71106 13 snd_via82xx,snd_ac97_codec,snd_pcm_oss,snd_mixer_oss,snd_pcm,snd_mpu401_uart,snd_seq_oss,snd_rawmidi,snd_seq,snd_timer,snd_seq_device, Live 0xffffffffa0165000
edac_core 45423 3 amd64_edac_mod, Live 0xffffffffa0157000
ppdev 6375 0 - Live 0xffffffffa0018000
drm 199204 3 radeon,ttm,drm_kms_helper, Live 0xffffffffa0112000
i2c_algo_bit 6024 1 radeon, Live 0xffffffffa0089000
ns558 3704 0 - Live 0xffffffffa003d000
mac80211 238448 2 rt2x00pci,rt2x00lib, Live 0xffffffffa00c6000
k8temp 3912 0 - Live 0xffffffffa0048000
edac_mce_amd 9278 1 amd64_edac_mod, Live 0xffffffffa00be000
psmouse 64576 0 - Live 0xffffffffa00a6000
serio_raw 4918 0 - Live 0xffffffffa009f000
i2c_viapro 6537 0 - Live 0xffffffffa005f000
soundcore 8052 1 snd, Live 0xffffffffa0021000
parport_pc 29958 1 - Live 0xffffffffa0095000
gameport 10966 3 snd_via82xx,ns558, Live 0xffffffffa0005000
cfg80211 148546 2 rt2x00lib,mac80211, Live 0xffffffffa0062000
eeprom_93cx6 1765 1 rt61pci, Live 0xffffffffa005c000
shpchp 33711 0 - Live 0xffffffffa004c000
lp 9336 0 - Live 0xffffffffa0043000
parport 37160 3 ppdev,parport_pc,lp, Live 0xffffffffa0031000
via_rhine 22496 0 - Live 0xffffffffa0024000
mii 5237 1 via_rhine, Live 0xffffffffa001d000
tulip 50592 0 - Live 0xffffffffa0009000
pata_via 9072 5 - Live 0xffffffffa0000000

```Here is my fstab, which hasn't changed since I first installed Ubuntu weeks ago:
```

proc /proc proc defaults 0 0
# Entry for /dev/sda1 :
UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be / ext4 errors=remount-ro 0 1
# Entry for /dev/sda5 :
UUID=c2f898b6-9b33-40b8-a92b-19a4b6c3ea9e none swap sw 0 0
/dev/scd0 /media/cdrom0 udf,iso9660 user,noauto,exec,utf8 0 0
/dev/sdb /mnt/samba_d ext2 defaults 1 2
/dev/sdc1 /mnt/samba_d/backup ntfs-3g rw,umask=0000,defaults 1 2

```Here is my menu.lst, which I have edited trying various fixes:
```

# menu.lst - See: grub(8), info grub, update-grub(8)
#            grub-install(8), grub-floppy(8),
#            grub-md5-crypt, /usr/share/doc/grub
#            and /usr/share/doc/grub-legacy-doc/.

## default num
# Set the default entry to the entry number NUM. Numbering starts from 0, and
# the entry number 0 is the default if the command is not used.
#
# You can specify 'saved' instead of a number. In this case, the default entry
# is the entry saved with the command 'savedefault'.
# WARNING: If you are using dmraid do not use 'savedefault' or your
# array will desync and will not let you boot your system.
default         0

## timeout sec
# Set a timeout, in SEC seconds, before automatically booting the default entry
# (normally the first entry defined).
timeout         10

## hiddenmenu
# Hides the menu by default (press ESC to see the menu)
# hiddenmenu

# Pretty colours
#color cyan/blue white/blue

## password ['--md5'] passwd
# If used in the first section of a menu file, disable all interactive editing
# control (menu entry editor and command-line)  and entries protected by the
# command 'lock'
# e.g. password topsecret
#      password --md5 $1$gLhU0/$aW78kHK1QfV3P2b2znUoe/
# password topsecret

#
# examples
#
# title         Windows 95/98/NT/2000
# root          (hd0,0)
# makeactive
# chainloader   +1
#
# title         Linux
# root          (hd0,1)
# kernel        /vmlinuz root=/dev/hda2 ro
#

#
# Put static boot stanzas before and/or after AUTOMAGIC KERNEL LIST

### BEGIN AUTOMAGIC KERNELS LIST
## lines between the AUTOMAGIC KERNELS LIST markers will be modified
## by the debian update-grub script except for the default options below

## DO NOT UNCOMMENT THEM, Just edit them to your needs

## ## Start Default Options ##
## default kernel options
## default kernel options for automagic boot options
## If you want special options for specific kernels use kopt_x_y_z
## where x.y.z is kernel version. Minor versions can be omitted.
## e.g. kopt=root=/dev/hda1 ro
##      kopt_2_6_8=root=/dev/hdc1 ro
##      kopt_2_6_8_2_686=root=/dev/hdc2 ro
# kopt=root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro

## default grub root device
## e.g. groot=(hd0,0)
# groot=b4960f77-5e6b-462d-a2e5-51a9573db3be

## should update-grub create alternative automagic boot options
## e.g. alternative=true
##      alternative=false
# alternative=true

## should update-grub lock alternative automagic boot options
## e.g. lockalternative=true
##      lockalternative=false
# lockalternative=false

## additional options to use with the default boot option, but not with the
## alternatives
## e.g. defoptions=vga=791 resume=/dev/hda5
# defoptions=quiet splash

## should update-grub lock old automagic boot options
## e.g. lockold=false
##      lockold=true
# lockold=false

## Xen hypervisor options to use with the default Xen boot option
# xenhopt=

## Xen Linux kernel options to use with the default Xen boot option
# xenkopt=console=tty0

## altoption boot targets option
## multiple altoptions lines are allowed
## e.g. altoptions=(extra menu suffix) extra boot options
##      altoptions=(recovery) single
# altoptions=(recovery mode) single

## controls how many kernels should be put into the menu.lst
## only counts the first occurence of a kernel, not the
## alternative kernel options
## e.g. howmany=all
##      howmany=7
# howmany=all

## specify if running in Xen domU or have grub detect automatically
## update-grub will ignore non-xen kernels when running in domU and vice versa
## e.g. indomU=detect
##      indomU=true
##      indomU=false
# indomU=detect

## should update-grub create memtest86 boot option
## e.g. memtest86=true
##      memtest86=false
# memtest86=true

## should update-grub adjust the value of the default booted system
## can be true or false
# updatedefaultentry=false

## should update-grub add savedefault to the default options
## can be true or false
# savedefault=false

## ## End Default Options ##

title           Ubuntu 10.04.1 LTS, kernel 2.6.32-24-generic
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.32-24-generic root=/dev/sda1 ro quiet splash rootdelay=90
initrd          /boot/initrd.img-2.6.32-24-generic

title           Ubuntu 10.04.1 LTS, kernel 2.6.32-24-generic (recovery mode)
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.32-24-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro  single
initrd          /boot/initrd.img-2.6.32-24-generic

title           Ubuntu 10.04.1 LTS, kernel 2.6.32-23-generic
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.32-23-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash 
initrd          /boot/initrd.img-2.6.32-23-generic

title           Ubuntu 10.04.1 LTS, kernel 2.6.32-23-generic (recovery mode)
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.32-23-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro  single
initrd          /boot/initrd.img-2.6.32-23-generic

title           Ubuntu 10.04.1 LTS, kernel 2.6.32-22-generic
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.32-22-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash 
initrd          /boot/initrd.img-2.6.32-22-generic

title           Ubuntu 10.04.1 LTS, kernel 2.6.32-22-generic (recovery mode)
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.32-22-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro  single
initrd          /boot/initrd.img-2.6.32-22-generic

title           Ubuntu 10.04.1 LTS, kernel 2.6.31-20-generic
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.31-20-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro quiet splash 
initrd          /boot/initrd.img-2.6.31-20-generic

title           Ubuntu 10.04.1 LTS, kernel 2.6.31-20-generic (recovery mode)
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/vmlinuz-2.6.31-20-generic root=UUID=b4960f77-5e6b-462d-a2e5-51a9573db3be ro  single
initrd          /boot/initrd.img-2.6.31-20-generic

title           Chainload into GRUB 2
root            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/grub/core.img

title           Ubuntu 10.04.1 LTS, memtest86+
uuid            b4960f77-5e6b-462d-a2e5-51a9573db3be
kernel          /boot/memtest86+.bin

### END DEBIAN AUTOMAGIC KERNELS LIST

```I cannot think of anything else to add to this post other than: I am thorougly confused. I have never ran into this issue in all my years of running Linux, even on old RH 5.3 systems.

That being said, is this just a case of needing to add more delay to the kernel command line? If so, does anyone have any idea how long I would need to make it wait to fully detect all the hardware?

Many thanks,

Vadtec

---

### Post by Vadtec on 2010-08-17
Guess this isn't a big issue for anyone other than my self. How quaint.

---

### Post by Guerreiro on 2010-08-17
Well don't be sad, I am still figuring out how to boot from my external HDD. ;)

---

### Post by Vadtec on 2010-08-17
Oh I'm not sad, far from. I just find it rather dismal that the Ubuntu community doesn't have hordes of people who can post concrete responses to my issue. Luckily, I've found other ways around it. I guess it's a good thing I'm versed in more than just Ubuntu. I'd hate to be someone who has only ever used Ubuntu and be stuck with this issue.

---

### Post by dwbsr on 2010-08-17
> **Vadtec said:**
> 

I noticed that if I go into the BIOS and sit for a while then exit the BIOS, Ubuntu loads just fine. I don't know how long I have to sit there before Ubuntu will fully load just fine, so this confuses me.

Many thanks,

Vadtec

It sounds like the BIOS is losing it's memory (bad battery on the motherboard) then when you sit at the BIOS screen the battery has enough left in it to hold your session. I would check that first.

---

