---
title: "11.10: GRUB Legacy: old reference makes ubuntu freeze during boot"
date: 2012-01-03
forum: Installation &amp; Upgrades
---

### Post by pJansson on 2012-01-03
Pew! I'm not sure where to start on this problem...

A couple of months back i deleted my windows partition (sda1) due to a nasty virus (typical fate of an Win isntallation, isn't it). I then got myself a new HD and installed windows on a different physical HD. After a lot of help i got grub to detect the two disks, but there was still some reference to sda1 left: Every time i booted ubuntu there was a message during the ubuntu loading screen that "sda1 is unavailable or missing" and then options "S" for skip search or "M" for manual recovery.

Now to the issue...

I have now upgraded from 10.04 to 11.10 and when the "sda1 missing" message appears and I press "s", nothing happens: The dots under the "ubuntu" screen fills up and then stops loading. All i can do is hit the power switch.

Due to an issue with an new graphics card, i cannot access failsafeX via recoverymode. But i do however get an command-line via recoverymode as root. So here's what i need help with:

**Can someone please post the code for removing the old reference?**

I got a tip while back that it's probably a reference in /etc/fstab but i'm not good with the terminal... I'm pretty sure that the bootloader is grub legacy and the distro is of course 11.10

Anyone? Help would be much appreciated...

---

### Post by oldfred on 2012-01-03
It probably is fstab has an old entry. Or with drive order changed, you may have something mounting by device(/dev/sda) rather than UUID.

Post this and we can give specific suggestions.

Boot Info Script courtesy of forum members meierfra & Gert Hulselmans
Page with instructions and download:
[http://bootinfoscript.sourceforge.net/](http://bootinfoscript.sourceforge.net/)
Paste contents of results.txt in a New Reply, then highlight entire file and click on # in edit panel(code tags) to make it easier to read.
Or You can generate the tags first by pressing the # icon in the New Reply Edit toolbar and then paste the contents between the generated [ code] paste here [ /code] tags.
V60 has improved formating and requires code tags to make it legible. New Version is a zip file that you have to extract to get .sh to run.
Install these before running script:
sudo apt-get install gawk
sudo apt-get install xz-utils

---

### Post by pJansson on 2012-01-04
Well, it took me really long to get this, bur finally i managed to run the boot script. Here are the results:

```
                  Boot Info Script 0.60    from 17 May 2011


============================= Boot Info Summary: ===============================

 => Grub Legacy (v0.97) is installed in the MBR of /dev/sda and looks on the 
    same drive in partition #6 for /boot/grub/stage2 and /boot/grub/menu.lst.
 => Windows is installed in the MBR of /dev/sdb.
 => Syslinux MBR (4.04 and higher) is installed in the MBR of /dev/sdc.
 => No boot loader is installed in the MBR of /dev/sdd.

sda2: __________________________________________________________________________

    File system:       Extended Partition
    Boot sector type:  -
    Boot sector info:  

sda5: __________________________________________________________________________

    File system:       swap
    Boot sector type:  -
    Boot sector info:  

sda6: __________________________________________________________________________

    File system:       ext3
    Boot sector type:  Grub Legacy
    Boot sector info:   Grub Legacy (v0.97) is installed in the boot sector 
                       of sda6 and looks at sector 276572541 of the same hard 
                       drive for the stage2 file.  A stage2 file is at this 
                       location on /dev/sda.  Stage2 looks on partition #6 
                       for /boot/grub/menu.lst.
    Operating System:  Ubuntu 11.10
    Boot files:        /boot/grub/menu.lst /etc/fstab

sdb1: __________________________________________________________________________

    File system:       ntfs
    Boot sector type:  Windows XP
    Boot sector info:   No errors found in the Boot Parameter Block.
    Operating System:  Windows XP
    Boot files:        /boot.ini /ntldr /NTDETECT.COM

sdc1: __________________________________________________________________________

    File system:       vfat
    Boot sector type:  SYSLINUX 4.05 2011-12-09
    Boot sector info:   Syslinux looks at sector 252948 of /dev/sdc1 for its 
                       second stage. SYSLINUX is installed in the  directory. 
                       No errors found in the Boot Parameter Block.
    Operating System:  
    Boot files:        /boot/grub/grub.cfg /syslinux/syslinux.cfg /ldlinux.sys

sdd1: __________________________________________________________________________

    File system:       vfat
    Boot sector type:  -
    Boot sector info:   No errors found in the Boot Parameter Block.
    Operating System:  
    Boot files:        

============================ Drive/Partition Info: =============================

Drive: sda _____________________________________________________________________

Disk /dev/sda: 500.1 GB, 500107862016 bytes
255 heads, 63 sectors/track, 60801 cylinders, total 976773168 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes

Partition  Boot  Start Sector    End Sector  # of Sectors  Id System

/dev/sda2          97,659,135   976,768,064   879,108,930   5 Extended
/dev/sda5         953,040,123   976,768,064    23,727,942  82 Linux swap / Solaris
/dev/sda6    *     97,659,261   953,040,059   855,380,799  83 Linux


Drive: sdb _____________________________________________________________________

Disk /dev/sdb: 250.1 GB, 250059350016 bytes
255 heads, 63 sectors/track, 30401 cylinders, total 488397168 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes

Partition  Boot  Start Sector    End Sector  # of Sectors  Id System

/dev/sdb1    *             63   488,375,999   488,375,937   7 NTFS / exFAT / HPFS


Drive: sdc _____________________________________________________________________

Disk /dev/sdc: 8036 MB, 8036285952 bytes
255 heads, 63 sectors/track, 977 cylinders, total 15695871 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes

Partition  Boot  Start Sector    End Sector  # of Sectors  Id System

/dev/sdc1    *             44    15,679,439    15,679,396   b W95 FAT32


Drive: sdd _____________________________________________________________________

Disk /dev/sdd: 16.0 GB, 16008609792 bytes
255 heads, 63 sectors/track, 1946 cylinders, total 31266816 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes

Partition  Boot  Start Sector    End Sector  # of Sectors  Id System

/dev/sdd1                  32    31,266,815    31,266,784   c W95 FAT32 (LBA)


"blkid" output: ________________________________________________________________

Device           UUID                                   TYPE       LABEL

/dev/loop0                                              squashfs   
/dev/sda5        02cf9ea0-9a30-45ab-9627-738f12b37a45   swap       
/dev/sda6        eb553431-533f-4896-b8ab-4e2b8902688d   ext3       
/dev/sdb1        CCC83C9BC83C862C                       ntfs       
/dev/sdc1        481F-C14C                              vfat       PENDRIVE
/dev/sdd1        209B-4516                              vfat       

================================ Mount points: =================================

Device           Mount_Point              Type       Options

/dev/loop0       /rofs                    squashfs   (ro,noatime)
/dev/sda6        /media/eb553431-533f-4896-b8ab-4e2b8902688d ext3       (rw,nosuid,nodev,uhelper=udisks)
/dev/sdc1        /cdrom                   vfat       (rw,relatime,fmask=0022,dmask=0022,codepage=cp437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/sdd1        /media/209B-4516         vfat       (rw,nosuid,nodev,uid=999,gid=999,shortname=mixed,dmask=0077,utf8=1,showexec,flush,uhelper=udisks)
/dev/sr1         /media/U3 System         iso9660    (ro,nosuid,nodev,uid=999,gid=999,iocharset=utf8,mode=0400,dmode=0500,uhelper=udisks)


=========================== sda6/boot/grub/menu.lst: ===========================

--------------------------------------------------------------------------------
# menu.lst - See: grub(8), info grub, update-grub(8)
#            grub-install(8), grub-floppy(8),
#            grub-md5-crypt, /usr/share/doc/grub
#            and /usr/share/doc/grub-doc/.

## default num
# Set the default entry to the entry number NUM. Numbering starts from 0, and
# the entry number 0 is the default if the command is not used.
#
# You can specify 'saved' instead of a number. In this case, the default entry
# is the entry saved with the command 'savedefault'.
# WARNING: If you are using dmraid do not use 'savedefault' or your
# array will desync and will not let you boot your system.
default		0

## timeout sec
# Set a timeout, in SEC seconds, before automatically booting the default entry
# (normally the first entry defined).
timeout		10

## hiddenmenu
# Hides the menu by default (press ESC to see the menu)
#hiddenmenu

# Pretty colours
#color cyan/blue white/blue

## password ['--md5'] passwd
# If used in the first section of a menu file, disable all interactive editing
# control (menu entry editor and command-line)  and entries protected by the
# command 'lock'
# e.g. password topsecret
#      password --md5 $1$gLhU0/$aW78kHK1QfV3P2b2znUoe/
# password topsecret

#
# examples
#
# title		Windows 95/98/NT/2000
# root		(hd0,0)
# makeactive
# chainloader	+1
#
# title		Linux
# root		(hd0,1)
# kernel	/vmlinuz root=/dev/hda2 ro
#

#
# Put static boot stanzas before and/or after AUTOMAGIC KERNEL LIST

### BEGIN AUTOMAGIC KERNELS LIST
## lines between the AUTOMAGIC KERNELS LIST markers will be modified
## by the debian update-grub script except for the default options below

## DO NOT UNCOMMENT THEM, Just edit them to your needs

## ## Start Default Options ##
## default kernel options
## default kernel options for automagic boot options
## If you want special options for specific kernels use kopt_x_y_z
## where x.y.z is kernel version. Minor versions can be omitted.
## e.g. kopt=root=/dev/hda1 ro
##      kopt_2_6_8=root=/dev/hdc1 ro
##      kopt_2_6_8_2_686=root=/dev/hdc2 ro
# kopt=root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro

## default grub root device
## e.g. groot=(hd0,0)
# groot=(hd0,5)

## should update-grub create alternative automagic boot options
## e.g. alternative=true
##      alternative=false
# alternative=true

## should update-grub lock alternative automagic boot options
## e.g. lockalternative=true
##      lockalternative=false
# lockalternative=false

## additional options to use with the default boot option, but not with the
## alternatives
## e.g. defoptions=vga=791 resume=/dev/hda5
# defoptions=quiet splash

## should update-grub lock old automagic boot options
## e.g. lockold=false
##      lockold=true
# lockold=false

## Xen hypervisor options to use with the default Xen boot option
# xenhopt=

## Xen Linux kernel options to use with the default Xen boot option
# xenkopt=console=tty0

## altoption boot targets option
## multiple altoptions lines are allowed
## e.g. altoptions=(extra menu suffix) extra boot options
##      altoptions=(recovery) single
# altoptions=(recovery mode) single

## controls how many kernels should be put into the menu.lst
## only counts the first occurence of a kernel, not the
## alternative kernel options
## e.g. howmany=all
##      howmany=7
# howmany=all

## specify if running in Xen domU or have grub detect automatically
## update-grub will ignore non-xen kernels when running in domU and vice versa
## e.g. indomU=detect
##      indomU=true
##      indomU=false
# indomU=detect

## should update-grub create memtest86 boot option
## e.g. memtest86=true
##      memtest86=false
# memtest86=true

## should update-grub adjust the value of the default booted system
## can be true or false
# updatedefaultentry=false

## should update-grub add savedefault to the default options
## can be true or false
# savedefault=false

## ## End Default Options ##

title		Ubuntu 11.10, kernel 3.0.0-14-generic
root		(hd0,5)
kernel		/boot/vmlinuz-3.0.0-14-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-3.0.0-14-generic
quiet

title		Ubuntu 11.10, kernel 3.0.0-14-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-3.0.0-14-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-3.0.0-14-generic

title		Ubuntu 11.10, kernel 2.6.38-13-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.38-13-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.38-13-generic
quiet

title		Ubuntu 11.10, kernel 2.6.38-13-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.38-13-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.38-13-generic

title		Ubuntu 11.10, kernel 2.6.32-37-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.32-37-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.32-37-generic
quiet

title		Ubuntu 11.10, kernel 2.6.32-37-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.32-37-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.32-37-generic

title		Ubuntu 11.10, kernel 2.6.24-28-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-28-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.24-28-generic
quiet

title		Ubuntu 11.10, kernel 2.6.24-28-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-28-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.24-28-generic

title		Ubuntu 11.10, kernel 2.6.24-27-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-27-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.24-27-generic
quiet

title		Ubuntu 11.10, kernel 2.6.24-27-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-27-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.24-27-generic

title		Ubuntu 11.10, kernel 2.6.24-26-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-26-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.24-26-generic
quiet

title		Ubuntu 11.10, kernel 2.6.24-26-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-26-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.24-26-generic

title		Ubuntu 11.10, kernel 2.6.24-25-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-25-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.24-25-generic
quiet

title		Ubuntu 11.10, kernel 2.6.24-25-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-25-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.24-25-generic

title		Ubuntu 11.10, kernel 2.6.24-24-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-24-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.24-24-generic
quiet

title		Ubuntu 11.10, kernel 2.6.24-24-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-24-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.24-24-generic

title		Ubuntu 11.10, kernel 2.6.24-23-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-23-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.24-23-generic
quiet

title		Ubuntu 11.10, kernel 2.6.24-23-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-23-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.24-23-generic

title		Ubuntu 11.10, kernel 2.6.24-22-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-22-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.24-22-generic
quiet

title		Ubuntu 11.10, kernel 2.6.24-22-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.24-22-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.24-22-generic

title		Ubuntu 11.10, kernel 2.6.22-15-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.22-15-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro quiet splash 
initrd		/boot/initrd.img-2.6.22-15-generic
quiet

title		Ubuntu 11.10, kernel 2.6.22-15-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.22-15-generic root=UUID=eb553431-533f-4896-b8ab-4e2b8902688d ro  single
initrd		/boot/initrd.img-2.6.22-15-generic

title		Ubuntu 11.10, memtest86+
root		(hd0,5)
kernel		/boot/memtest86+.bin
quiet

### END DEBIAN AUTOMAGIC KERNELS LIST

# This is a divider, added to separate the menu items below from the Debian
# ones.
title		Other operating systems:
root


# This entry automatically added by the Debian installer for a non-linux OS
# on /dev/sda1
title		    Windows NT/2000/XP (loader)
map             (hd0) (hd1)
map             (hd1) (hd0)
rootnoverify    (hd1,0)
savedefault
makeactive
chainloader	+1

--------------------------------------------------------------------------------

=============================== sda6/etc/fstab: ================================

--------------------------------------------------------------------------------
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc                                       /proc          proc         defaults                    0  0  
# /dev/sda6
UUID=eb553431-533f-4896-b8ab-4e2b8902688d  /              ext3         defaults,errors=remount-ro  0  1  
# /dev/sda1
UUID=3E9801009800B883                      /media/sda1    ntfs         defaults,umask=007,gid=46   0  1  
# /dev/sda5
UUID=02cf9ea0-9a30-45ab-9627-738f12b37a45  none           swap         sw                          0  0  
/dev/scd0                                  /media/cdrom0  udf,iso9660  user,noauto,exec            0  0  
--------------------------------------------------------------------------------

=================== sda6: Location of files loaded by Grub: ====================

           GiB - GB             File                                 Fragment(s)

 131.968401432 = 141.699992064  boot/grub/menu.lst                             2
 131.880171299 = 141.605255680  boot/grub/stage2                               2
 131.918184757 = 141.646072320  boot/initrd.img-2.6.22-15-generic              3
 131.855848789 = 141.579139584  boot/initrd.img-2.6.22-15-generic.bak          5
 131.941977024 = 141.671619072  boot/initrd.img-2.6.24-22-generic              3
 131.856779575 = 141.580139008  boot/initrd.img-2.6.24-22-generic.bak          8
 131.879465580 = 141.604497920  boot/initrd.img-2.6.24-23-generic              3
 131.910723209 = 141.638060544  boot/initrd.img-2.6.24-23-generic.bak          3
 131.863939762 = 141.587827200  boot/initrd.img-2.6.24-24-generic              5
 131.958349705 = 141.689199104  boot/initrd.img-2.6.24-24-generic.bak          3
 131.830069065 = 141.551458816  boot/initrd.img-2.6.24-25-generic              3
 131.887381077 = 141.612997120  boot/initrd.img-2.6.24-25-generic.bak          3
 131.871149540 = 141.595568640  boot/initrd.img-2.6.24-26-generic              3
 131.895098209 = 141.621283328  boot/initrd.img-2.6.24-26-generic.bak          3
 131.845819950 = 141.568371200  boot/initrd.img-2.6.24-27-generic              6
 131.961779118 = 141.692881408  boot/initrd.img-2.6.24-27-generic.bak          7
 131.950655460 = 141.680937472  boot/initrd.img-2.6.24-28-generic              9
 131.901342869 = 141.627988480  boot/initrd.img-2.6.24-28-generic.bak          9
 411.982584476 = 442.362931712  boot/initrd.img-2.6.32-37-generic              7
 132.002478123 = 141.736581632  boot/initrd.img-2.6.38-13-generic              6
 411.892927647 = 442.266663424  boot/initrd.img-3.0.0-14-generic               6
 131.833887577 = 141.555558912  boot/vmlinuz-2.6.22-15-generic                 4
 131.923067570 = 141.651315200  boot/vmlinuz-2.6.24-22-generic                 3
 131.926657200 = 141.655169536  boot/vmlinuz-2.6.24-23-generic                 2
 131.821306705 = 141.542050304  boot/vmlinuz-2.6.24-24-generic                 2
 131.920938969 = 141.649029632  boot/vmlinuz-2.6.24-25-generic                 2
 131.897482395 = 141.623843328  boot/vmlinuz-2.6.24-26-generic                 2
 131.963552952 = 141.694786048  boot/vmlinuz-2.6.24-27-generic                 3
 131.974096775 = 141.706107392  boot/vmlinuz-2.6.24-28-generic                 6
 411.965319157 = 442.344393216  boot/vmlinuz-2.6.32-37-generic                 2
 131.968065739 = 141.699631616  boot/vmlinuz-2.6.38-13-generic                 7
 131.986692905 = 141.719632384  boot/vmlinuz-3.0.0-14-generic                  6
 132.002478123 = 141.736581632  initrd.img.old                                 6
 131.986692905 = 141.719632384  vmlinuz                                        6
 131.968065739 = 141.699631616  vmlinuz.old                                    7

================================ sdb1/boot.ini: ================================

--------------------------------------------------------------------------------
[boot loader]
timeout=1
default=multi(0)disk(0)rdisk(0)partition(1)\WINDOWS
[operating systems]
multi(0)disk(0)rdisk(0)partition(1)\WINDOWS="Microsoft Windows XP Professional" /noexecute=optin /fastdetect
--------------------------------------------------------------------------------

=========================== sdc1/boot/grub/grub.cfg: ===========================

--------------------------------------------------------------------------------

if loadfont /boot/grub/font.pf2 ; then
	set gfxmode=auto
	insmod efi_gop
	insmod efi_uga
	insmod gfxterm
	terminal_output gfxterm
fi

set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Try Ubuntu without installing" {
	set gfxpayload=keep
	linux	/casper/vmlinuz  file=/cdrom/preseed/ubuntu.seed boot=casper quiet splash --
	initrd	/casper/initrd.lz
}
menuentry "Install Ubuntu" {
	set gfxpayload=keep
	linux	/casper/vmlinuz  file=/cdrom/preseed/ubuntu.seed boot=casper only-ubiquity quiet splash --
	initrd	/casper/initrd.lz
}
menuentry "Check disc for defects" {
	set gfxpayload=keep
	linux	/casper/vmlinuz  boot=casper integrity-check quiet splash --
	initrd	/casper/initrd.lz
}
--------------------------------------------------------------------------------

========================= sdc1/syslinux/syslinux.cfg: ==========================

--------------------------------------------------------------------------------
# D-I config version 2.0
include menu.cfg
default vesamenu.c32
prompt 0
timeout 50

# If you would like to use the new menu and be presented with the option to install or run from USB at startup, remove # from the following line. This line was commented out (by request of many) to allow the old menu to be presented and to enable booting straight into the Live Environment! 
# ui gfxboot bootlogo
--------------------------------------------------------------------------------

=================== sdc1: Location of files loaded by Grub: ====================

           GiB - GB             File                                 Fragment(s)

            ?? = ??             boot/grub/grub.cfg                             1

================= sdc1: Location of files loaded by Syslinux: ==================

           GiB - GB             File                                 Fragment(s)

            ?? = ??             ldlinux.sys                                    1
            ?? = ??             syslinux/chain.c32                             1
            ?? = ??             syslinux/gfxboot.c32                           1
            ?? = ??             syslinux/syslinux.cfg                          1
            ?? = ??             syslinux/vesamenu.c32                          1

============== sdc1: Version of COM32(R) files used by Syslinux: ===============

 syslinux/chain.c32                 :  COM32R module (v4.xx)
 syslinux/gfxboot.c32               :  COM32R module (v4.xx)
 syslinux/vesamenu.c32              :  COM32R module (v4.xx)



```

I'm really no good with this, but as a note i can tell you that this entry might be taken into consideration:

```
This entry automatically added by the Debian installer for a non-linux OS
# on /dev/sda1
title		    Windows NT/2000/XP (loader)
map             (hd0) (hd1)
map             (hd1) (hd0)
rootnoverify    (hd1,0)
savedefault
makeactive
chainloader	+1
```

The two map entries are there to trick windows that it's installed in the first hard drive. Not sure that it means anything to you...

So.. My problem is that somewhere there's a reference to **sda1**, which doesn't exist and this somehow makes my ubuntu not to boot properly.

Anyone with pointers to solve this problem?

---

### Post by drs305 on 2012-01-04
It's the reference to sda1 in your fstab file:

> =============================== sda6/etc/fstab: ================================

--------------------------------------------------------------------------------
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc                                       /proc          proc         defaults                    0  0  
# /dev/sda6
UUID=eb553431-533f-4896-b8ab-4e2b8902688d  /              ext3         defaults,errors=remount-ro  0  1  
[COLOR="Red"]
# /dev/sda1
UUID=3E9801009800B883                      /media/sda1    ntfs         defaults,umask=007,gid=46   0  1  [/COLOR]
# /dev/sda5
UUID=02cf9ea0-9a30-45ab-9627-738f12b37a45  none           swap         sw                          0  0  
/dev/scd0                                  /media/cdrom0  udf,iso9660  user,noauto,exec            0  0  
-----------------------

To edit the file, if you can boot the recovery mode:
```
nano /etc/fstab
```
Remove the line or place a # symbol at the start.

If you cannot boot to the recovery mode, boot a LiveCD to the Desktop (Try It), then mount your Ubuntu partition and edit the real fstab file:
```
sudo mount /dev/sda6 /mnt
gksu gedit /mnt/etc/fstab
```

---

### Post by pJansson on 2012-01-04
Thanx for all the help guys!

I first tried drs305 1st option. Unfortunately, i couldn't figure out to save the changes, there was commands at the bottom but i couldn't use them.

I was forced to hit the power switch and go for option 2. And that one worked! Yay!

Still can't boot an x-session though. Now it ubuntu just freezes before the login screen instead  :(

The reference is gone though, so for this matter the issues solved...

---

### Post by ehamman on 2012-01-27
I would appreciate some help with a similar issue I have after upgrading  from 10.10 to 11.10 (lubuntu).
10.10 worked fine after install and after the updates loaded.  Then after I did a reboot after the upgrade was done, the screen goes to psychedelic snow and my Caps lock and Scroll lock lights keep flashing - nothing happens.

I've made a copy of the boot record similar to the original query using the live CD, but am too much of a rookie to know what is going on. 

I do have to note that I previously tried to install Xubuntu 11.10 and Kubuntu 11.10 from a live DVD - with the same problem.

History of the drive is it started with Ubunutu 8 and upgraded all the way to 11.10, then I tried a dual boot with openSuse.  This did not work so I played around with openSuse that worked fine (apart from sound), which is why I decided to go back to the good old trusted Ubuntu.

Hope someone can help.


```
                  Boot Info Script 0.60    from 17 May 2011


============================= Boot Info Summary: ===============================

 => Grub2 (v1.99) is installed in the MBR of /dev/sda and looks at sector 1 of 
    the same hard drive for core.img. core.img is at this location and looks 
    for (,msdos1)/boot/grub on this drive.

sda1: __________________________________________________________________________

    File system:       ext4
    Boot sector type:  -
    Boot sector info:  
    Operating System:  Ubuntu 11.04
    Boot files:        /boot/grub/grub.cfg /etc/fstab /boot/grub/core.img

sda2: __________________________________________________________________________

    File system:       Extended Partition
    Boot sector type:  Unknown
    Boot sector info:  

sda5: __________________________________________________________________________

    File system:       swap
    Boot sector type:  -
    Boot sector info:  

============================ Drive/Partition Info: =============================

Drive: sda _____________________________________________________________________

Disk /dev/sda: 500.1 GB, 500107862016 bytes
255 heads, 63 sectors/track, 60801 cylinders, total 976773168 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes

Partition  Boot  Start Sector    End Sector  # of Sectors  Id System

/dev/sda1    *          2,048   970,631,167   970,629,120  83 Linux
/dev/sda2         970,633,214   976,771,071     6,137,858   5 Extended
/dev/sda5         970,633,216   976,771,071     6,137,856  82 Linux swap / Solaris


"blkid" output: ________________________________________________________________

Device           UUID                                   TYPE       LABEL

/dev/loop0                                              squashfs   
/dev/sda1        8b64fd27-6ef6-4571-8d71-0d1285d56e60   ext4       
/dev/sda5        41a8f25d-b195-4c18-808c-3579032a8bd4   swap       

================================ Mount points: =================================

Device           Mount_Point              Type       Options

/dev/loop0       /rofs                    squashfs   (ro,noatime)
/dev/sda1        /media/8b64fd27-6ef6-4571-8d71-0d1285d56e60 ext4       (rw,nosuid,nodev,uhelper=udisks)
/dev/sr0         /cdrom                   iso9660    (ro,noatime)


=========================== sda1/boot/grub/grub.cfg: ===========================

--------------------------------------------------------------------------------
#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub
#

### BEGIN /etc/grub.d/00_header ###
if [ -s $prefix/grubenv ]; then
  set have_grubenv=true
  load_env
fi
set default="0"
if [ "${prev_saved_entry}" ]; then
  set saved_entry="${prev_saved_entry}"
  save_env saved_entry
  set prev_saved_entry=
  save_env prev_saved_entry
  set boot_once=true
fi

function savedefault {
  if [ -z "${boot_once}" ]; then
    saved_entry="${chosen}"
    save_env saved_entry
  fi
}

function recordfail {
  set recordfail=1
  if [ -n "${have_grubenv}" ]; then if [ -z "${boot_once}" ]; then save_env recordfail; fi; fi
}

function load_video {
  insmod vbe
  insmod vga
  insmod video_bochs
  insmod video_cirrus
}

insmod part_msdos
insmod ext2
set root='(/dev/sda,msdos1)'
search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
if loadfont /usr/share/grub/unicode.pf2 ; then
  set gfxmode=auto
  load_video
  insmod gfxterm
fi
terminal_output gfxterm
insmod part_msdos
insmod ext2
set root='(/dev/sda,msdos1)'
search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
set locale_dir=($root)/boot/grub/locale
set lang=en_US
insmod gettext
if [ "${recordfail}" = 1 ]; then
  set timeout=-1
else
  set timeout=10
fi
### END /etc/grub.d/00_header ###

### BEGIN /etc/grub.d/05_debian_theme ###
set menu_color_normal=white/black
set menu_color_highlight=black/light-gray
### END /etc/grub.d/05_debian_theme ###

### BEGIN /etc/grub.d/10_linux ###
if [ ${recordfail} != 1 ]; then
  if [ -e ${prefix}/gfxblacklist.txt ]; then
    if hwmatch ${prefix}/gfxblacklist.txt 3; then
      if [ ${match} = 0 ]; then
        set linux_gfx_mode=keep
      else
        set linux_gfx_mode=text
      fi
    else
      set linux_gfx_mode=text
    fi
  else
    set linux_gfx_mode=keep
  fi
else
  set linux_gfx_mode=text
fi
export linux_gfx_mode
if [ "$linux_gfx_mode" != "text" ]; then load_video; fi
menuentry 'Ubuntu, with Linux 2.6.38-13-generic' --class ubuntu --class gnu-linux --class gnu --class os {
	recordfail
	set gfxpayload=$linux_gfx_mode
	insmod part_msdos
	insmod ext2
	set root='(/dev/sda,msdos1)'
	search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
	linux	/boot/vmlinuz-2.6.38-13-generic root=UUID=8b64fd27-6ef6-4571-8d71-0d1285d56e60 ro   quiet splash vt.handoff=7
	initrd	/boot/initrd.img-2.6.38-13-generic
}
menuentry 'Ubuntu, with Linux 2.6.38-13-generic (recovery mode)' --class ubuntu --class gnu-linux --class gnu --class os {
	recordfail
	set gfxpayload=$linux_gfx_mode
	insmod part_msdos
	insmod ext2
	set root='(/dev/sda,msdos1)'
	search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
	echo	'Loading Linux 2.6.38-13-generic ...'
	linux	/boot/vmlinuz-2.6.38-13-generic root=UUID=8b64fd27-6ef6-4571-8d71-0d1285d56e60 ro single 
	echo	'Loading initial ramdisk ...'
	initrd	/boot/initrd.img-2.6.38-13-generic
}
submenu "Previous Linux versions" {
menuentry 'Ubuntu, with Linux 2.6.35-32-generic' --class ubuntu --class gnu-linux --class gnu --class os {
	recordfail
	set gfxpayload=$linux_gfx_mode
	insmod part_msdos
	insmod ext2
	set root='(/dev/sda,msdos1)'
	search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
	linux	/boot/vmlinuz-2.6.35-32-generic root=UUID=8b64fd27-6ef6-4571-8d71-0d1285d56e60 ro   quiet splash vt.handoff=7
	initrd	/boot/initrd.img-2.6.35-32-generic
}
menuentry 'Ubuntu, with Linux 2.6.35-32-generic (recovery mode)' --class ubuntu --class gnu-linux --class gnu --class os {
	recordfail
	set gfxpayload=$linux_gfx_mode
	insmod part_msdos
	insmod ext2
	set root='(/dev/sda,msdos1)'
	search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
	echo	'Loading Linux 2.6.35-32-generic ...'
	linux	/boot/vmlinuz-2.6.35-32-generic root=UUID=8b64fd27-6ef6-4571-8d71-0d1285d56e60 ro single 
	echo	'Loading initial ramdisk ...'
	initrd	/boot/initrd.img-2.6.35-32-generic
}
}
### END /etc/grub.d/10_linux ###

### BEGIN /etc/grub.d/20_linux_xen ###
### END /etc/grub.d/20_linux_xen ###

### BEGIN /etc/grub.d/20_memtest86+ ###
menuentry "Memory test (memtest86+)" {
	insmod part_msdos
	insmod ext2
	set root='(/dev/sda,msdos1)'
	search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
	linux16	/boot/memtest86+.bin
}
menuentry "Memory test (memtest86+, serial console 115200)" {
	insmod part_msdos
	insmod ext2
	set root='(/dev/sda,msdos1)'
	search --no-floppy --fs-uuid --set=root 8b64fd27-6ef6-4571-8d71-0d1285d56e60
	linux16	/boot/memtest86+.bin console=ttyS0,115200n8
}
### END /etc/grub.d/20_memtest86+ ###

### BEGIN /etc/grub.d/30_os-prober ###
if [ "x${timeout}" != "x-1" ]; then
  if keystatus; then
    if keystatus --shift; then
      set timeout=-1
    else
      set timeout=0
    fi
  else
    if sleep --interruptible 3 ; then
      set timeout=0
    fi
  fi
fi
### END /etc/grub.d/30_os-prober ###

### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
### END /etc/grub.d/40_custom ###

### BEGIN /etc/grub.d/41_custom ###
if [ -f  $prefix/custom.cfg ]; then
  source $prefix/custom.cfg;
fi
### END /etc/grub.d/41_custom ###
--------------------------------------------------------------------------------

=============================== sda1/etc/fstab: ================================

--------------------------------------------------------------------------------
# /etc/fstab: static file system information.
#
# Use 'blkid -o value -s UUID' to print the universally unique identifier
# for a device; this may be used with UUID= as a more robust way to name
# devices that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc            /proc           proc    nodev,noexec,nosuid 0       0
# / was on /dev/sda1 during installation
UUID=8b64fd27-6ef6-4571-8d71-0d1285d56e60 /               ext4    errors=remount-ro 0       1
# swap was on /dev/sda5 during installation
UUID=41a8f25d-b195-4c18-808c-3579032a8bd4 none            swap    sw              0       0
/dev/fd0        /media/floppy0  auto    rw,user,noauto,exec,utf8 0       0
--------------------------------------------------------------------------------

=================== sda1: Location of files loaded by Grub: ====================

           GiB - GB             File                                 Fragment(s)

 284.128028870 = 305.080147968  boot/grub/core.img                             1
 112.667781830 = 120.976109568  boot/grub/grub.cfg                             1
   0.841392517 = 0.903438336    boot/initrd.img-2.6.35-32-generic              2
   1.766021729 = 1.896251392    boot/initrd.img-2.6.38-13-generic              2
 284.258983612 = 305.220759552  boot/vmlinuz-2.6.35-32-generic                 1
   1.220035553 = 1.310003200    boot/vmlinuz-2.6.38-13-generic                 1
   1.766021729 = 1.896251392    initrd.img                                     2
   0.841392517 = 0.903438336    initrd.img.old                                 2
   1.220035553 = 1.310003200    vmlinuz                                        1
 284.258983612 = 305.220759552  vmlinuz.old                                    1

======================== Unknown MBRs/Boot Sectors/etc: ========================

Unknown BootLoader on sda2

00000000  ca f2 49 f1 ca f2 49 f1  ca f2 49 f1 ca f2 49 f1  |..I...I...I...I.|
*
00000020  00 00 00 00 00 00 00 00  ca f2 49 f1 ca f2 49 f1  |..........I...I.|
00000030  ca f2 49 f1 ca f2 49 f1  ca f2 49 f1 54 50 52 43  |..I...I...I.TPRC|
00000040  36 30 33 20 00 00 34 42  00 00 38 42 d6 ca 3b 47  |603 ..4B..8B..;G|
00000050  0b 75 0b 48 09 82 9a 43  00 00 80 3f b0 8b 8d 43  |.u.H...C...?...C|
00000060  22 5a 72 42 00 00 00 00  00 00 1b 43 41 4e 47 20  |"ZrB.......CANG |
00000070  20 20 20 20 20 20 20 20  00 00 40 40 ca f2 49 f1  |        ..@@..I.|
00000080  ca f2 49 f1 ca f2 49 f1  ca f2 49 f1 ca f2 49 f1  |..I...I...I...I.|
*
00000100  ca f2 49 f1 00 00 00 00  00 00 00 00 ca f2 49 f1  |..I...........I.|
00000110  ca f2 49 f1 ca f2 49 f1  ca f2 49 f1 ca f2 49 f1  |..I...I...I...I.|
00000120  cd cc cc 3d 00 00 20 41  00 00 a0 40 00 00 a0 40  |...=.. A...@...@|
00000130  00 00 80 3f 00 00 80 3f  00 00 80 3f 00 00 80 3f  |...?...?...?...?|
00000140  00 00 80 3f 56 20 20 20  20 20 20 20 11 45 3f 47  |...?V       .E?G|
00000150  35 32 0a 48 e5 d3 45 43  00 00 0c 42 2d 20 20 20  |52.H..EC...B-   |
00000160  20 20 20 20 20 20 20 20  b8 1e 1e 42 66 66 04 42  |        ...Bff.B|
00000170  41 4e 47 20 20 20 20 20  20 20 20 20 00 00 40 40  |ANG         ..@@|
00000180  54 50 44 33 38 35 20 20  00 00 80 3f 00 00 80 3f  |TPD385  ...?...?|
00000190  56 20 20 20 20 20 20 20  00 00 80 3f cd cc cc 3d  |V       ...?...=|
000001a0  00 00 20 41 00 00 a0 40  00 00 a0 40 00 00 80 3f  |.. A...@...@...?|
000001b0  00 00 80 3f 00 00 80 3f  00 00 80 3f 00 00 00 fe  |...?...?...?....|
000001c0  ff ff 82 fe ff ff 02 00  00 00 00 a8 5d 00 00 00  |............]...|
000001d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
00000200


=============================== StdErr Messages: ===============================

unlzma: Decoder error

```

---

### Post by drs305 on 2012-01-28
ehamman,

Your files look okay except for one thing. Several of your boot files are located pretty deep on the disk. Older BIOS can't 'see' that far (137GB limit) onto the disk until after an OS boots. This may be your problem.

Boot to the Grub menu, press 'c' to get to the grub prompt, then run the following command:
```
ls (hd0,1)/boot/grub/core.img
ls (hd0,1)/boot/vmlinuz-2.6.35-32-generic 
```
They should return "core.img" / "vmlinuz-2.6.35-32-generic" or  "error: file not found."

If it doesn't find these files, you will need to either shrink your linux partition to less than 130 GB or so, create a separate /boot partition within the first 130GB, or update/check your BIOS to enable large drives (perhaps listed as LBA option).

If Grub does see the files, you can boot the LiveCD and try to reinstall Grub:
```
sudo mount /dev/sda1 /mnt
sudo grub-install --root-directory=/mnt /dev/sda
```
Don't use the partition number in the second command.

You can also try Boot Repair. You can install it on the LiveCD and let it try to fix things. See the link in my signature line.

---

### Post by ehamman on 2012-01-28
Thanks for that *drs305*
I've done the check through grub and it sees both files.
I've also tried the re-install of grub, but that did not work either.
Have then gone the route to reduce the partition where my linux reside to 100GB and no luck there as well.  This is the only operating system that I'm trying to install so no issues with windows or the like.
I've actually tried to reformat the drive and rewrite the MBR as well ans still not luck.  After the grub menu I am greeted by a snowy screen, the  black and then when it is suppose to kick in the operating system I get a red flashing screen with my Caps lock and Scroll lock lights flasing on the keyboard.  Boots fine from most liveDVD's, but just not from the HDD anymore.
I've checked the Bios Rom is  ASUSTeK EZ Flash B325.  Running on a P5N-MX motherboard, V0202 dated 12/17/2007.

I'm not worried about a complete re-install at this stage, just want to find some way to get up and running with the drive and an OS.
The one thing I find weird is that even though it says I got a 500GB HDD, when I get into Gparted I can see only 465GB allocated.

Thanks anyway - I'll just have to keep searching or just buy  a new drive I guess.

---

### Post by ehamman on 2012-01-28
What I have noticed as well, when I try to boot on the rescue/safe boot, then just after it tries to "loading initial ramdisk" it goes into the flashing fit - this time a black and white vertical striped screen.

---

### Post by oldfred on 2012-01-28
What video card/chip do you have? Often a video issue where a parameter is required to boot. The nomodeset often works for many systems.
May also need other parameters which just requires experimentation or search for similar systems and similar issues with solutions.

Natty or later Video issues. MAFoElffen
[http://ubuntuforums.org/showthread.php?t=1743535](http://ubuntuforums.org/showthread.php?t=1743535)

Resetting an out&#8208;of&#8208;range resolution (does not include grub's set gfxmode=640x480)
[https://wiki.ubuntu.com/X/Config/Resolution#Resetting_an_out-of-range_resolution](https://wiki.ubuntu.com/X/Config/Resolution#Resetting_an_out-of-range_resolution)
Repair grub's video mode and other settings
[https://launchpad.net/grub-customizer](https://launchpad.net/grub-customizer)

How to set NOMODESET and other kernel boot options in grub2 
[http://ubuntuforums.org/showthread.php?t=1613132](http://ubuntuforums.org/showthread.php?t=1613132)
[https://help.ubuntu.com/community/BootOptions](https://help.ubuntu.com/community/BootOptions)

---

