---
title: "m1530 Touchpad: Intermitent Vertical scrolling after Kernel update"
date: 2008-06-08
forum: Dell Ubuntu Support (CLOSED)
---

### Post by sc00ter on 2008-06-08
Hardware: Dell M1530 (XPS)
O/S: Ubuntu (Hardy Heron) 8.04 LTS (32bit)

After the last kernel update, 2.6.24-19-generic the vertical scrolling behavior on the touchpad doesn't always work.

Sometimes it does after a reboot, sometimes it doesn't. This was working reliably when on kernel 2.6.24-16-generic.

Under Mouse Preferences, the touchpad disappears too when there's no vertical scrolling.

Only after various reboots does the vertical scrolling work (along with the touchpad tab under Mouse Preferences). But I stress, it's very unpredictable.

Below is the device section for the touchpad from my /etc/X11/xorg.conf:

```
Section "InputDevice"
	Identifier	"Synaptics Touchpad"
	Driver		"synaptics"
	Option		"SendCoreEvents"	"true"
	Option		"Device"	"/dev/psaux"
	Option		"Protocol"	"auto-dev"
	Option		"HorizEdgeScroll"	"0"
	Option		"ZAxisMapping" "4 5"
	Option		"Emulate3Buttons" "on"
	Option		"SHMConfig" "on"
	Option		"VertEdgeScroll" "on"
	Option		"VertTwoFingerScroll" "on"
	Option		"LeftEdge" "85"
	Option		"RightEdge" "830"
	Option		"TopEdge" "85"
	Option		"BottomEdge" "715"
	Option		"FingerLow" "25"
	Option		"FingerHigh" "30"
	Option		"MaxTapTime" "180"
	Option		"MaxTapMove" "220"
	Option		"MinSpeed" "0.45"
	Option		"MaxSpeed" "0.75"
	Option		"AccelFactor" "0.020"
EndSection
```

I've also attached my **dmesg** output.

I'm going to revert back to kernel 2.6.24-16-generic for the time being. Anyone else hitting this problem?

---

### Post by JSHN on 2008-06-24
Same here, noticed it just a little time ago. Was going to reinstall so I didn't care then, but the problem came back again after a reinstallation and upgrade, so I can also confirm this.

---

### Post by sc00ter on 2008-06-26
(Bump) Anyone else getting this issue? I'm still holding off using kernel 2.6.24-19 until I find a working solution.

---

### Post by OffHand on 2008-06-26
Works for me

---

### Post by titimoi on 2008-06-26
I was getting crazy trying to make this Touchpad working.. I didn't thought it could come from the upgraded kernel.. Does your gsynaptics config opens ? (when you go System>Preference>Touchpad ?) mine says that SHMConfig should be "true" but it is !!

---

### Post by JSHN on 2008-06-27
Strange.....now the problem is gone...everything is working like it should, maybe a update fixed it, I have not idea but I'm very happy it's working again. =)

---

### Post by titimoi on 2008-06-27
> **JSHN said:**
> Strange.....now the problem is gone...everything is working like it should, maybe a update fixed it, I have not idea but I'm very happy it's working again. =)

could you please give us your complete xorg.conf, do you have another (usb for example) mouse ?

---

### Post by JSHN on 2008-06-27
Oh yeah, here it is.

```
# xorg.conf (X.Org X Window System server configuration file)
#
# This file was generated by dexconf, the Debian X Configuration tool, using
# values from the debconf database.
#
# Edit this file with caution, and see the xorg.conf manual page.
# (Type "man xorg.conf" at the shell prompt.)
#
# This file is automatically updated on xserver-xorg package upgrades *only*
# if it has not been modified since the last upgrade of the xserver-xorg
# package.
#
# If you have edited this file but would like it to be automatically updated
# again, run the following command:
#   sudo dpkg-reconfigure -phigh xserver-xorg

Section "InputDevice"
	Identifier	"Generic Keyboard"
	Driver		"kbd"
	Option		"XkbRules"	"xorg"
	Option		"XkbModel"	"pc105"
	Option		"XkbLayout"	"se"
EndSection

Section "InputDevice"
	Identifier	"Configured Mouse"
	Driver		"mouse"
	Option		"CorePointer"
EndSection

Section "InputDevice"
	Identifier	"Synaptics Touchpad"
	Driver		"synaptics"
	Option		"SendCoreEvents"	"true"
	Option		"Device"	"/dev/psaux"
	Option		"Protocol"	"auto-dev"
	Option		"HorizEdgeScroll"	"0"
EndSection

Section "Device"
	Identifier	"Configured Video Device"
	Driver		"nvidia"
	Option      "OnDemandVBlankInterrupts" "True"
	Option		"NoLogo"	"True"
EndSection

Section "Monitor"
	Identifier	"Configured Monitor"
EndSection

Section "Screen"
	Identifier	"Default Screen"
	Monitor		"Configured Monitor"
	Device		"Configured Video Device"
	Defaultdepth	24
EndSection

Section "ServerLayout"
	Identifier	"Default Layout"
  screen "Default Screen"
	Inputdevice	"Synaptics Touchpad"
EndSection
Section "Module"
	Load		"glx"
EndSection
```

I haven't made any changed to it so it should be like default.

And yes, I have an external mouse that I'm using sometimes, when I had the problem I first though that this problem came when I started the PC with the external mouse connected, but I tested this and the problem was just random, had nothing to do with the mouse.

I'm sorry I cannot tell you what solved it, if you need more info just send me a message or reply here and I will help you as good as I can.

EDIT: I see that one thing I changed was adding OnDemandVBlankInterrupts to nvidia, but that shouldn't have anything to do with it.

---

### Post by titimoi on 2008-06-27
perfect thank you very much.. I will just copy/paste what I need.. and wait for it to work ! Thank you

---

### Post by JSHN on 2008-06-27
No problem, I hope you get it to work. =)

---

### Post by slabix on 2008-06-27
This morning I installed the most recent 2.4.24-19 generic kernel update, and here's what I've found so far.

1. Following restart after update the touchpad "worked" but was moving very, very slowly. I went to --System --Preferences --Mouse and changed the acceleration and sensitivity settings and restarted. Still, the touchpad tab is missing from Mouse Preferences

2. On the second restart, The mouse seems to be behaving normally, except there is still no Touchpad tab in Mouse Preferences.

I suppose I would be satisfied at this point, except the touchpad is set by defaut to "tap for clicks," and I really don't like this.

Any more ideas out there?

---

### Post by titimoi on 2008-06-27
@JSHN : can you just tell me what kind of Touchpad you have, giving me the result of those command : > sudo cat /proc/bus/input/devices | grep GlidePoint just to verify if have the same

@slabix: can you give us your xorg.conf for use to be able to see what is wrong ;)

---

### Post by cespinal on 2008-06-27
My vertical scrolling works intermitently as well... where can I start with to get this soolved? HELP

---

### Post by cjwalle on 2008-06-27
Oh thank god, I thought I was the only one. The issue seems to be that the "Option "SHMConfig" "true"" isn't recognized, as if it wasn't there. I'm a complete linux newbie, so any help would be appreciated. Here's my xorg:


```
# xorg.conf (xorg X Window System server configuration file)
#
# This file was generated by dexconf, the Debian X Configuration tool, using
# values from the debconf database.
#
# Edit this file with caution, and see the xorg.conf manual page.
# (Type "man xorg.conf" at the shell prompt.)
#
# This file is automatically updated on xserver-xorg package upgrades *only*
# if it has not been modified since the last upgrade of the xserver-xorg
# package.
#
# If you have edited this file but would like it to be automatically updated
# again, run the following command:
#   sudo dpkg-reconfigure -phigh xserver-xorg

Section "Module"
	Load "synaptics"
EndSection

Section "Screen"
	Identifier	"Default Screen"
	Device		"nVidia Corporation G80 [GeForce 8600M GT]"
	Monitor		"Generic Monitor"
	SubSection "Display"
		Modes		"1440x1440"
	EndSubSection
	Option		"AddARGBGLXVisuals"	"True"
	Defaultdepth	24
EndSection

Section "Device"
	Identifier	"nVidia Corporation G80 [GeForce 8600M GT]"
	Driver		"nvidia"
	Busid		"PCI:1:0:0"
EndSection

Section "InputDevice"
	Identifier	"Generic Keyboard"
	Driver		"kbd"
	Option		"CoreKeyboard"
	Option		"XkbRules"	"xorg"
	Option		"XkbModel"	"pc105"
	Option		"XkbLayout"	"no"
EndSection

Section "InputDevice"
	Identifier "Synaptics Touchpad"
	Driver "synaptics"
	Option "SHMConfig" "on"
	Option "SendCoreEvents" "true"
	Option "Device" "/dev/psaux"
	Option "Protocol" "auto-dev"
	Option "ZAxisMapping" "4 5"
	Option "Emulate3Buttons" "on"
	Option "VertEdgeScroll" "on"
	Option "VertTwoFingerScroll" "on"
	Option "LeftEdge" "85"
	Option "RightEdge" "910"
	Option "TopEdge" "85"
	Option "BottomEdge" "715"
	Option "FingerLow" "25"
	Option "FingerHigh" "30"
	Option "MaxTapTime" "180"
	Option "MaxTapMove" "220"
EndSection

Section "InputDevice"
	Identifier	"Configured Mouse"
	Driver		"mouse"
	Option		"CorePointer"
	Option		"Device"	"/dev/input/mice"
	Option		"Protocol"	"ImPS/2"
	Option		"ZAxisMapping"	"4 5"
	Option		"Emulate3Buttons"	"true"
EndSection

Section "InputDevice"
	Driver		"wacom"
	Identifier	"stylus"
	Option		"Device"	"/dev/input/wacom"
	Option		"Type"	"stylus"
	Option		"ForceDevice"	"ISDV4"# Tablet PC ONLY
EndSection

Section "InputDevice"
	Driver		"wacom"
	Identifier	"eraser"
	Option		"Device"	"/dev/input/wacom"
	Option		"Type"	"eraser"
	Option		"ForceDevice"	"ISDV4"# Tablet PC ONLY
EndSection

Section "InputDevice"
	Driver		"wacom"
	Identifier	"cursor"
	Option		"Device"	"/dev/input/wacom"
	Option		"Type"	"cursor"
	Option		"ForceDevice"	"ISDV4"# Tablet PC ONLY
EndSection

Section "ServerLayout"
	Identifier	"Default Layout"
  	screen "Default Screen"
	Inputdevice	"Generic Keyboard" "CoreKeyboard"
	Inputdevice	"Configured Mouse" "CorePointer"
	# Uncomment if you have a wacom tablet
	#	InputDevice     "stylus"	"SendCoreEvents"
	#	InputDevice     "cursor"	"SendCoreEvents"
	#	InputDevice     "eraser"	"SendCoreEvents"
	Inputdevice	"Synaptics Touchpad" "AlwaysCore"
EndSection

Section "Monitor"
	Identifier	"Generic Monitor"
	Option		"DPMS"
	Horizsync	28-72
	Vertrefresh	43-60
EndSection

Section "Extensions"
	Option		"Composite"	"Enable"
EndSection
```

---

### Post by slabix on 2008-06-27
Here's my xorg.conf as requested. Thanks for being willing to look at it.

> Section "Screen"
	Identifier	"Default Screen"
	Monitor		"Configured Monitor"
	Device		"Configured Video Device"
	Option		"AddARGBGLXVisuals"	"True"
	Defaultdepth	24
EndSection

Section "Device"
	Identifier	"Configured Video Device"
	Driver		"nvidia"
EndSection

Section "InputDevice"
	Identifier	"Generic Keyboard"
	Driver		"kbd"
	Option		"XkbRules"	"xorg"
	Option		"XkbModel"	"pc105"
	Option		"XkbLayout"	"us"
EndSection

Section "InputDevice"
	Identifier	"Configured Mouse"
	Driver		"mouse"
	Option		"CorePointer"
EndSection

Section "InputDevice"
	Identifier	"Synaptics Touchpad"
	Driver		"synaptics"
	Option		"SendCoreEvents"	"true"
	Option		"Device"	"/dev/psaux"
	Option		"Protocol"	"auto-dev"
	Option		"HorizEdgeScroll"	"0"
EndSection

Section "ServerLayout"
	Identifier	"Default Layout"
  screen "Default Screen"
	Inputdevice	"Synaptics Touchpad"
EndSection

Section "Monitor"
	Identifier	"Configured Monitor"
EndSection

Section "Extensions"
	Option		"Composite"	"Enable"
EndSection

---

### Post by sc00ter on 2008-06-27
Here's the output I get from **sudo cat /proc/bus/input/devices** that's related to the touchpad on the M1530:
```

I: Bus=0011 Vendor=0002 Product=0008 Version=7321
N: Name="AlpsPS/2 ALPS GlidePoint"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input10
U: Uniq=
H: Handlers=mouse3 event10 
B: EV=f
B: KEY=420 0 70000 0 0 0 0 0 0 0 0
B: REL=3
B: ABS=1000003
```

Anyone from Dell checking out this thread? Any help or direction would be great. Thanks in advance.

---

### Post by titimoi on 2008-06-28
ok so we are speaking about the same Touchpad wich is an ALPS GlidePoint.. whcich causes so many problems.. some peaple get it work sometime without doing anything.. i think we should just wait until we update the kernel.. and get it fix

---

### Post by JSHN on 2008-06-28
I: Bus=0011 Vendor=0002 Product=0008 Version=7321
N: Name="AlpsPS/2 ALPS GlidePoint"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input10
U: Uniq=
H: Handlers=mouse3 event10 
B: EV=f
B: KEY=420 70000 0 0 0 0
B: REL=3
B: ABS=1000003

I also have the Alps you guys have.....still no problem here.

---

### Post by titimoi on 2008-06-28
that's really wierd, I just made a copy/paste of your whole xorg.conf JSHN (because I compared and we have the same hardware..) and the Touchpad has still no scroll.. did you install gsynaptics ? did you do something for this touch pad ? (install q synaptics or anything else ?)

---

### Post by JSHN on 2008-06-28
no, nothing alps-specific installed, everything just default.

hmmmm........maybe something with the menu.lst?

```
# menu.lst - See: grub(8), info grub, update-grub(8)
#            grub-install(8), grub-floppy(8),
#            grub-md5-crypt, /usr/share/doc/grub
#            and /usr/share/doc/grub-doc/.

## default num
# Set the default entry to the entry number NUM. Numbering starts from 0, and
# the entry number 0 is the default if the command is not used.
#
# You can specify 'saved' instead of a number. In this case, the default entry
# is the entry saved with the command 'savedefault'.
# WARNING: If you are using dmraid do not use 'savedefault' or your
# array will desync and will not let you boot your system.
default		0

## timeout sec
# Set a timeout, in SEC seconds, before automatically booting the default entry
# (normally the first entry defined).
timeout		1

## hiddenmenu
# Hides the menu by default (press ESC to see the menu)
hiddenmenu

# Pretty colours
#color cyan/blue white/blue

## password ['--md5'] passwd
# If used in the first section of a menu file, disable all interactive editing
# control (menu entry editor and command-line)  and entries protected by the
# command 'lock'
# e.g. password topsecret
## password --md5 $1$gLhU0/$aW78kHK1QfV3P2b2znUoe/
# password topsecret

#
# examples
#
# title		Windows 95/98/NT/2000
# root		(hd0,0)
# makeactive
# chainloader	+1
#
# title		Linux
# root		(hd0,1)
# kernel	/vmlinuz root=/dev/hda2 ro
#

#
# Put static boot stanzas before and/or after AUTOMAGIC KERNEL LIST

### BEGIN AUTOMAGIC KERNELS LIST
## lines between the AUTOMAGIC KERNELS LIST markers will be modified
## by the debian update-grub script except for the default options below

## DO NOT UNCOMMENT THEM, Just edit them to your needs

## ## Start Default Options ##
## default kernel options
## default kernel options for automagic boot options
## If you want special options for specific kernels use kopt_x_y_z
## where x.y.z is kernel version. Minor versions can be omitted.
## e.g. kopt=root=/dev/hda1 ro
##      kopt_2_6_8=root=/dev/hdc1 ro
##      kopt_2_6_8_2_686=root=/dev/hdc2 ro
# kopt=root=UUID=13d3e58d-8ddb-41dc-a7d9-49b054788fdb ro

## Setup crashdump menu entries
## e.g. crashdump=1
# crashdump=0

## default grub root device
## e.g. groot=(hd0,0)
# groot=(hd0,0)

## should update-grub create alternative automagic boot options
## e.g. alternative=true
##      alternative=false
# alternative=true

## should update-grub lock alternative automagic boot options
## e.g. lockalternative=true
##      lockalternative=false
# lockalternative=false

## additional options to use with the default boot option, but not with the
## alternatives
## e.g. defoptions=vga=791 resume=/dev/hda5
# defoptions=splash quiet rootflags=data=writeback i8042.nomux=1 vga=794

## should update-grub lock old automagic boot options
## e.g. lockold=false
##      lockold=true
# lockold=false

## Xen hypervisor options to use with the default Xen boot option
# xenhopt=

## Xen Linux kernel options to use with the default Xen boot option
# xenkopt=console=tty0

## altoption boot targets option
## multiple altoptions lines are allowed
## e.g. altoptions=(extra menu suffix) extra boot options
##      altoptions=(recovery) single
# altoptions=(recovery mode) single rootflags=data=writeback i8042.nomux=1 vga=794

## controls how many kernels should be put into the menu.lst
## only counts the first occurence of a kernel, not the
## alternative kernel options
## e.g. howmany=all
##      howmany=7
# howmany=all

## should update-grub create memtest86 boot option
## e.g. memtest86=true
##      memtest86=false
# memtest86=true

## should update-grub adjust the value of the default booted system
## can be true or false
# updatedefaultentry=false

## should update-grub add savedefault to the default options
## can be true or false
# savedefault=false

## ## End Default Options ##

title		Ubuntu 8.04, kernel 2.6.24-19-generic
root		(hd0,0)
kernel		/boot/vmlinuz-2.6.24-19-generic root=UUID=13d3e58d-8ddb-41dc-a7d9-49b054788fdb ro splash quiet rootflags=data=writeback i8042.nomux=1 vga=794
initrd		/boot/initrd.img-2.6.24-19-generic
quiet

title		Ubuntu 8.04, kernel 2.6.24-19-generic (recovery mode)
root		(hd0,0)
kernel		/boot/vmlinuz-2.6.24-19-generic root=UUID=13d3e58d-8ddb-41dc-a7d9-49b054788fdb ro single rootflags=data=writeback i8042.nomux=1 vga=794
initrd		/boot/initrd.img-2.6.24-19-generic

title		Ubuntu 8.04, kernel 2.6.24-16-generic
root		(hd0,0)
kernel		/boot/vmlinuz-2.6.24-16-generic root=UUID=13d3e58d-8ddb-41dc-a7d9-49b054788fdb ro splash quiet rootflags=data=writeback i8042.nomux=1 vga=794
initrd		/boot/initrd.img-2.6.24-16-generic
quiet

title		Ubuntu 8.04, kernel 2.6.24-16-generic (recovery mode)
root		(hd0,0)
kernel		/boot/vmlinuz-2.6.24-16-generic root=UUID=13d3e58d-8ddb-41dc-a7d9-49b054788fdb ro single rootflags=data=writeback i8042.nomux=1 vga=794
initrd		/boot/initrd.img-2.6.24-16-generic

title		Ubuntu 8.04, memtest86+
root		(hd0,0)
kernel		/boot/memtest86+.bin
quiet

### END DEBIAN AUTOMAGIC KERNELS LIST
```

I've disabled ipv6.
Set to no swap.
Enabled laptop-mode. (just powersaving features I think?, but maybe.)
Fixed the harddrive-cycle that makes the drive click. (hdparm -B 200)
I will try to think of more changes I've made.

( Also I'm traveling to New York in 4,5 hours, so after that I cannot replay for a week. )

---

### Post by titimoi on 2008-06-30
ok thank's for theses clarifications, I've seen with surprise yesterday, that my Touchpad was working perfect.. but today.. this satisfaction is gone.. :(

When you say power saving you mean this line ? : vga=794

---

### Post by JSHN on 2008-07-08
No, I mean that I enabled: ENABLE_LAPTOP_MODE in: /etc/default/acpi-support

---

### Post by cjwalle on 2008-08-05
Anyone resolved this issue yet? It's still bugging me.

---

### Post by titimoi on 2008-08-05
still not.. sometimes it works quite great, sometimes not, actually when it works (I mean when I get the scrool) I don't have the tap function (click when I tap on my touchpad) and I get errors when i shut down the computer, but when I don't have the scroll i have the tap function working and no errors, it is just randomly...

---

### Post by cjwalle on 2008-08-05
Quite odd. With me, it all works, or I lose everything except basic point and click functionality. No scrolling or anything. When it works, though, everything works the way I want it to. I guess that's something.

---

### Post by LiamGaerity on 2008-08-19
Hey all, I've got the same problem. Touchpad works intermittently between reboots. I've modified the kernal and the xorg.conf file with the available resources on these forums. Does anyone have any other suggestions that are stable?

---

### Post by LiamGaerity on 2008-08-25
***BUMP***

Is anyone else still having a problem with this? Any solutions?

---

### Post by axeloid on 2008-08-27
Hi all,
I've found that the problem does not appear randomly. It consistently appears when the computer is booted when powered differently than the last time it was booted. So, for example, if the last time it was booted with the AC power adaptor plugged in and you then (re)boot it only powered by the battery, then the touchpad options do not work properly. Also the other way arround. The touchpad options work back properly when the computer is (re)booted with the same power supply it had the last time it was booted. I hope this helps developers to fix this really annoying bug.

---

### Post by LiamGaerity on 2008-08-27
I've had the same experience. Thanks Axeloid for clarifying that.

---

### Post by 4Play on 2008-08-30
I have the same problem, and it's really bugging me, the vertical scroll is what i miss the most. And in regards to the power source theory, it doesnt hold with me, I just rebooted(on ac power), and the touchpad still has limited functionality.

Computer: XPS M1530
kernel: 2.6.24-19-generic

---

### Post by LiamGaerity on 2008-08-31
Does anyone know if this has been reported as a bug? Is there any "experts" out there working on this? Please help. It'd be greatly appreciated!

---

### Post by axeloid on 2008-09-02
The issue not only occurs when booting with or without the AC adaptor plugged, but also if between bootings i physically enable or disable the wireless adaptor. So maybe the issue comes up when any (or some) hardware is modified between one and the next boot.
I hope there is people getting onto this problem because it is really annoying, especially due to the tap clicking and lack of scrolling.

---

### Post by cathuria on 2008-09-02
I'm supposing this is related to a similar problem I'm having with my Wacom Intuos -- although I haven't seen another thread on that yet.

Sometimes the tablet will simply not respond, especially after a boot, but sometimes just if left idle for a moment.  Sometimes it comes back with a tap on the pad, but sometimes I have to reboot the desktop (ctrl-alt-bkspc) -- so is this a kernel or a desktop problem?

---

### Post by gunthr on 2008-10-19
Anyone find a solution to this? I get the same issue, with the same touchpad, using kernel 2.6.24-21-generic.

---

### Post by JSHN on 2008-10-20
I upgraded the BIOS to A09 and the problem was gone. I haven't used my laptop for a while now but I used it for like a week after the BIOS upgrade and I haven't had the problem anymore.

Try it and good luck!

---

### Post by egypt on 2008-12-05
I'm getting the same issue with a Latitude E6500 and the power source theory seems to hold.  If I'm on battery and reboot with AC (or vice versa), the Touchpad tab under System -> Preferences -> Mouse disappears and I have no scrolling.

```

$ uname -a
Linux localhost 2.6.27-9-generic #1 SMP Thu Nov 20 22:15:32 UTC 2008 x86_64 GNU/Linux

```

---

### Post by axeloid on 2009-02-03
Hi, it's been a while. I didn't manage to solve the problem while my system was still 8.04. However, i upgraded (via the normal ubuntu update) from Heron 8.04 to Ibex 8.10 and the problem is gone for good. Now i can even pull/put the power cable while loading/closing the system and no problem at all. The bios upgrades/downgrades didn't work for me, but just for the sake of completion, I'm currently using the bios version A12.

Good luck to all the rest.

---

