---
title: "Gutsy RC x64 .. no boot splash ??"
date: 2007-10-12
forum: x86 64-bit Users (Pre April '08)
---

### Post by OVERMiND on 2007-10-12
I just grabbed the RC ISO image of Gutsy x64, burned it and booted it .. I got no boot splash after the GRUB menu.. Then I installed the OS on my machine.. the same thing.. no bootsplash between GRUB and Login screen..   my monitor goes black in standby until Login .. is this normal ?

---

### Post by John.Michael.Kane on 2007-10-12
> **OVERMiND said:**
> I just grabbed the RC ISO image of Gutsy x64, burned it and booted it .. I got no boot splash after the GRUB menu.. Then I installed the OS on my machine.. the same thing.. no bootsplash between GRUB and Login screen..   my monitor goes black in standby until Login .. is this normal ?

What is the specs of the hardware you are running 64bit Ubuntu on?

As for being normal depends. Users in the past have had boot splash issues before.

---

### Post by OVERMiND on 2007-10-12
well here are the specs.. 

CPU: AMD Athlon64 X2 3800+
RAM: [GeIL 512 x 2 MB DDR-II 800 MHz]("http://www.geilusa.com/products/show/id/65")
Motherboard: [ASUS M2NPV-VM nVIDIA GeForce 6150 + nForce 430]("http://www.asus.com/products4.aspx?l1=3&l2=101&l3=0&model=1138&modelmenu=1")
GPU: [Palit 8600GT Sonic+]("http://www.palit.biz/en/products/nv_pcie_8600GT-Sonic+.htm")
Monitor: LG L226WTQ-SF 22'' 

and here is the **/boot/grub/menu.lst** file generated by Ubuntu.. [http://pastebin.com/ma60e8e0]("http://pastebin.com/ma60e8e0")

---

### Post by John.Michael.Kane on 2007-10-12
> **OVERMiND said:**
> well here are the specs.. 

CPU: AMD Athlon64 X2 3800+
RAM: [GeIL 512 x 2 MB DDR-II 800 MHz]("http://www.geilusa.com/products/show/id/65")
Motherboard: [ASUS M2NPV-VM nVIDIA GeForce 6150 + nForce 430]("http://www.asus.com/products4.aspx?l1=3&l2=101&l3=0&model=1138&modelmenu=1")
GPU: [Palit 8600GT Sonic+]("http://www.palit.biz/en/products/nv_pcie_8600GT-Sonic+.htm")
Monitor: LG L226WTQ-SF 22'' 

and here is the **/boot/grub/menu.lst** file generated by Ubuntu.. [http://pastebin.com/ma60e8e0]("http://pastebin.com/ma60e8e0")

Try this edit your /boot/grub/menu.lst
On line 132 where it says splash put vga=794 at the end, and reboot.

---

### Post by John Jason Jordan on 2007-10-13
I just downloaded and burned the amd64 RC also. I just wanted to check it out so I didn't install it. I'll upgrade my amd64 Feisty later when it's final. But I wanted to say that I had a similar problem. Instead of a splash screen I got a bunch of angled lines across the screen. I booted several times and even re-burned the ISO. Eventually I discovered that when I got to the angled lines and the CD drive quit spinning, if I did Ctrl-Alt-Bksp it would bring up a normal login screen. Thereafter it worked perfectly.

I have been using Ubuntu amd64 on this computer since Hoary and have never had that experience with any release, even betas. I suspect a lot of work was done to enable compiz and all that stuff and some of that work is responsible for the messed up boot splash screen. My video is "NVIDIA Corporation NV17 [GeForce4 420 Mac 32M/GeForce 440 Go 64M]".

I should also add that Gutsy is going to be sweet. Y'all have done an outstanding job.

---

### Post by OVERMiND on 2007-10-13
From what I understood from other users on this forum this is definitely a bootsplash bug .. at least on some x64 machines with ATi or nVIDIA cards.. the solution is to remove the splash kernel parameter from GRUB.. anyway I hope the final release will have this fixed :D

---

### Post by Gunner_Sr on 2007-10-13
I just installed 10.7 today and had the same problem on my laptop. How I fixed it was to install startmanager and run it and reboot and everything worked out well.

Cheers,

-cg

Dell Inspiron 1520 2GB RAM 8600GT Video 160GB HDD running Gutsy RC.

---

### Post by jpyanowski on 2007-10-14
I've had no problem with my fresh install of Gutsy 64-bit.

---

### Post by bkraptor on 2007-10-16
Same problem here, but on Gutsy 32bitRC with latest updates on Dell Inspiron 6400 with Core 2 Duo T7200, 2 GB RAM and ATI Radeon Mobility X1400 w/ 128 Mb of onboard vRAM.

---

### Post by dylix on 2007-10-16
same here, 64bit, nvidia

---

### Post by TNakos on 2007-10-16
hmmmm. try checking the synaptic. you might have something missing

---

### Post by atomicdad on 2007-10-16
I was having this problem as well. I first had the 32bit version of 7.04 installed and the splash screen came up. I updated to the 64bit version and lost the splash screen.

> Try this edit your /boot/grub/menu.lst
On line 132 where it says splash put vga=794 at the end, and reboot.

This gave me an error, saying something like it did not know what resolution it it was looking for, or something along those lines.

I put it in as vga=791 just after quiet splash and all is well now, I get the nice Ubuntu screen while the machine is booting.

So was the 794 posted in error or do different systems use different values (just wondering).

(Inspirion 1520,........)

---

### Post by dylix on 2007-10-16
yea ive tried all the things mentiond in here, still no luck.

---

### Post by dcstar on 2007-10-17
> **dylix said:**
> yea ive tried all the things mentiond in here, still no luck.

Possibly the system is trying to use a Refresh Rate that is invalid, and until the login screen is loaded using the xorg.conf settings you see nothing.

It may all depend on the video/monitor combinations people have, as mine also works of with a fresh Gutsy RC install.

PS - The Nvidia setup seems to turn off the Nvidia splash option in xorg.conf by default, some people way want to manually comment out the appropriate line to get it back.

---

### Post by bkraptor on 2007-10-18
I solved my problem following the instructions here: [https://bugs.launchpad.net/ubuntu/+bug/152726](https://bugs.launchpad.net/ubuntu/+bug/152726)

---

### Post by conehead77 on 2007-10-18
I just installed 64bit Gutsy on a separate Partition and get a black screen ("no signal") on my monitor after the GRUB menu.

I wont get into the login screen, i waited for about 10 minutes for it, harddrive is not working.

I tried the suggestion above with no luck.
I copied the xorg.conf from my current 7.04 installation, it didnt work.

Recovery mode works fine and the 32bit Gutsy beta version i had on this partition before also worked.

Im on a Intel(R) Pentium(R) 4 CPU 3.20GHz; width: 64 bits
video card: RV410 [Radeon X700 Pro (PCIE)]; size: 128MB; width: 64 bits; clock: 33MHz
1011 MB RAM

Any ideas? :confused:

edit: here is my menu.lst:```
# menu.lst - See: grub(8), info grub, update-grub(8)
#            grub-install(8), grub-floppy(8),
#            grub-md5-crypt, /usr/share/doc/grub
#            and /usr/share/doc/grub-doc/.

## default num
# Set the default entry to the entry number NUM. Numbering starts from 0, and
# the entry number 0 is the default if the command is not used.
#
# You can specify 'saved' instead of a number. In this case, the default entry
# is the entry saved with the command 'savedefault'.
# WARNING: If you are using dmraid do not use 'savedefault' or your
# array will desync and will not let you boot your system.
default		0

## timeout sec
# Set a timeout, in SEC seconds, before automatically booting the default entry
# (normally the first entry defined).
timeout		10

## hiddenmenu
# Hides the menu by default (press ESC to see the menu)
#hiddenmenu

# Pretty colours
#color cyan/blue white/blue

## password ['--md5'] passwd
# If used in the first section of a menu file, disable all interactive editing
# control (menu entry editor and command-line)  and entries protected by the
# command 'lock'
# e.g. password topsecret
#      password --md5 $1$gLhU0/$aW78kHK1QfV3P2b2znUoe/
# password topsecret

#
# examples
#
# title		Windows 95/98/NT/2000
# root		(hd0,0)
# makeactive
# chainloader	+1
#
# title		Linux
# root		(hd0,1)
# kernel	/vmlinuz root=/dev/hda2 ro
#

#
# Put static boot stanzas before and/or after AUTOMAGIC KERNEL LIST

### BEGIN AUTOMAGIC KERNELS LIST
## lines between the AUTOMAGIC KERNELS LIST markers will be modified
## by the debian update-grub script except for the default options below

## DO NOT UNCOMMENT THEM, Just edit them to your needs

## ## Start Default Options ##
## default kernel options
## default kernel options for automagic boot options
## If you want special options for specific kernels use kopt_x_y_z
## where x.y.z is kernel version. Minor versions can be omitted.
## e.g. kopt=root=/dev/hda1 ro
##      kopt_2_6_8=root=/dev/hdc1 ro
##      kopt_2_6_8_2_686=root=/dev/hdc2 ro
# kopt=root=UUID=3da925ff-a8d3-4f21-bec9-a5bc4f9b35de ro

## Setup crashdump menu entries
## e.g. crashdump=1
# crashdump=0

## default grub root device
## e.g. groot=(hd0,0)
# groot=(hd0,5)

## should update-grub create alternative automagic boot options
## e.g. alternative=true
##      alternative=false
# alternative=true

## should update-grub lock alternative automagic boot options
## e.g. lockalternative=true
##      lockalternative=false
# lockalternative=false

## additional options to use with the default boot option, but not with the
## alternatives
## e.g. defoptions=vga=791 resume=/dev/hda5
# defoptions=quiet splash

## should update-grub lock old automagic boot options
## e.g. lockold=false
##      lockold=true
# lockold=false

## Xen hypervisor options to use with the default Xen boot option
# xenhopt=

## Xen Linux kernel options to use with the default Xen boot option
# xenkopt=console=tty0

## altoption boot targets option
## multiple altoptions lines are allowed
## e.g. altoptions=(extra menu suffix) extra boot options
##      altoptions=(recovery) single
# altoptions=(recovery mode) single

## controls how many kernels should be put into the menu.lst
## only counts the first occurence of a kernel, not the
## alternative kernel options
## e.g. howmany=all
##      howmany=7
# howmany=all

## should update-grub create memtest86 boot option
## e.g. memtest86=true
##      memtest86=false
# memtest86=true

## should update-grub adjust the value of the default booted system
## can be true or false
# updatedefaultentry=false

## should update-grub add savedefault to the default options
## can be true or false
# savedefault=false

## ## End Default Options ##

title		Ubuntu 7.10, kernel 2.6.22-14-generic
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.22-14-generic root=UUID=3da925ff-a8d3-4f21-bec9-a5bc4f9b35de ro quiet splash
initrd		/boot/initrd.img-2.6.22-14-generic
quiet

title		Ubuntu 7.10, kernel 2.6.22-14-generic (recovery mode)
root		(hd0,5)
kernel		/boot/vmlinuz-2.6.22-14-generic root=UUID=3da925ff-a8d3-4f21-bec9-a5bc4f9b35de ro single
initrd		/boot/initrd.img-2.6.22-14-generic

title		Ubuntu 7.10, memtest86+
root		(hd0,5)
kernel		/boot/memtest86+.bin
quiet

### END DEBIAN AUTOMAGIC KERNELS LIST

# This is a divider, added to separate the menu items below from the Debian
# ones.
title		Other operating systems:
root


# This entry automatically added by the Debian installer for a non-linux OS
# on /dev/sda1
title		Microsoft Windows XP Home Edition
root		(hd0,0)
savedefault
makeactive
chainloader	+1


# This entry automatically added by the Debian installer for an existing
# linux installation on /dev/sdb2.
title		Ubuntu, kernel 2.6.20-16-generic (on /dev/sdb2)
root		(hd1,1)
kernel		/boot/vmlinuz-2.6.20-16-generic root=UUID=4fa60d9a-d5c3-4e03-9edd-e097baef7ad7 ro quiet splash 
initrd		/boot/initrd.img-2.6.20-16-generic
savedefault
boot


# This entry automatically added by the Debian installer for an existing
# linux installation on /dev/sdb2.
title		Ubuntu, kernel 2.6.20-16-generic (recovery mode) (on /dev/sdb2)
root		(hd1,1)
kernel		/boot/vmlinuz-2.6.20-16-generic root=UUID=4fa60d9a-d5c3-4e03-9edd-e097baef7ad7 ro single 
initrd		/boot/initrd.img-2.6.20-16-generic
savedefault
boot


# This entry automatically added by the Debian installer for an existing
# linux installation on /dev/sdb2.
title		Ubuntu, kernel 2.6.20-15-generic (on /dev/sdb2)
root		(hd1,1)
kernel		/boot/vmlinuz-2.6.20-15-generic root=UUID=4fa60d9a-d5c3-4e03-9edd-e097baef7ad7 ro quiet splash 
initrd		/boot/initrd.img-2.6.20-15-generic
savedefault
boot


# This entry automatically added by the Debian installer for an existing
# linux installation on /dev/sdb2.
title		Ubuntu, kernel 2.6.20-15-generic (recovery mode) (on /dev/sdb2)
root		(hd1,1)
kernel		/boot/vmlinuz-2.6.20-15-generic root=UUID=4fa60d9a-d5c3-4e03-9edd-e097baef7ad7 ro single 
initrd		/boot/initrd.img-2.6.20-15-generic
savedefault
boot


# This entry automatically added by the Debian installer for an existing
# linux installation on /dev/sdb2.
title		Ubuntu, memtest86+ (on /dev/sdb2)
root		(hd1,1)
kernel		/boot/memtest86+.bin  
savedefault
boot

```

---

### Post by Coucouf on 2007-10-18
I've had a similar problem with my system since I tried Feisty x86_64 (Athlon X2+nForce4+X800XL).
It freezes just after GRUB when the splash screen is enabled. This looks like a bug in the graphic driver when changing the resolution for the splash, and for me it happens only with the x86_64 version. The 32-bit version works correctly.

A workaround if you have the same problem is to remove the 'splash' boot option, but you'll never get the splash screen.

conehead77> try removing it from the kernel line of your first boot entry in your menu.lst :
```
title Ubuntu 7.10, kernel 2.6.22-14-generic
root (hd0,5)
kernel /boot/vmlinuz-2.6.22-14-generic root=UUID=3da925ff-a8d3-4f21-bec9-a5bc4f9b35de ro quiet
```

If like me someone has a freeze when starting the x86_64 live CD, you can also remove the 'splash' option from the live CD boot options.
Press **F6** while on the **first entry of the boot menu**, and remove 'splash' from the end of the line.
You you should try and change the boot line from something like :
(...) quiet splash --
to
(...) quiet --

---

### Post by qkslvr221 on 2007-10-18
I have this same problem, except mine does it on the livecd as well. I've tried using F4 to change the resolution setting, but that didn't help. 

I boot the livecd, hit enter, kernel loading, see "kernel is active" at the bottom of the screen, and then nothing but a blank screen. I don't hear any sounds or anything, and the hard drive activity stops after about 90 seconds.

AMD Athlon x2 6000+
4GB DDR2-800
eVGA 8800GTS 640MB
DFI NF5 motherboard

Oh, and I'm using ubuntu-7.10-desktop-amd64.iso

---

### Post by spiraloid on 2007-10-18
I can also confirm this bug. Happens on the LiveCD and as a result I cannot even install. How can this exist in a final release? Why did the RC pass RC phase with this still happening? This is happening on common hardware setups, reliably.

Hardware:
AMD Athlon64 X2 3800+
ASUS A8N-SLI Deluxe
nVidia GeForce 8800 GTS

Ubuntu 7,10 -final-

I've tried removing the splash and silent parameters from the LiveCD boot, and still it did not work. The i386 LiveCD boots fine on the same machine (in fact, I am posting this from it).

---

### Post by Pnevma on 2007-10-18
> **qkslvr221 said:**
> I have this same problem, except mine does it on the livecd as well. I've tried using F4 to change the resolution setting, but that didn't help. 

I boot the livecd, hit enter, kernel loading, see "kernel is active" at the bottom of the screen, and then nothing but a blank screen. I don't hear any sounds or anything, and the hard drive activity stops after about 90 seconds.

AMD Athlon x2 6000+
4GB DDR2-800
eVGA 8800GTS 640MB
DFI NF5 motherboard

Oh, and I'm using ubuntu-7.10-desktop-amd64.iso

Yep, same exact problem here as well.

Q6600 Core 2 Quad
IP35 Pro
XFX 8600GT
2GB mushkin

---

### Post by Silent Ninja on 2007-10-18
I've got something similar to this, I'm running a Sempron 3500+ (64bits), and it has the nVidia go 6100, and I can't go thru the splash screen.. it doesn't even appear. When I've installed it, I've noticed that if I start with the VGA mode, it hangs up on the screen load. Although, when I've set the 1024x768 screen size, it automaticaly changed it to 1280x768 (i'm using a widescreen laptop), and worked, but It doesn't start up.. is there anything that I can do to make it work?

---

### Post by Yannovitch on 2007-10-18
Hello

it comes only from 64 bit, and for many users, with nvidia or last ati cards.
for me 2, and I don't remember where I can find the log of the splash, so I would appreciate to have this log, because I want to change ipw3945 > iwl3945 and I would like to know what kernel thinks of this ^^

---

### Post by cdekter on 2007-10-18
I tried out the live CD of the release version this morning and got the same problem - it would boot up with the progress bar screen, then go to a blank screen. After a while my display goes into standby mode. I was able to get around this by hitting Ctrl + Alt + Backspace. This then brought me to the GDM login screen. After that everything was fine.

My system:
AMD X2 5600+
Nvidia 7900GT
2GB RAM 
etc etc

---

### Post by Octagonal on 2007-10-18
So, is this only happening w/ people that use the DVI connection instead of the VGA connection on their graphics card?

I've had the same problem w/ no splash screen so I removed the splash option passed in the bootup kernel command like what was already posted.  I am also unable to use vga=791 or any other resolution (this worked in Feisty).  I have yet to try the vga connection to see if it's working w/ that.

---

### Post by jaqattack02 on 2007-10-18
> **bkraptor said:**
> I solved my problem following the instructions here: [https://bugs.launchpad.net/ubuntu/+bug/152726](https://bugs.launchpad.net/ubuntu/+bug/152726)

I had this problem with my new install.  I used the above bug fix, and changed it from 1280x1024 to 1280x800 (which is my monitors default resolution).  It may just be me, but not only did it bring back my splash screen, but it seemed to boot a bit faster.

---

### Post by conehead77 on 2007-10-18
> **Coucouf said:**
> You you should try and change the boot line from something like :
(...) quiet splash --
to
(...) quiet --
This is working for me, thanks a lot!

---

### Post by chris86wm on 2007-10-19
> **bkraptor said:**
> I solved my problem following the instructions here: [https://bugs.launchpad.net/ubuntu/+bug/152726](https://bugs.launchpad.net/ubuntu/+bug/152726)

This fixed the problem with me. Boot screen is up and running and it boots much faster now for some reason.

I'm running an Inspiron 6000

---

### Post by Pnevma on 2007-10-19
Use the alternative CD, it fixes the problem - though, after installing I still don't see the boot splash screen.

---

### Post by penguin957 on 2007-10-19
I just had to disable the splash screen altogether so it would boot with dvi.  When i tried to boot with a vga monitor it lost connection for a second but then i got to the login screen.  I've tried everything i've seen and still cant get it to work.  Eh, but I guess a splash screen isn't everything...

---

### Post by ubuntu dave on 2007-10-19
There are a few different bugs being talked about in this thread which is really bad for those trying to debug their own setup. 

The boot splash causing kernel panic with x86_64 installs is pretty common and, if you have this bug, will appear for the LiveCD as well as for an install. Straight after grub/the liveCD boot menu, you'll kernel panic and nothing at all will happen. No amount of ctrl+alt+backspace etc will fix it. Simply removing the 'splash' boot parameter should fix the problem.
(If this is your problem you'll not get to the GDM and you'll probably have keyboard lights blinking. - It's easy to fix at least)

Other 'similar' issues might be related to boot resolution options or graphics card drivers, but they're quite separate. No boot splash but still being able to eventually get to the GDM/gnome desktop can probably be corrected by editing your usplash resolution or something similar. If you get no boot splash and no GDM, you probably have multiple problems of graphics card drivers and incorrect usplash resolution.

As far as I know, only the kernel panic boot splash issue is specifically x86_64.

---

### Post by picopir8 on 2007-10-19
I am surprised that this still has not been fixed as there are now a number of bug reports on this problem. 

The 64 bit beta installed fine for me but I had no splash.  Yesterday I did a clean install with the official release and I got a blank screen and was unable to install.  I was able to fix it by booting with the "compatible video mode" option in the boot menu.  So most people should be able to do that or hit the function key that allows you to edit the boot command and then remove splash there.

---

### Post by eyelessfade on 2007-10-19
[https://bugs.launchpad.net/ubuntu/+source/usplash/+bug/147623]("https://bugs.launchpad.net/ubuntu/+source/usplash/+bug/147623")

---

### Post by rikis on 2007-10-19
I installed 7.10 yesterady.

I notice that the splash screen was a little different than the one i used to have from 7.04 but I didn't really care. Then I was playing around with the screen resolution and at some point the screen went blank. I restarted my computer and since then the splash screen has gone.

I am using the 64 bit version on an ATI.

---

### Post by DRAGONPOWER on 2007-10-20
help plz. can someone tell me how to fix the boot screen, its always black when i boot, even in installation nothing appeared. it shows me grub, then after a while the login screen comes up>? im running gusty 64-bit hp laptop dv9000 nvidia.

---

### Post by crjackson on 2007-10-22
> **DRAGONPOWER said:**
> help plz. can someone tell me how to fix the boot screen, its always black when i boot, even in installation nothing appeared. it shows me grub, then after a while the login screen comes up>? im running gusty 64-bit hp laptop dv9000 nvidia.

Here you go...  This was originally posted by "malcam" in a thread about slow booting, but it's the same thing.  Read it all before you try.

[quote=malcam]Rough translation, although I don't speak newbie that well. 

Open terminal, (ie Applications > Accessories > Terminal), then type:

```
sudo nano -w /etc/usplash.conf
```

As aways, sudo will require you to enter your password.

Change the xres to 1024 and the yres to 768.

Hold down Ctrl and X, release those keys, press Y and press Return.

```
sudo nano -w /boot/grub/menu.lst
```

Hold down Ctrl and W, release those keys, type "vga=794" (without quotes) and press Return. This will take you to the correct part of the file. Now, type "defoptions=vga=794" (without quotes) in the blank line below the one that starts with "# defoptions=quiet".

Hold down Ctrl and X, release those keys, press Y and press Return.

Then type: ```
sudo update-initramfs -u -k `uname -r`
```

Bear in mind I haven't told you how to make copies of each of the files, so be careful not to make a mistake.
[/quote]

---

### Post by thegr8brian on 2007-10-24
> **crjackson said:**
> Here you go...  This was originally posted by "malcam" in a thread about slow booting, but it's the same thing.  Read it all before you try.
did not work for me...I think its because I am using a widescreen...maybe it would help if someone could tell me the vga code for a 1280x800 screen...im on an acer 5920g laptop with the nvidia 8600m GT

---

### Post by crjackson on 2007-10-24
> **thegr8brian said:**
> did not work for me...I think its because I am using a widescreen...maybe it would help if someone could tell me the vga code for a 1280x800 screen...im on an acer 5920g laptop with the nvidia 8600m GT

I think it's hit and miss.  It worked on my laptop with 1280x800, but wouldn't work on my desktop at all.  I tried various settings on the desktop system and It just won't boot unless I completely disable the splash screen.

---

### Post by jaybombalous on 2007-10-27
```
Cannot find /lib/modules/uname -r
```

what does this mean? it means u can't type things in properly!!!!! ;)


those are not apostrophes.

---

### Post by crjackson on 2007-11-12
I've tried SO many times to fix this on my main desktop at the house.  This is the only one I can't seem to fix the splash screen issue on.  I just have to leave nosplash in the grub or else it won't even boot.

However...  I was having an issue whereby my system would boot into an ultra high resolution about 75% of the time, instead of my selected resolution.  By using the methods listed above, but staying with NOSPLASH, it now seems to boot to normal desktop resolution every time.

I was having to boot, and then do a ctrl+alt+backspace to correct the problem most of the time.  Even the resolution applet would show the desired resolution was selected.  Using the applet had no effect on desktop resolution when I got a bad boot.  After using the ctrl+alt+backspace however, the applet then worked as normal, but it was not needed at that point since restarting X fixed the problem anyway.

Now, it seems to work correctly all the time.  I just can't get a danged splash screen. :mad:

---

### Post by crjackson on 2007-11-12
> **crjackson said:**
> I've tried SO many times to fix this on my main desktop at the house.  This is the only one I can't seem to fix the splash screen issue on.  I just have to leave nosplash in the grub or else it won't even boot.

However...  I was having an issue whereby my system would boot into an ultra high resolution about 75% of the time, instead of my selected resolution.  By using the methods listed above, but staying with NOSPLASH, it now seems to boot to normal desktop resolution every time.

I was having to boot, and then do a ctrl+alt+backspace to correct the problem most of the time.  Even the resolution applet would show the desired resolution was selected.  Using the applet had no effect on desktop resolution when I got a bad boot.  After using the ctrl+alt+backspace however, the applet then worked as normal, but it was not needed at that point since restarting X fixed the problem anyway.

Now, it seems to work correctly all the time.  I just can't get a danged splash screen. :mad:

If anyone has some other suggestions, please jump in.  I'm game to try anything...

---

### Post by Lonthong on 2007-11-14
> **crjackson said:**
> If anyone has some other suggestions, please jump in.  I'm game to try anything...

Have you tried the values in the table listed in following [link]("http://ubuntuguide.org/wiki/Ubuntu:Gutsy#Fix_Slow_boot.2Ffaulty_splash_screen")?
I have the same problem & that solution works for me.

---

### Post by crjackson on 2007-11-14
> **Lonthong said:**
> Have you tried the values in the table listed in following [link]("http://ubuntuguide.org/wiki/Ubuntu:Gutsy#Fix_Slow_boot.2Ffaulty_splash_screen")?
I have the same problem & that solution works for me.

Yes, I tried that already.  It worked on my laptop but not on my desktop.

---

### Post by Kurumi on 2007-11-14
I had the same issue with my x64 install as well.

My 8800 GTS would not like the LiveCD install.  Nor did it like booting with the splash screen.  I had to boot into recovery mode and edit out the splash line in the boot menu for it to boot normally.

---

### Post by crjackson on 2007-11-14
> **Kurumi said:**
> I had the same issue with my x64 install as well.

My 8800 GTS would not like the LiveCD install.  Nor did it like booting with the splash screen.  I had to boot into recovery mode and edit out the splash line in the boot menu for it to boot normally.

Thanks for the input.  If you'll look back a few posts, you'll see that's what I've been doing since day one.  I know how to do all that, what I want is to get the splash screen to actually work.

---

### Post by crjackson on 2007-11-15
Well I've tried every combination of settings I can find and nothing works.

---

### Post by delconis on 2007-11-28
AMD 4200x64 Dual Core
1024megs of DDR2 Dual Channel
Nvidia 8800 GTS Pci-Ex16 320meg. Sli, Dvi Connections.
300gig sata2 7200 Rpm Hd.
Nivida N-Force 4 Mother Board chipset.

Ok. I try installing Ubuntu with the live CD but i would get no screen. So i got the Alterntive Downlad and installed it. Well apon boot i get nothing for the screen. I've tryed the CTRL ALT BCKSPC with no luck. Also the Ubuntu install is the X64 version. i'm woundering if my card is just not supported or what. i'm new to linux so i'm a little iffy about what really is wrong. But i thought i would post here for hopefully future fixes and whatnots. But i guess i'll try the i386 version and see if i get any better luck. If it does work i would guess it's a nivida issue.

---

### Post by ZachSka87 on 2007-11-28
Nono! All you have to do is press F6 to see your boot commands before booting the Live CD, delete "quiet" from that line and change "splash" to "nosplash"

You will also need to configure this in Grub after the install. Happy Ubuntu-ing!

---

### Post by hodge24 on 2007-12-01
Hi,

I found this problem was because my /etc/usplash.conf file had the xres and yres values set to 1280 and 1024 respectively. However, my notebook is "widescreen", and the desktop resolution set to 1280x800. So, I edited the usplash.conf file and set the values to:

xres=1280
yres=800

by running

```
gksu gedit /etc/usplash.conf
```

and editing/saving the new values.

After rebooting, the splash screen was displayed again!

Hope that helps,

Hodge

---

### Post by raven on 2007-12-02
What solved my blank screen
changed values in /etc/usplash.conf to 1024x768

added to /etc/initramfs-tools/modules at the end "vesafb and fbcon"
some might need "vga16fb" I did not needed it in my case

I modified /etc/modprobed/blacklist-framebuffer and commented out "blacklist vesafb" with #

in terminal sudo update-initramfs -u
and reboot...
my usplash appeared

than I downloaded startupmanager to manage the usplash themes and some other startup settings now it is working fine...

hardwares:
Intel core 2 Quad Q6600
mobo gigabyte [SIZE=-1]GA-P35C-DS3R
Nvidia 8600GT

[/SIZE]hope this help someone

---

### Post by sandysandy on 2007-12-02
i have a basic doubt. 
i have updated the splash screen with this URL
[https://help.ubuntu.com/community/USplash](https://help.ubuntu.com/community/USplash)

now i get a splash screen when shutting down computer and also when the computer is booting up.

i wanted to know whether i can get a splash screen (like Open SUSE has) when selecting the operating system at start up. i have quadruple boot with XP, Mandriva, Edubuntu and open suse. Menu.lst being followed is that of edubuntu.

at present the GRUB gives options of booting on a black background.
wanted some image or colour.

thanks

---

### Post by dlpfmVfH on 2007-12-10
> **raven said:**
> What solved my blank screen
changed values in /etc/usplash.conf to 1024x768

added to /etc/initramfs-tools/modules at the end "vesafb and fbcon"
some might need "vga16fb" I did not needed it in my case

I modified /etc/modprobed/blacklist-framebuffer and commented out "blacklist vesafb" with #

in terminal sudo update-initramfs -u
and reboot...
my usplash appeared

than I downloaded startupmanager to manage the usplash themes and some other startup settings now it is working fine...

hardwares:
Intel core 2 Quad Q6600
mobo gigabyte [SIZE=-1]GA-P35C-DS3R
Nvidia 8600GT

[/SIZE]hope this help someone

Thanks, this worked for me too

my hardware:
Intel core 2 Quad Q6600
mobo asus p5n-e sli
Nvidia 8500gt (silent)

maybe you're on to something !

---

### Post by lmellor on 2007-12-11
This worked for me too, I think the lad's cracked it!

Now to figure out how to center my usplash screen...

---

### Post by crjackson on 2007-12-12
> **lmellor said:**
> This worked for me too, I think the lad's cracked it!

Now to figure out how to center my usplash screen...

Not for all of us.  I have an Nvidia 7900 GTO coming in today.  Perhaps that will fix it for me...

---

### Post by Brando569 on 2007-12-12
i thought this was only a problem with the 8600GT(S)s, it works fine with my 7600GT but when i put my 8600GTS in i got the blank bootsplash but then it would start x and all would be well. ill try a few of these and let everyone know what one works.

---

### Post by crjackson on 2007-12-14
Okay, so I installed my new 7900 GTO and now I have working boot splash.  It's great finally.

The only issue is that when I get my login screen, the resolution is at 640x480.  It didn't used to do this until I started mucking around with the splash screen.

The splash screen itself is working at 1024x768.  Does anyone know how to make the login screen match?

---

### Post by gamma on 2007-12-18
Am I doing something wrong? I'm on a Dell XPS 1330 and I don't see the bootsplash even after editting my usplash.conf and reupdating usplash.

---

### Post by tedk89 on 2007-12-25
I am running 
t7400 2.2ghz
4gb ram
nvidia 8600m gt w/256mb vram
64bit 7.10

I did two things to fix my splash screen 

step one

 edit the file: gksu gedit /etc/usplash.conf

 change the resolution inside the conf file by mine (it was 1680x1680) which was not a supported res for my screen,  since I was not sure what was loaded at what times during boot I set it to a low but supported res for my screen which was 1024x768 than I ran : sudo update-initramfs -u


step two 

 edit your /boot/grub/menu.lst
On line 132 where it says splash put vga=791 at the end, and rebooted. Upon reboot I was very happy to have my spash screen back.

---

### Post by Laryllan on 2008-01-02
Gutsy disables framebuffer drivers by default.

Feel free to take a look at this solution please:
[http://ubuntuforums.org/showpost.php?p=4057740&postcount=3](http://ubuntuforums.org/showpost.php?p=4057740&postcount=3)

It works for me.

---

